Core/OfficeDevPnP.Core/Utilities/PnPMonitoredScope.cs
To allow for creating a monitored scope without name. Name then defaults to calling method.
=> Created overloaded PnPMonitoredScope constructor

Core/OfficeDevPnP.Core/Framework/TimerJobs/TimerJob.cs
Changed TimerJob class from using NetworkCredential.Password to NetworkCredential.SecurePassword to prevent using insecure string as storage for passwords.
=> Implemented usage of NetworkCredential.SecurePassword

Core/OfficeDevPnP.Core.Tests/AppModelExtensions/SecurityExtensionsTests.cs, Core/OfficeDevPnP.Core/AppModelExtensions/ClientObjectExtensions.cs, Core/OfficeDevPnP.Core/AppModelExtensions/SecurableObjectExtensions.cs, Core/OfficeDevPnP.Core/AppModelExtensions/SecurityExtensions.cs, Core/OfficeDevPnP.Core/OfficeDevPnP.Core.csproj
Current implementation relies only on Web object to apply permission to. Some methods reworked to accept any SecurableObject (Web, List, ListItem).   
Note according breaking inheritance: caller should take care about breaking inheritance when make a call to AddPermissions....
=> Improved SecurityExtensions methods to be called on any SecurableObject (i.e. Web, List, ListItem).

Core/OfficeDevPnP.Core/AppModelExtensions/FileFolderExtensions.cs
Currently FileFolderExtensions.SetFileProperties has checkoutIfRequired parameter, but it is not actually used inside the method. 
I encountered an issue when deploying files (using <pnp:Files> ) to "Pages" library and attempting to set file properties:  "The file "XXX" is checked out for editing by YYY" and found that the reason is that the code is trying to check out file twice.
I assumed, if passed checkoutIfRequired="false", SetFileProperties should not check out the file even if checkout is required by library settings.
Current change takes into account checkoutIfRequired and does not attempt to check out the file if checkoutIfRequired == false
=> Fix for FileFolderExtensions.SetFileProperties to take into account checkoutIfRequired parameter

Core/OfficeDevPnP.Core.Tests/Framework/ObjectHandlers/ObjectTermGroupsTests.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectTermGroups.cs
Fix to first parse tokens in term group name, and check for existing group using parsed name.
=> Term groups provisioning: fix to search by group name with parsed tokens

Core/OfficeDevPnP.Core/Framework/Provisioning/Model/RoleDefinition.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectRegionalSettings.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectSiteSecurity.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectSupportedUILanguages.cs
Added extraction cleanup handling for new object handlers
Write warning that content types are not included when exporting a template from a subweb if lists in subwebs refers to content types.
=> Implemented extraction cleanup handling for new object handlers

Core/OfficeDevPnP.Core.Tests/OfficeDevPnP.Core.Tests.csproj, Core/OfficeDevPnP.Core.Tests/Utilities/UtilityTest.cs, Core/OfficeDevPnP.Core/Utilities/Utility.cs
Now instead of writing something like this: 
if (!web.IsPropertyAvailable("ServerRelativeUrl"))
{
clientContext.Load(web, w => w.ServerRelativeUrl);
clientContext.ExecuteQueryRetry();
}
var serverRelativeUrl = web.ServerRelativeUrl;
you can do just 
string serverRelativeUrl = web.EnsureProperty(w => w.ServerRelativeUrl);
Another examples: 
bool hasUniquePermisions = web.EnsureProperty(w => w.HasUniqueRoleAssignments);
Or 
FieldCollection fields = clientContext.Web.EnsureProperty(w => w.Fields);
Or for multiple properties: 
clientContext.Web.EnsureProperties(w => w.Fields, w => w.ServerRelativeUrl);    
Only one level of property depth supported.
=> EnsureProperty helper method

Core/OfficeDevPnP.Core.Tests/AppModelExtensions/SecurityExtensionsTests.cs, Core/OfficeDevPnP.Core.Tests/Framework/ObjectHandlers/ObjectFilesTests.cs, Core/OfficeDevPnP.Core/AppModelExtensions/BrandingExtensions.cs, Core/OfficeDevPnP.Core/AppModelExtensions/FeatureExtensions.cs, Core/OfficeDevPnP.Core/AppModelExtensions/FileFolderExtensions.cs, Core/OfficeDevPnP.Core/AppModelExtensions/SecurityExtensions.cs, Core/OfficeDevPnP.Core/AppModelExtensions/TaxonomyExtensions.cs, Core/OfficeDevPnP.Core/AppModelExtensions/WebExtensions.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/Connectors/SharePointConnector.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectFiles.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstanceDataRows.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectPages.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/TokenParser.cs
There is an issue with EnsureProperty not accepting properties of type Guid. (Like DefinitionId, Id, etc.). I updated references to those methods where appropriate with a call to EnsureProperties.
=> Updated references from EnsureProperty to EnsureProperties.

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/Extensions/SecurableObjectExtensions.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectTermGroups.cs
Some early versions of CSOM for SP2013 on-premises does not support MajorVersionLimit, so it breaks provisioning if versioning enabled,
=> some provisioning engine fixes

Core/OfficeDevPnP.Core.Tests/AppModelExtensions/ClientObjectExtensionsTests.cs, Core/OfficeDevPnP.Core/AppModelExtensions/ClientObjectExtensions.cs
Now you can write 
```
clientContext.Web.EnsureProperties(w => w.Fields.Include(f => f.Id, f => f.Title), w => w.Url);
```
this will be equal to: 
```
clientContext.Load(clientContext.Web, w=> w.Url,  w => w.Fields.Include(f => f.Id, f => f.Title));
clientContext.ExecuteQueryRetry();
```
Or for single property: 
```
var fields = clientContext.Web.EnsureProperty(w => w.Fields.Include(f => f.Id, f => f.Title)).ToList();
```
equivalent: 
```
clientContext.Load(clientContext.Web, w => w.Fields.Include(f => f.Id, f => f.Title));
clientContext.ExecuteQueryRetry();
var fields = clientContext.Web.Fields;
```
=> Include support for EnsureProperties

Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/XMLPnPSchemaV201508Formatter.cs
Eg.
<pnp:Publishing AutoCheckRequirements="MakeCompliant">
<pnp:AvailableWebTemplates>...</pnp:AvailableWebTemplates>
<pnp:PageLayouts />
</pnp:Publishing>
=> NullReferenceException in formatter when template doesn't contain PageLayout

Core/OfficeDevPnP.Core/AppModelExtensions/FieldAndContentTypeExtensions.cs
FieldAndContentTypeExtensions.AddFieldToContentType does not apply Required=false when adding field link to content type. It ends up in that in situation when provisioning engine add fields marked as required even when you explicitly set Required attribute to false in pnp:FieldRef node.
=> fix for AddFieldToContentType does not set Required=false for field link

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectPages.cs
If Overwrite is True on a Page that is already HomePage, it cannot be deleted. Hence it isn't overwritten.
Eg.
<pnp:Pages WelcomePage="{site}/SitePages/Home.aspx">
<pnp:Page Url="{site}/SitePages/Home.aspx" Overwrite="true" Layout="TwoColumnsHeader">
<pnp:Security>
<pnp:BreakRoleInheritance CopyRoleAssignments="false" ClearSubscopes="false" />
</pnp:Security>
</pnp:Page>
</pnp:Pages>
=> Fixed issue with overwriting HomePage (not possible to delete HomePage)

Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/ProvisioningSchema-2015-08.xsd
An exported template doesn't necessarily contain RoleAssignments.
If it doesn't, the template cannot be imported as it fails verification against the schema.
=> Allow zero instances of RoleAssignment under BreakRoleInheritance

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectPublishing.cs
ctx.Web.GetProvisioningTemplate() throws {"Data at the root level is invalid. Line 1, position 1."}
I added a check in GetAvaliablePageLayouts(Web web) in ObjectPublishing.cs to handle this error:
// if (defaultLayoutXml != null)
if (defaultLayoutXml != null && defaultLayoutXml != "__inherit")
{
defaultPageLayoutUrl = XElement.Parse(defaultLayoutXml).Attribute("url").Value;
}
=> Getavailabepagelayoutfix

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectComposedLook.cs
In ObjectComposeLook.cs, there is an access to the properties AlternateCssUrl and SiteLogoUrl of the web object. Unfortunately, both properties are within a conditional compilation clause and are sometimes not loaded when they are accessed afterwards.
=> Accessing missing properties due to conditional compilation

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectExtensibilityProviders.cs
This is alternative solution to PR #71 (https://github.com/OfficeDev/PnP-Sites-Core/pull/71) tokens in configuration data are replaced before data is passed to provider. If you merge it, please close PR #71
=> provision extensibility providers token parsing

Core/OfficeDevPnP.Core/Framework/Provisioning/Model/ProvisioningTemplate.cs
Sometimes, saving to a file is not necessary. A simple string is enough for further processing.
=> ToXML for ProvisioningTemplate

Core/OfficeDevPnP.Core.Tests/AppModelExtensions/SecurityExtensionsTests.cs, Core/OfficeDevPnP.Core/AppModelExtensions/SecurityExtensions.cs
This code:
```
clientContext.Web.AddPermissionLevelToGroup(_testGroupName, RoleType.Contributor, true);
clientContext.Web.AddPermissionLevelToGroup(_testGroupName, RoleType.Contributor, false);
```
throws an exception `The permission level specified is already added to the collection` in current pnp version. But sometimes in complex scenarios it is possible that code tries to set same permission twice. This was fixed. Also simplified methods `AddPermissionLevelImplementation` and `RemovePermissionLevelImplementation`
=> Fixed exception thrown when trying to assign same permission twice. 

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectHandlerBase.cs
String comparison was failing due to Uri r encoding webUrl, this change decodes the PathAndQuery so that url.IndexOf is successful if there are any escaped characters.
=> ObjectHandlerBase.Tokenize 'url.IndexOf' failing on encoded Uri

Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/XMLPnPSchemaV201508Formatter.cs
Fix for the following issue:
- Create new template (automatically creates empty instance of ComposedLook)
- Do not set ComposedLook
- Save template to XML file - will create ComposedLook node with empty attributes
- Try to read template from resulting XML file
Current fix compares current composed look with empty one, and saves it only if it is not empty.
=> XMLPnPSchemaV201508Formatter - Fix to not to serialize empty ComposedLook

Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/XMLPnPSchemaV201508Formatter.cs
Serialize object Security only if it is not empty (File.Security is automatically initialized to empty ObjectSecurity object. When template is applied (ObjectFiles) code does check if security object is not empty and only then applies. But on serialization it did not check and produced empty Security nodes in XML files )
=> Serialize object Security only if it is not empty

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectExtensibilityProviders.cs
When using/developing extensibility providers it’s difficult to follow the execution when exceptions inside the providers isn’t exposed. You could use the trace log capabilities but that give you a little bit too much, I just what the error.
Suggestion:
- Log the exception as an error
- Rethrow the exception
=> Rethrow provider exceptions

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectLookupFields.cs
When a lookup field is created/update the List attribute is temporarily removed.
In this case the field cannot be created if RelationshipDeleteBehavior is set.
I've fixed this issue and is also making sure Indexed attribute is set to True if RelationshipDeleteBehavior is either Cascade or Restrict.
=> Added support for lookup fields, which isn't a site column

Core/OfficeDevPnP.Core/AppModelExtensions/NavigationExtensions.cs
When applying custom action to onprem (site level) I get a "unknown error" when CommandUIExtension is set to empty string
=> Fix for custom actions onprem

Core/OfficeDevPnP.Core/AppModelExtensions/BrandingExtensions.cs
Changes to GetCurrentComposedLook method, to work also in sites not in english. In English sites the current name of the theme is "Current" but in finnish sites ex. its "Nykyinen", so the method will fail. But if we use the id of the item, which is always 1, then we will get always the right theme.
=> Changes to GetCurrentComposedLook method

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectContentType.cs
FieldLinks collection not always (never in my case when testing onprem) initialized. This causes runtime exceptions, failing the process of adding the provisioning template.
Adding a single line of code to ensure the FieldLinks collection always is initialized
=> FieldLinks collection not always initialized causing runtime exceptions 

Core/OfficeDevPnP.Core/AppModelExtensions/BrandingExtensions.cs
It is possible that the Theme.Name property returns Null. This will be handled by the fix provided in this Pull Request.
=> NullReferenceException while accessing Theme.Name 

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectFiles.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectPages.cs
When provisioning files "inside" a list (not library) the object handler for files do a checkout (which succeeds) but the checkin fails with "Unknown Error".
When provisioning pages onprem and setting the welcome page the ServerRelativeUrl property fails with an uninstantiated error.
=> Fixes for provisioning files to list and setting welcome page onprem

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectContentType.cs
Fix for issue #174 that ensures that the columns of the Content Type have the same order as specified in the template.
=> Ensure Content Type Column order

Core/OfficeDevPnP.Core/AppModelExtensions/FieldAndContentTypeExtensions.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs
This is to address a specific scenario when OOTB PWA lists can not be updated as they are centrally managed.
=> Added a check so that if no bindings were actually added then the SetDefaultContentTypeToList method will not be executed.

Core/OfficeDevPnP.Core.Tests/Framework/ObjectHandlers/ObjectListInstanceTests.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs
Fix for issue #212: The Folder content type should not be deleted from a created document library even if the Remove Existing Content Types -flag is set in the template.
=> Fix for #212: Do not delete folder content type from provisioned document libraries

Core/OfficeDevPnP.Core/AppModelExtensions/ExternalSharingExtensions.cs
The *ExternalSharingExtensions* class was not set to public, making it unable to use in other applications.
=> Making ExternalSharingExtensions class public

Core/OfficeDevPnP.Core/Framework/Provisioning/Model/Page.cs
Page element in provisioning template is parsed in a way that Security property is not null, even if Security element for the page is not specified. That brings trouble with permissions removal for the page, when Security element is omitted.
=> fix for provisioning engine pnp:Page parsing

Core/OfficeDevPnP.Core.Tests/Framework/ObjectHandlers/ObjectListInstanceTests.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs
Currently when the provisioning engine changes the list title, the new title is not available as a token in the TokenParser. This makes the following scenario quite hard:
1. Provisioning template is used to rename an out-of-the box SharePoint list (for example Documents -library)
2. If the listId is needed in the template (for example in the webpart definitions), the template must use the {listid:Documents} token since that was the original title of the library and the updated title is not available as a token.
3. Later on some changes are made to the template and the template is reapplied to the existing site.
4. But now the {listid:Documents} token no longer works, since the Document library title has been changed when the template was applied the first time.
So we cannot create a …
=> Make updated list titles available as tokens in the Provisioning Engine

Core/OfficeDevPnP.Core/AuthenticationManager.cs, Core/OfficeDevPnP.Core/OfficeDevPnP.Core.csproj, Core/OfficeDevPnP.Core/Utilities/CookieReader.cs, Core/OfficeDevPnP.Core/packages.config
**Browser-based login and context creating, trough the Browser control.**
Had a project where we had multi-factor authentication and federated adfs authentication enabled at the tenant also app passwords didn't work and we really needed the provisioning engine.
So i put together this browser-based login that uses the WinForms WebBrower control and catches the auth cookies. Manly based on [Remote authentication in SharePoint Online](https://code.msdn.microsoft.com/Remote-Authentication-in-b7b6f43c).
It worked for us and maybe somebody else will find it useful.
=> Browser-based login

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectHandlerBase.cs
Changed Tokenize back to allow tokenization of propertybag values (no only urls).
Eg.
Within "ObjectPropertyBagEntry.ExtractObjects" propertybag values are tokenized.
foreach (PropertyBagEntry propbagEntry in template.PropertyBagEntries)
{
propbagEntry.Value = Tokenize(propbagEntry.Value, web.ServerRelativeUrl);
}
=> ObjectHandlerBase Tokenize

Core/OfficeDevPnP.Core/Diagnostics/Log.cs
The Log.cs class contains some apparent copy/paste bugs. For example that the Warning methods aren't checking if the logLevel is actually warning or debug, but only debug.. Or that the same method checks for logLevel "information" rather than "debug" (there's a separate method for logLevel == Information)..
Also fixed a bug where one of the Error methods were incorrectly calling .Info() instead of .Error().
=> Loggingfixes

Core/OfficeDevPnP.Core.Tests/Framework/ObjectHandlers/ObjectFilesTests.cs, Core/OfficeDevPnP.Core.Tests/OfficeDevPnP.Core.Tests.csproj, Core/OfficeDevPnP.Core.Tests/Resources/EditForm.aspx, Core/OfficeDevPnP.Core.Tests/Resources/Templates/ProvisioningTemplate-2015-03-Sample-01.xml, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectFiles.cs
I've added two test cases and a bug fix for the following issue:
CheckOutIfNeeded is not honoring the default behavior dictated by forcecheckin on lists. This has the effect that 
1) we will not be able to add webparts to forms 
2) we will not be able to upload files (to lists with forcecheckin=false) unless all required parameters are set
Usecase for 1) is pretty obvious (e.g. a ContentEditor with some additional info, or a listview webpart etc)
Usecase for 2) is cases when you want to pre-populate a document library with files, where even required attributes are empty. If the user wants to modify these files in any way they have to fill in the required attriburtes. If, however, we have to pre-populate all these fields with some dummy values (or "not set" values), the user can freely …
=> Not honoring forcecheckin will cause sideffects

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/TokenParser.cs
Make TokenParser class public so it can be used in external providers to parse external files (e.g. web part definitions etc.)
=> TokenParser public

Core/OfficeDevPnP.Core/AppModelExtensions/WebExtensions.cs
There is redundant method call (GetWebTemplate()) in the extension 
GetProvisioningTemplate(this Web web).
This method already called in the in the constructor of the class "ProvisioningTemplateCreationInformation"
=> Removed redundant method call GetWebTemplate()

Core/OfficeDevPnP.Core/AppModelExtensions/ListRatingExtensions.cs
On O365 an List that has been created using CSOM (in Hostweb) will end up throwing this error when trying to enable Ratings. 
But there seem to be no problem in creating Ratings in that list. So removing this Exception just makes it work.
MAYBE instead of removing that line, adding a "bool forcePublishingWeb=true" as additional Parameter might be even worth considering
=> Removing validation for PublishingWeb

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectContentType.cs
Setting DocumentTemplate does not work currently for initial deployment in the current implementation due to the content type not being updated _after_ setting the documenttemplate property. This PR fixes that issue.
Note: in the current implementation (pre this PR) running a template twice or more on a site will update the DocumentTemplate property, this is due to the UpdateContentType handling things correctly.
I.E. to test this fix you need to try on a fresh site collection
=> Fix: DocumentTemplate property of ContentTypes would not be set on initial deployment

Core/OfficeDevPnP.Core/AppModelExtensions/ListRatingExtensions.cs
If SetRating() is called multiple times (eg. switching from none to "VotingExperience.Likes" to "VotingExperience,Rating") each time the fields are added to the view. Resulting in something like this:
http://ibin.co/2Y5QoWk8u5jS
Added removing already existing Fields (only in the view) before adding the new ones.
=> Remove already existing fields before adding new ones to default view

Core/OfficeDevPnP.Core.Tests/AppModelExtensions/BrandingExtensionsTests.cs, Core/OfficeDevPnP.Core.Tests/AppModelExtensions/PageExtensionsTests.cs, Core/OfficeDevPnP.Core.Tests/AppModelExtensions/TenantExtensionsTests.cs, Core/OfficeDevPnP.Core.Tests/Framework/ObjectHandlers/ObjectFilesTests.cs, Core/OfficeDevPnP.Core.Tests/Framework/ObjectHandlers/ObjectPagesTests.cs, Core/OfficeDevPnP.Core/AppModelExtensions/BrandingExtensions.cs, Core/OfficeDevPnP.Core/AppModelExtensions/FileFolderExtensions.cs, Core/OfficeDevPnP.Core/AppModelExtensions/ListExtensions.cs, Core/OfficeDevPnP.Core/AppModelExtensions/PageExtensions.cs, Core/OfficeDevPnP.Core/AppModelExtensions/WebExtensions.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/Connectors/SharePointConnector.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectLookupFields.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectPageContents.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectPages.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectPublishing.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectWebSettings.cs, Core/OfficeDevPnP.Core/Utilities/UrlUtility.cs
With the exception of class "UrlUtility", all other utility classes have namespace "OfficeDevPnP.Core.Utilities".
=> Changed namespace for the utility class UrlUtility

Core/OfficeDevPnP.Core.Tests/Framework/Connectors/ConnectorSharePointTests.cs, Core/OfficeDevPnP.Core.Tests/OfficeDevPnP.Core.Tests.csproj, Core/OfficeDevPnP.Core.Tests/Resources/TestDefault.aspx, Core/OfficeDevPnP.Core/Framework/Provisioning/Connectors/FileConnectorBase.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/Connectors/SharePointConnector.cs
Modified SharePoint connector to use web root folder rather than list folder when container is not supplied.
Addresses issue when generating a template using the provisioning engine from a site where the welcome page is for example default.aspx in site root folder rather than a page in a list.
=> Modified SharePoint connector to use web root folder rather than list folder when container is not supplied 

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectFiles.cs
Fix for checking if a field is not read only before trying to set the value when setting a files properties.
Not sure why this was previously commented out, but without this check we are unable to add a publishing page as it errors when trying to set a value on a read only field.
=> Adding Publishing Pages - Read only field fix

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectPages.cs
This fixes an error where if the wiki page doesn't exist and the PageLayout is Custom it fails to create them, but running again will work. This was because the check for the Custom pagelayout wasn't included in the code block for non-existing wikipages and was present for the existing wiki pages.
=> Fix for adding Wiki Home Page during creation

Core/OfficeDevPnP.Core/AppModelExtensions/FieldAndContentTypeExtensions.cs
Added Support for the following child elements of a Content Type inheriting from 'Document Set': AllowedContentTypes / SharedFields / WelcomePageFields
(Code Note: I added template.update(true) after every addition because if I didn't do that it would somehow only save the last item. Weird behavior!)
=> Added Support for the following xml-elements: AllowedContentTypes/SharedFields/WelcomePageFields

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectPageContents.cs
It now checks if the WelcomePage url is empty or not, without this the folder and filename are incorrect in the template
=> Fix for bug when extracting WelcomePage that doesn't belong to a list

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectWorkflows.cs
We were experiencing this issue again for another site where the workflow subscriptions weren't correctly provisioned, now fixed by copying CreatedBySPD property definition value when creating the subscription
=> Fix for #323 Workflows not provisioning correctly

Core/OfficeDevPnP.Core/AppModelExtensions/FieldAndContentTypeExtensions.cs
Added Field extension method to set jsLink
Added List extension to set jsLink on list field
This is very useful for client side rendering templates; being able to jsLink your csr template to a field rather than just a web part.
=> Added SetJsLinkCustomizations site and list fields

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectPageContents.cs
Although the template contained the order for the webparts it was not coming through when provisioning this was because it was not being set, so it has now been added
=> Added Order for Webpart provisioning

Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/XMLPnPSchemaV201512Formatter.cs
When provisioning custom actions without any rights attribute an exception is raised (at basePermissionString.Split)
=> Fix for ToBasePermission when rights attribute not set on custom action

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectFiles.cs
Makes it easier and more readable if we need to extend with more properties.
=> Implemented an array of writeable readonly-fields to replace the check in SetFileProperties

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs
When provisioning it was only check for an existing list by the url but if a list has the same title but different url it would error so it now checks for the list by url and title
=> Fix for List already exists bug when the list title is already in use

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs
Creation of "Site Assets" library is performed using the out of the box EnsureSiteAssetsLibrary method. Proposed fix for issue #512.
=> Create "Site Assets" using EnsureSiteAssetsLibrary

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/Extensions/UserResourceExtensions.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectContentType.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectCustomActions.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectField.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ProvisioningTemplateCreationInformation.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/SiteToTemplateConversion.cs
| Bug fix?        | no ?
| New feature?    |  yes?
| New sample?      | no?
| Related issues?  | mentioned in #547
Added functionality for exporting multi language resource files with the provisioning engine. Requires the PersistMultiLanguageResources property to be true on ProvisioningTemplateCreationInformation. Optionally set ResourceFilePrefix property on ProvisioningTemplateCreationInformation to a prefix other than "PnP_Resources_"
=> Implemented support for extracting multi-language resource values.

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectHandlerBase.cs
If not all tokens where replaced when creating/updating fields there is a great change of ending up with a corrupt field, possible a broken fields collection, especially when provisioning taxonomy fields. This small fix ensure that the provisioning stops when that happens.
A broken fields collection can really mess up the entire site collection, I haven’t been able to fix it, restoring the site collection is the only option.
On-premises if you haven’t got/picked a default TermStore for site collections TermSetsId-tokens will not be replaced, perhaps there should be a warning if GetDefaultSiteCollectionTermStore returns null (TokenParser.cs, line 97)
=> Catch leftover tokens in field xml

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectCustomActions.cs
A UserCustomAction migth not contain a Title or Description. If you PersistMultiLanguageResources it will fail because the Title or Description is null.
I've also changed the use of Title in the resource key to the Name of the UserCustomAction.
=> UserCustomAction localization fix

Core/OfficeDevPnP.Core/Framework/Provisioning/Connectors/OpenXMLConnector.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Json/JsonOpenXMLTemplateProvider.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/XMLOpenXMLTemplateProvider.cs
| Related issues?  | nothing
Removed the encyphering arguments, because we will not provide encryption in the OpenXML connector.
=> Removed cyphering capability from OpenXML

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectFiles.cs
Proposed fix for issue #514. The changed code will try to upload file as usual. If loading the file fails, the filename will be decoded (e.g. "%20" will be converted to a single space) and it will try to read the file with the new filename once more. If the upload fails, a similar workaround will be performed.
=> Upload files with encoded file names in XML

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectField.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectHandlerBase.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs
| Related issues? | [#572](https://github.com/OfficeDev/PnP-Sites-Core/issues/572)
This PR fixes three issues.
1. The termsetid token wasn't set in the field schemaxml because an ExecuteQuery was missing after store.GetTermSet()
2. Only site columns were tokenized. Now also list column taxanomy fields are tokenized.
3. If the TermGroup is a Site Collection Term Group, the group name was inserted in the TermSetId token, and caused the IsFieldXmlValid to fail when provisioning. This is changed to insert the "{sitecollectiontermgroupname}" token.
=> TaxonomyField tokenization fix

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectTermGroups.cs
Valid Scenario: On premises SharePoint 2013
Issue: Framework.Provisioning.ObjectHandlers.ObjectTermGroups:ExtractObjects() previously threw a method not supported exception when attempting to limit term sets to only those which where not the orphan term set. This fix replaces the inline linq query.
=> Fixed not supported linq error when extracting terms sets running OnPremSP2013

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ProvisioningTemplateApplyingInformation.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/SiteToTemplateConversion.cs
Hi,
Please make configurable behavior for applying ObjectPersistTemplateInfo provisioning handler. The point is ObjectPersistTemplateInfo writes to web's property bag so requires FullControl permissions to execute. So when you try to execute only those handlers that require less permissions (e.g. ObjectPages or ObjectFiles) you still need FullControl to apply the template.
This is just a proposal of implementation, feel free to implement it another way.
__
Br, Ivan
=> Configurable behavior for ObjectPersistTemplateInfo handler

Core/OfficeDevPnP.Core/AppModelExtensions/FileFolderExtensions.cs
Bug desciption:
For example, we want to ensure folder path "AAAAAAAAA/BBB/C".
The website ("https://myportal.com/sites/test") contains two libraries: "AAA" and "AAAAAAAAA".
The root folder server relative path:
for library "AAA": "/sites/test/AAA"
for library "AAAAAAAAA": "/sites/test/AAAAAAAAA"
The variable folderServerRelativeUrl = "/sites/test/AAAAAAAAA/BBB/C" 
So, If we call the extension method web.EnsureFolderPath("AAAAAAAAA/BBB/C"), 
the folder may be created in the wrong library (with name "AAA"), because the string "/sites/test/AAAAAAAAA/BBB/C" starts with "/sites/test/AAA".
(as the result we have the incorrect folder server relative path: "/sites/test/AAA/AAAAAA/BBB/C")
This PR fix this bug. As a result, the …
=> Ensure folder fix1

Core/OfficeDevPnP.Core/Framework/Provisioning/Connectors/AzureStorageConnector.cs
When persisting files using the AzureStorageConnector files are stored in the root of the storage container.
This PR adds support for storing files in a subfolder within the storage container.
Eg. "MyStorageContainer/PnPTemplate/MyExportedTemplateFolder/"
=> Support for folders in AzureStorageConnector

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs
When site columns are added to a list, the TitleResource and DescriptionResource isn't inherited from the site column. These explicit need to be set after the field is added.
This fix checks if the site column in the template contains a resource token and then sets the TitleResource or DescriptionResource.
One could argue that using resource token in the FieldRef element is a better solution, however the schema only allows DisplayName in the FieldRef element and not Description.
=> Localization not set on list site columns

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs
Scenario: Extracting lists existing in a sub site with field references to site fields.
Problem: List field references not detected and all fields added as list fields instead.
Fix: Changed ObjectListInstance:ExtractFields() to always load the site fields for comparison from the root spweb in the site collection
=> BUGFIX - Lists in sub sites with field references are extracted with list fields instead

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectSiteSecurity.cs
| Related issues?  | have not checked if there are related issues
fix: check if a group exists with a unparsed title is inconsistent with adding the group with a parsed title. This can result in an exception when a group including {sitename} is used.
changed: 'excessive' parsing to parsing once
fix: if the principal is a sharepoint group, the name of the principal should also replace the site title as is done for sitegroups. If not an inconsistency can occur causing an exception when provisioning the template, the group/principal might not exist.
fix: don't add a role assignment for a principal if the principal is a sharepoint group when sharepoint groups are not included. …
=> Sitegroups

Core/OfficeDevPnP.Core/AppModelExtensions/FileFolderExtensions.cs
As a rule of thumb: one should always use document sets instead of folders. But if folders were used, whether by malicious users or (now) fired developers, you might want to convert them.
=> Added functionality: Convert folder to document set

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, Core/OfficeDevPnP.Core/AppModelExtensions/SearchExtensions.cs, README.md
Added the ability to set the search results page url of the web. Until now, we are able to only set the search settings at the site collection level. Now, using this we would be able to redirect search results of the subsite to a particular page.
=> Added the search results page setting at web level

Core/OfficeDevPnP.Core/AppModelExtensions/NavigationExtensions.cs
Adds `asLastNode` parameter to the `AddNavigationNode` method to control whether new nodes are added to the beginning or end of the collection.`asLastNode` defaults to `true` to match the current behavior.
=> Allow adding navigation nodes at beginning or end

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/TokenParser.cs
| Related issues?  | #630
In TokenParser when web is as SubSite the addition of rootweb ListUrl token is failing becuase the subsite web isn't used when generating the ListUrl.
I've changed the web to rootWeb.
=> Fixed rootweb ListUrl token for subsite

Core/OfficeDevPnP.Core/Framework/Provisioning/Connectors/OpenXML/PnPPackageHelper.cs
Fixes an issue related to an edge case that lead to a backward compatibility issue while handling .PNP files created with the old format (with folders structure) opened and then saved again with the new format (without folders structure).
=> Fix for edge case with backward compatibility issue in folders handling.

Core/OfficeDevPnP.Core.Tests/Framework/Providers/Extensibility/SecureXml.cs, Core/OfficeDevPnP.Core.Tests/Framework/Providers/Extensibility/XMLEncryptionTemplateProviderExtension.cs, Core/OfficeDevPnP.Core.Tests/Framework/Providers/XMLProvidersTests.cs, Core/OfficeDevPnP.Core.Tests/OfficeDevPnP.Core.Tests.csproj, Core/OfficeDevPnP.Core.Tests/Resources/Templates/ProvisioningTemplate-2016-05-Sample-01.xml, Core/OfficeDevPnP.Core.Tests/Resources/Templates/ProvisioningTemplate-2016-05-Sample-02.xml, Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/ITemplateProviderExtension.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Json/JsonTemplateProvider.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/TemplateProviderBase.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/XMLTemplateProvider.cs, Core/OfficeDevPnP.Core/OfficeDevPnP.Core.csproj
| Related issues?  | nothing
Added the capability to register object that implement interface ITemplateProviderExtension in order to handle pre/post-processing during template load/save operations. 
Look at test XMLEncryptionTest to see how to use it in code (we will add support for PowerShell, too) and to see an example about how to do XML Encryption of a provisioning template.
=> Added capability to do pre/post-extensions during template load/save

Core/OfficeDevPnP.Core.Tests/Framework/ObjectHandlers/TokenParserTests.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/TokenDefinitions/ContentTypeIdToken.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/TokenDefinitions/ListIdToken.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/TokenDefinitions/ListUrlToken.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/TokenDefinitions/LocalizationToken.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/TokenDefinitions/ParameterToken.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/TokenDefinitions/TermSetIdToken.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/TokenDefinitions/TermStoreIdToken.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/TokenDefinitions/WebPartIdToken.cs
Some Token classes for the TokenParser have parameters (list name, content type name etc.) that were added to the token without any escaping. TokenParser then creates Regex from token and uses this regex to find the matches in parsed strings.
If those parameters contained special characters that are part of Regex syntax (e.g. "{listid:ListName (ABBR)}" contains brackets ), they got interpreted incorrectly and resulted in tokens not being resolved.
This pull request fixes the issue by doing Regex.Escape. It also contains test to verify the scenarios.
=> Escape tokens to support special characters

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectCustomActions.cs
CommandUIExtension updates should be treated like updating any other property.  This was causing the update to get sent in the next clientContext batch.
=> use isDirty for CommandUIExtension

Core/OfficeDevPnP.Core/AppModelExtensions/FieldAndContentTypeExtensions.cs
Fixed the two DeleteContentTypeById methods to be public, they were accidentally submitted as internal methods.
=> Fixed DeleteContentTypeById methods to be public

Core/OfficeDevPnP.Core.Tests/AppModelExtensions/ListExtensionsTests.cs, Core/OfficeDevPnP.Core/AppModelExtensions/ListExtensions.cs
Added a few ListExists() test cases, and wrote an additional overload that determines if the List exists based on url path.
This is handy to have as when using CreateList method overload you can hard-code url path and at times when lists are renamed, it's hard to determine by title if list already exists.
=> Add ListExists() based on List's url path

Core/OfficeDevPnP.Core.Tests/Framework/ObjectHandlers/ObjectContentTypeTests.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectContentType.cs
Fixing issue where we have fields defined with internal names containing tokens and re-ordering of these. The bug manifested itself through OOB fields getting sorted before our custom fields for no apparent reason. The unittest reflects this scenario.
example 
This field 
`<Field ID="{dd6b7dae-1281-458d-a66c-01b0c7b7930b}" Name="{parameter:TestFieldPrefix}TestField" DisplayName="TestField" Type="Note" Group="PnP" Description="" />
`
Would end up as the last field when referenced like this
```
<pnp:ContentType ID="0x010100503B9E20E5455344BFAC2292DC6FE805" Name="Test Content Type" Description="" Group="PnP}"> …
```
=> Fix: FieldRefs containing replacement tokens are ordered wrong

Core/OfficeDevPnP.Core.Tests/Framework/ObjectHandlers/TokenParserTests.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectSiteSecurity.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/TokenDefinitions/GroupIdToken.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/TokenParser.cs, Core/OfficeDevPnP.Core/OfficeDevPnP.Core.csproj
| Related issues?  | mentioned in issue #503
Adds a groupid token, which returns the ID of a sitegroup. Syntax is as follows:
{groupid:<groupname>} => returns the group id of the groupname specified or to return the id of an associated group:
{groupid:associatedownergroup}  
{groupid:associatedmembergroup}
{groupid:associatedvisitorgroup}
=> Added GroupId token

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectFiles.cs
| Related issues?  | fixes #756 
Fix issue #756 
MetadataMappingFile is set as Empty when is not present in the XML, and code is expecting Null value.
Also, when IncludedExtensions is not set, is set by default as "*.*" and that pattern is not supported later, when filtering the Files in the Directory.
=> Fixing issue 756: Provisioning Framework - issue with Directory Handler.

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectSiteSecurity.cs
| Related issues?  | fixes #656 
Fixes site security provisioning when you only want to provision role assignments or role definitions (OfficeDev/PnP-Sites-Core#656).
=> Fix: Site security RoleAssignments and RoleDefinitions provisioning.

Core/OfficeDevPnP.Core/Utilities/YammerUtility.cs
| Related issues?  |
Added required value "ContentLength = 0" to HttpWebRequest -object in method "PostYammerJson".
Creation of yammer groups is not working without it.
=> fixes an issue which prevents creation of yammer groups

Core/OfficeDevPnP.Core/AppModelExtensions/SecurityExtensions.cs
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| Related issues? | no |
Ignore case in web.IsUserInGroup() extension method. Currently this is a problem for on prem.
```
web.IsUserInGroup("groupName", "DOMAIN\\user"); // => false
web.IsUserInGroup("groupName", "domain\\user"); // => true
```
=> Ignore case of login name for web.IsUserInGroup() extension method

Core/OfficeDevPnP.Core/Framework/Provisioning/Connectors/SharePointConnector.cs
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | yes |
| Related issues? | mentioned in #496 |
Added support for backslash (`\`) as a path separator to the PnP Provisioning Engine's `SharePointConnector`. 
Files which contain paths in their `Src`-attribute cannot currently be imported using the `SharePointConnector` because the Files-handler always adds a  backslash (`\`) in the path if the `Src`-attrbute contains folders. ([source](https://github.com/OfficeDev/PnP-Sites-Core/blob/master/Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectFiles.cs#L440)). As the current `SharePointConnector` supports only forward slash (`/`) as the path separator, it causes an error.
Adding support for backslashes (`\`) in `SharePointConnector` fixes this …
=> Support both "\" and "/" as path separators in SharePointConnector

Core/OfficeDevPnP.Core/Framework/Provisioning/Connectors/SharePointConnector.cs
Fixed incorrect CAML query tag <Valye> to <Value> in SharePointConnector.GetFolders(string)
=> SharePointConnector: fixed CAML query for retrieving folders

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| Related issues? |  |
In the provisioning framework, views couldn't have their display name localized.
<View Name="{2ACBD28D-D2A2-4F97-AC44-DE56F5D7C4E4}" DefaultView="TRUE" Type="HTML" DisplayName="{resource:Glossary}"... did not work and was just giving a view whose display name is {resource:Glossary} in SharePoint. It now works.
=> List instance's view titles can now be localized

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/TokenDefinitions/SiteOwnerToken.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/TokenParser.cs, Core/OfficeDevPnP.Core/OfficeDevPnP.Core.csproj
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| Related issues? | none |
Add ability to use {siteowner} as a token in provisioning templates.
=> Add {siteowner} token to provisioning templates

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectPageContents.cs
| Related issues?  | fixes #754 
This PR adds a possible fix to issue #754 
However, there is a use case that the Engine cannot cover regarding export/import of Content Query WebParts: 
When the CQWP is in the root site, and is pointing to a subsite web, the property would be:
```xml
<property name="WebUrl" type="string">~sitecollection/subsite</property>
```
As we are exporting the root site, and the CQWP is pointing to a subsite that won't exist when importing the template to the new site, this fix won't work (current code without this fix won't work either). I'm afraid we can't cover that use case anyway, as it depends on a subsite.
However, if we are exporting a CQWP in …
=> Possible fix to issue #754

Core/OfficeDevPnP.Core.Tests/Framework/Functional/FunctionalTestBase.cs
If the default site collection uses tenant language, for example Norwegian, then localization tests will fail as they assume 1033/English to be the default.
I also set the the initial quota for storage to 100mb and sandbox resources to 0, to play nice.
=> Set site collection locale to English in tests

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectPropertyBagEntry.cs
| Bug fix?        | yes 
Changed ObjectPropertyBagEntry, context is now cloned from web.Url which is passed in by the function parameter instead of the current context url. 
In my case the Propertybag Entries ended up in the parent Web because the context was still pointing towards that web, while I applied my template to a Web that I retrieved earlier. By taking the Url of the Web passed into the function this problem is solved, it stores the Propertiebag Entries on the correct Web.
=> Fix for Propertybag Entries ending up in the wrong Web.

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/TokenDefinitions/DateNowToken.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/TokenParser.cs, Core/OfficeDevPnP.Core/OfficeDevPnP.Core.csproj
| New feature?    | yes?
Added a new token for provisioning framework : ~now or {now}.
Replaced by DateTime.Now in UTC format. Used in my project to set date fields to now : <pnp:Property Key="ArticleStartDate" Value="{now}"/>
=> Added a new token for {now}

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/Extensions/SecurableObjectExtensions.cs
A parameter/token cannot be used in the RoleDefinition of a RoleAssignment. The parse.ParseString method wasn't used when trying to retrieve the RoleDefinition on the Web. It will not retrieve a RoleDefinition and will produce an error when the RoleDefinitionCollection is empty when adding it to the RoleAssignment.
=> Token is not replaced for a SecurableObjectExtensions.RoleDefinition in SetSecurity

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectFiles.cs
| Bug fix?        | Yes
| New feature?    | No
| New sample?      | No
| Related issues?  | #898 
In case of folder hierarchy more than two level deep with multiple folders as siblings inside a parent folder, the ObjectFiles.cs code fails.
In recursion code below, when you have sibling folder under a parent folder, the code breaks when in case of recursion for second sibling.
foreach (var folder in subFolders)
{
directory.Src += @"\" + folder;
directory.Folder += @"\" + folder;
result.AddRange(directory.GetDirectoryFiles(metadataProperties));
}
I've made a fix by removing the last folder name added to the path using substring method.
=> Fixed the directory recursion issue - #898

Core/OfficeDevPnP.Core.Tests/AppModelExtensions/WebExtensionsTests.cs, Core/OfficeDevPnP.Core/AppModelExtensions/ListExtensions.cs, Core/OfficeDevPnP.Core/AppModelExtensions/WebExtensions.cs
Some sites in SPO no longer allow access to Web property bag, so for re-indexing we need to trigger individual lists.
Added check on NoCrawl flag for web/list as there is no need to try to trigger these.
=> Re index group point pub

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectSiteSecurity.cs
This will ensure that -IncludeSiteGroups works regardless of the web.Title value.
Should fix issue #915
=> Fix #915 check Web Title != null before tokenization

Core/OfficeDevPnP.Core/AppModelExtensions/ListExtensions.cs, Core/OfficeDevPnP.Core/AppModelExtensions/WebExtensions.cs
| Related issues?  | fixes #895 
Re-added check for new blog and video portal templates to be skipped using re-indexed on root property bag, as they seemed to have been list in the refactoring done by @jansenbe. 
Added try/catch on list re-index as some lists cannot be updated - and they should be skipped. Eg. *Forms Designer* list
=> Re index patch

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectTermGroups.cs
When adding terms that are reused but not the source a null reference exception is thrown because the CreateTerm method will return null in this scenario. there are 5 references to that method and only three has a null check implemented for the return value. I have added this check to the remaining 2 references.
=> Added missing checks for null value when creating a term.

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectWebSettings.cs, Core/OfficeDevPnP.Core/Utilities/UrlUtility.cs
I experienced an Exception when I tried to persist a web that referred _layouts-paths in the SiteLogoUrl and AlternateCssUrl properties. 
I extended the ObjectWebSettings.PersistFile() to skip URLs referring IIS Virtual Directories.
=> Fix: Web.SiteLogoUrl refering to _layouts page causes Exception when using GetProvisioningTemplate()

Core/OfficeDevPnP.Core/AppModelExtensions/TenantExtensions.cs
| Related issues?  | #930
Fix for a bug in the new TimeOut-feature for long running operations in TenantExtensions. The WaitForIsComplete-function should return false, when timed out.
Discussion about this feature and bug can be found here:
https://github.com/SharePoint/PnP-Sites-Core/pull/940#issuecomment-270871238
=> Bugfix: WaitForIsComplete should return false when timed out

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs
I created a template from a migrated SharePoint 2010 site collection. I found that the template contained some field references to automatic fields that caused errors during provisioning.
I seems like old site collections can use different names for some out of the box fields. 
As a quick fix I added the names that were in my site collection to the code. In the long run we should use the Field.ID property to identify those fields by their Guid.
=> Template creation: Add some automatic fields that don't need to be referenced

Core/OfficeDevPnP.Core/Framework/TimerJobs/TimerJob.cs
| Related issues?  | Issue 936
The timerjob class is fixed to not use static variables which gives problems when using multiple timerjobs in a single windows service or console application
=> Replaces static for normal variables for Timerjob #936

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectField.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs
| Related issues?  | fixes #849 
Possible workaround to issue #849. As described in the issue, this is not a problem with PnP Core. Problem is because the Field definition contains the Internal name of the field in the Validation Formula:
```xml
<Field Type="Text" Title="Validate Formula" DisplayName="Validate Formula" Required="FALSE" ID="{41e93963-b9c4-4f33-a8c4-8f1adbb4d40e}" SourceID="{{listid:PnP Issue 849}}" StaticName="Validate_x0020_Formula" Name="Validate_x0020_Formula" ColName="nvarchar3" RowOrdinal="0" Version="3" EnforceUniqueValues="FALSE" Indexed="FALSE" MaxLength="255">
<Validation Message="Text must contain …
```
=> Possible workaround to fix issue #849

Core/OfficeDevPnP.Core/Framework/Provisioning/Model/Field.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectLookupFields.cs
| Bug fix?        | Yes
| New feature?    | No
| New sample?      | No
The WillProvision method for ObjectLookupField was always returning true.  This would in turn always call ProvisionObjects and this would always execute queries against SharePoint before determining if the template had elements applicable to provisioning Lookup Fields.  This change fixes the performance *bug*.
1. Changes WillProvision to only return true if the template has lookup fields in SiteFields or in Lists.
2. Creates a helper property in Field to avoid multiple parsing of SchemaXml (used by WillProvision and ProvisionObjects).  This property returns the parsed XElement from the SchemaXml string and will be re-parsed whenever the underlying …
=> Implement *smart* WillProvision for ObjectLookupField

Core/OfficeDevPnP.Core.sln, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectSiteSecurity.cs
| Related issues?  | fixes #806 and #167 
When using unique permissions in a subsite any new groups listed in the pnp:security were not added, any missing role definitions would trip up the engine causing a failure. Added code to generate a warning in the log & removed the check for subsite (as mentioned in the same function at the top by Paolo Pialorsi)
=> Allow manage permissions on subsite

Core/OfficeDevPnP.Core.Tests/AppModelExtensions/TaxonomyExtensionsTests.cs, Core/OfficeDevPnP.Core/AppModelExtensions/TaxonomyExtensions.cs
If term had a comma and no quotes, it would split into parent/child term on import
If you have a term with a comma in it, it will be exported as:
`Group|Set|TermX,TermY`
On import this would import **TermX** as parent and **TermY** as child instead of **TermX,TermY**. By adding quotes around it it works as expected.
`Group|Set|"TermX,TermY"`
Also added a test for terms with quotes. Edge case where a term has quotes around it as the label is not handle and currently not supported, as the import will then strip away the quotes.
=> Added handling of terms with a comma.

Core/OfficeDevPnP.Core/Resources/SP-Responsive-UI.js, Core/OfficeDevPnP.Core/Resources/SP-Responsive-UI_CSS.css
|  Q              | A
| New sample?     | no
| Related issues? | [#45 PnP Tool](https://github.com/SharePoint/PnP-Tools/issues/45)
> I previously submitted a first PR ([#902](https://github.com/SharePoint/PnP-Sites-Core/pull/902)), but I clumsily deleted the fork. In this PR you'll find the ressources of the first one as well as some improvements.
This PR uses the concept of PnP Guidance, resolves some HTML troubles and speed improvement :
- Change PnP Responsive script structure in accordance with PnP Guidance Embedding JavaScript SharePoint (MDS Support)
- Remove the JQuery dependency (Full JavaScipt DOM)
- Speed improvement
- Fix IDs doublons caused by cloneNode JavaScript element
- Hide "EDIT LINK" from cloned Top …
=> PnP Responsive UI improvements and suite bar feature

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs
If you add localized site columns directly to a list, they will show as the default language on the list itself. In order to fix this you need to set the **DisplayName** property of the **pnp:FieldRef**. This did not have a handler for localization, which has now been added.
Without this PR the label would the token instead of the resource.
Sample template.
```xml
<pnp:ListInstance Title="{resource:ExternalSharedDocumentsTitle}" TemplateType="101" Url="External Shared Documents" EnableVersioning="true" MinorVersionLimit="0" MaxVersionLimit="0" DraftVersionVisibility="0" OnQuickLaunch="true">
<pnp:FieldRefs>
<pnp:FieldRef ID="a063ae0e-a815-41cb-a356-06fe2622259b" Name="{parameter:GenericFieldsPrefix}Country" …
```
=> Added localization of list field refs

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectContentType.cs
Fixes exception when provisioning with early versions of Microsoft.SharePoint.Client.Runtime.dll (e.g. with 15.0.4561.1000 the one in PnP-Site-Core repo), where ClientQueryable.GetEnumerator method is not implemented.
=> ClientQueryable.GetEnumerator not implemented fix

Core/OfficeDevPnP.Core/AppModelExtensions/FileFolderExtensions.cs
Fix for when using SaveFileToLocal with a callback function and destination file doesn't exist on FileSystem, doSave stays false and file don't get saved. (Second commit is just code clean up).
=> Save file fix

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectTermGroups.cs
If description for TermGroup, TermSet or Term contains a resource token, it must be parsed before it is applied.
=> Added parsing of description resource to TermGroup, TermSet and Term.

Core/OfficeDevPnP.Core/BuiltInContentTypeId.cs
Added built in content types for Publishing, so that they don't get exported when Publishing is enabled on a Team Site.
=> Added built in content type ids used in the publishing infrastructure.

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectTermGroups.cs
Only add labels to a term, if the label language is an available termstore language.
=> Only add labels to a term for available termstore languages

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectContentType.cs
| Bug fix?    |  yes
| Related issues?  | not found
Updated the content type object handler to reorder the content type field after adding new fields to the content type. Re-order was called too early so new fields added to the content type always ended up at the bottom. Reduced to one re-order call.
=> Re-order fields when content type is updated

Core/OfficeDevPnP.Core/AppModelExtensions/WebExtensions.cs, Core/OfficeDevPnP.Core/Entities/SiteEntity.cs
| New feature?    | no [Performance improvement]
| New sample?      | Yes [Change to existing sample]
| Related issues?  | Fixes the severe performance issue with using "StartRow" property for paging the search results
Search Product Group has recently found severe performance issue with using "StartRow" property of "KeywordQuery" class for paging the search results. The recommendation is to use the "IndexDocId" property to get the subsequent results after sorting the results from first query based on IndexDocId. 
This pull request contains changes to "SiteSearch" method and "ProcessQuery" method in OfficeDevPnP.Core\AppModelExtensions\WebExtensions.cs to implement paging based on "IndexDocId" instead of using StartRow. …
=> Siteretrieval via search by index doc

Core/OfficeDevPnP.Core/Extensions/TaxonomyExtensions.cs
Fix for TaxonomyExtensions.SetTaxonomyFieldDefaultValue does not an option for pushing changes to the list, so updating site column's default value does not propagate change to lists. Having such option is extremely useful in many scenarios.
=> fix for SetTaxonomyFieldDefaultValue not pushing changes to lists

Core/OfficeDevPnP.Core/Framework/Graph/UnifiedGroupsUtility.cs
Handle if Site is not ready on GetUnifiedGroup
| Improvement?    | yes
Added option to exclude drive loading. This makes the call quicker if the URL is not needed. And also speeds up the *remove-pnpunifiedgroup* cmdlet if it can avoid loading the drive before deleting the group.
=> Added option to exclude drive on GetUnifiedGroup call.

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/TokenParser.cs
| Bug fix?        |yes
| Related issues?  | fixes #1045 
Following @jansenbe instructions. This is a Fix to #1045: Removed token match from regular expression on GetLeftOverTokens (see comments on Bug detail).
=> Fix to #1045: Removed token match from regular expression on GetLeftOverTokens

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectNavigation.cs
Inheritance of current navigation does not work. The reason is, that WebNavigationSettings.Update() was not called to apply the configuration. Interestingly this had no impact on the other navigation options.
To reproduce apply the following template to a subsite.
`<?xml version="1.0"?>
<pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2016/05/ProvisioningSchema">
<pnp:Preferences Generator="OfficeDevPnP.Core, Version=2.9.1611.0, Culture=neutral, PublicKeyToken=d8f0f7d8ea55cb0a" />
<pnp:Templates ID="CONTAINER-TEMPLATE-DD6D590BBF6D4D31A19021D8512C86C6">
<pnp:ProvisioningTemplate ID="TEMPLATE-DD6D590BBF6D4D31A19021D8512C86C6" Version="1"> …
=> Fix CurrentNavigation inheritance

Core/OfficeDevPnP.Core/Utilities/CredentialManager.cs
here is public static method GetSharePointOnlineCredential  in the CredentiaManager (the first method from the top of the class ). It seems to be  not used inside of Library, but I allowed it to use. In case there is problem with credentials it crashes with NullReferenceException) 
Seeing   GetSharePointOnlineCredential  using  GetCredential method, which returns null  in case of no success, I allowed to ask for this simple pull request , where the GetSharePointOnlineCredential  similarly returns null in case of no success.
=> small fix of  NullReferenceException in CredentiaManager.GetSharePointOnlineCredential

Core/OfficeDevPnP.Core.Tests/App.config.sample, Core/OfficeDevPnP.Core.Tests/Extensions/ListExtensionsTests.cs, Core/OfficeDevPnP.Core.Tests/TestCommon.cs, Core/OfficeDevPnP.Core/Entities/WebhookSubscription.cs, Core/OfficeDevPnP.Core/Extensions/ListExtensions.cs, Core/OfficeDevPnP.Core/OfficeDevPnP.Core.csproj, Core/OfficeDevPnP.Core/Utilities/Utility.cs, Core/OfficeDevPnP.Core/Utilities/Webhooks/ResponseModel.cs, Core/OfficeDevPnP.Core/Utilities/Webhooks/WebhookUtility.cs
List Extension methods to manage List Webhooks subscriptions and all the underlying utilities + related unit tests
=> Add List Extensions methods to manage Webhooks subscriptions

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs
This PR fixes an issue where a site column on a list isn't extracted when the field on the list contains a different DefaultValue than the site column.
=> Fields with DefaultValue not extracted

Core/OfficeDevPnP.Core.Tests/Framework/ObjectHandlers/ObjectListInstanceTests.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs
| New feature?    | yes 
This change will allow the removal of the default content types from an asset list, if there are custom content types defined for this list. Before this change this was possible for a lot of OOTB lists, but not for the asset list.
=> Allow removal of default content types from an asset list.

Core/OfficeDevPnP.Core/CoreResources.Designer.cs, Core/OfficeDevPnP.Core/CoreResources.resx, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectField.cs
This change fixes an issue where updating and pushing changes for a field, will result in a timeout exception if the field is a site column and the site column is used on many subsites and lists.
=> Catch timeout exception when updating and pushing changes for a site column

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/TokenParser.cs
When having empty parameter values in a provisioning template I get an exception from the TokenParser class as the empty value get translated to a null value and gives an error in the `regex.Replace` call. Converting null value to empty string at creation solves the issue.
=> Null exception in TokenParser class when having empty parameter in provisioning template

Core/OfficeDevPnP.Core/Extensions/FileFolderExtensions.cs
When treating files its a bit dangerous to assume all files live in lists. One example of this is when modifying existing forms pages, e.g. adding webparts to these. For us this is a pretty common scenario, we often add a content editor webpart or script editor webpart to forms pages so we can modify OOB functionaltity without creating custom Forms pages.
In order to support adding webparts to pages which are NOT normal files, we have to do a null check on listitemallfields whenever we use that.
=> Support modifying Forms pages by null-checking ListItemAllfields

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectContentType.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ProvisioningTemplateCreationInformation.cs
| Related issues?  | fixes #1208
When a content type is provisioned through content type syndication, it's flagged as *read-only* in the site collection.
This leads to provisioning error because the PNP provisioning engine try to create the content type, which is already here because of the ct syndication.
My solution was simply to check if the content type is syndicated or not, to avoid exporting the content type.
A flag has also been added to the `ProvisioningTemplateCreationInformation` to reenable exporting this kind of content types.
Hope that helps
=> #1208: filter content types that come with content type syndication

Core/OfficeDevPnP.Core.Tests/App.config.sample, Core/OfficeDevPnP.Core.Tests/Extensions/ListExtensionsTests.cs, Core/OfficeDevPnP.Core/Extensions/ListExtensions.cs, Core/OfficeDevPnP.Core/Utilities/Webhooks/WebhookUtility.cs
- Bug fix : Ensure List Id is loaded when needed
- Pre-check of expiration date validity
- Add a valid delta when validity period is 6 months exactly
- better handling of exception in WebhooksUtility methods
=> Improvements and small bug fix in List Webhooks extension methods

Core/OfficeDevPnP.Core/Extensions/WebExtensions.cs
"dubplicates" -> "duplicates" for one of SiteSearch() methods.
Correcting misspelling of "dublicates" to "duplicates" in SiteSearch() method.
=> Correct misspelling of "duplicates" in SiteSearch() method

Core/OfficeDevPnP.Core/Framework/TimerJobs/TimerJob.cs
missed one exception in d3a6d77bdd1a4d985ad00481f9b0350e1caa53ee :)
| Related issues?  |
=> Use nameof instead of literal parameter name

Core/OfficeDevPnP.Core/Extensions/PageExtensions.cs
If you provide a path to a WikiPage, that contains a folder in the library, the Provisioning will fail.
e.g: /sitepages/SubFolderA/somePage.aspx
This change will ensure that the target folder (SubFolderA) is created, before the Wiki Page is uploaded.
=> New Feature: Provision WikiPages into SubFolders of a Library

Core/OfficeDevPnP.Core/Framework/Provisioning/Connectors/AzureStorageConnector.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/Connectors/FileSystemConnector.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/Connectors/OpenXMLConnector.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/Connectors/SharePointConnector.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectContentHandlerBase.cs
If a FileConnector with a Container is set to eg. /Templates/SubFolder and PersistBrandingFiles is True,
the FileConnector container is replaced when persisting a page in the PageContents Objecthandler.
Let's say that the SiteAssets/default.aspx page should be persisted.
Then the Container will be /SiteAssets instead of  /Templates/SubFolder/SiteAssets which will in my case result in a bad server request as I'm using the AzureStorageConnector.
This change will check for an already set Container and concatenate it.
=> Fixed issue where PersistFile is replacing already set Container

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs
| Related issues?  | fixes #1152, affects #1116 
Fixes the problem that the engine is trying to set MajorVersionlimit on SharePoint 2013. Problem is, that this property is not exposed at the API of SharePoint 2013. To be consistent with the other parts of ObjectListInstance, the property will be ignored on SharePoint 2013.
Resubmitting #1291 to DevBranch as discussed with @VesaJuvonen
=> Do not set  VersionLimits on SP2013

Core/OfficeDevPnP.Core.Tests/Framework/ObjectHandlers/ObjectSiteSecurityTests.cs, Core/OfficeDevPnP.Core.Tests/Framework/ObjectHandlers/TokenParserTests.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectSiteSecurity.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/TokenDefinitions/RoleDefinitionIdToken.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/TokenParser.cs, Core/OfficeDevPnP.Core/OfficeDevPnP.Core.csproj
| Related issues?  | /
Added a new token '{roledefinitionid:name_of_roledefinition}'
i.e.
{roledefinitionid:Read} will return the id of the roledefinition.
I use it to replace the value in a workflow I created so I spare the need to call REST-service to get this data each time the WF is running.
Unit tests have been extended to test the new token.
=> Add new tokendefinition (RoleDefinitionId) incl. UTs

Core/OfficeDevPnP.Core.Tests/Framework/ObjectHandlers/ObjectListInstanceTests.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs
This PR changed provisioning engine so that tokens (e.g. {parameter:aaaa}) can be used in ListInstance -> Description attribute.
=> Enable token use in ListInstance.Description

Core/OfficeDevPnP.Core/Resources/SP-Responsive-UI.js
| Related issues?  | fixes #1272
A fix for #1272 by changing how we set the width of the 's4-bodyContainer' element in the 'FixRibbonAndWorkspaceDimensions' function.
=> Fix for the Responsive UI when going to mobile view and back to desktop view

Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/Serializers/PagesSerializer.cs
| Related issues?  | fixes #869
`LimitedWebPartManager.AddWebPart` method from the CSOM library requires to provide WebPart definition wrapped within a `<webParts>` node.
The custom serialization reads the `pnp:webPart/pnp:Contents/webParts` **InnerXml** value, which is actually the `<webPart>` node.
This leads to the namespace error mentioned in the issue.
Changing the serializer code to use **OuterXml** resolves the issue.
This also allow the usage of DWP webparts.
Hope that helped
=> Fix webpart importation

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/Extensions/UserResourceExtensions.cs
| Bug fix?        | Yes
In UserResourceExtensions.SaveResourceValues you'll get and InvalidOperationException: "Collection was modified; enumeration operation may not execute." if a token is added to the ResourceTokens list.
=> Fix InvalidOperationException

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectTermGroups.cs
| Related issues?  | #1137
As described in issue #1137 child terms are not added if the parent term already exist.
This change will check if the child terms exist and create them if the doesn't exist.
=> Support incremental addition of child terms

Core/OfficeDevPnP.Core/Pages/ClientSidePageControls.cs, Core/OfficeDevPnP.Core/Pages/ClientSidePagesControlData.cs
When exporting a client page as a template with a custom web part I noticed I got a `controlIndex` of 0.5. Changed from int to float to allow this.
=> Changed control index to float

Core/OfficeDevPnP.Core/WebAPI/WebAPIHelper.cs
Fixes the condition to refresh the access token in the WebAPI Helper
The Token was refreshed only after expiration+ one hour
=> Refresh Token bug fix in WebAPI Helper

Core/OfficeDevPnP.Core.Tests/Framework/Providers/XMLProvidersTests.cs, Core/OfficeDevPnP.Core.Tests/Resources/Templates/ProvisioningTemplate-2016-05-Sample-03-OUT-ct.xml, Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/Resolvers/NavigationFromSchemaToModelTypeResolver.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/Serializers/PagesSerializer.cs
Fixes for Navigation and Pages XML serializers.
Navigation serializer throw NullReference when only one of two navigation is specified (e.g. only Global)
Pages serializer does not deserialize WebParts correctly for latest schema resulting in web part contents loss.
Also updated teasts.
=> Navigation and page serializers fixes + tests

Core/OfficeDevPnP.Core/Sites/SiteCollection.cs, Core/OfficeDevPnP.Core/Sites/SiteCollectionCreationInformation.cs
By default, the SharePoint Online UI creates a Public Office 365 Group. The extension method should do the same thing, for consistency, IMHO.
=> Fix to align extension method behavior with the SharePoint UI default behavior

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectFiles.cs
Support token replacement in the filename. Useful if you based on some external parameter want to upload a different file to a specific file name. All files could be stored in the package, but only one will be uploaded.
=> Support token replacement in the file name

Core/OfficeDevPnP.Core/IdentityModel/TokenProviders/ADFS/UsernameMixed.cs
| Related issues?  | fixes #1455
Fixed UsernameMixed.GetFedAuthCookie() to work if cookie-lifetime is in days (like 1.00:00:00, without hours and minutes) #1455
=> Fixed cookieLifeTime in UsernameMixed() to use lifeTime.TotalMinutes

Core/OfficeDevPnP.Core/Extensions/PageExtensions.cs
| Related issues?  | fixes #1452 
This PR fix #1452.
After delving into the code, I noticed that the engine builds an url like this to get the XML:
`http://server:80/sites/somepublishingsite/_vti_bin/exportwp.aspx?pageurl=http://server:80/sites/somepublishingsite/Pages/default.aspx&guidstring=df28b8a4-cad2-4652-97f1-5d57d8010232`
Precisely:
` var request = (HttpWebRequest)WebRequest.Create($"{webUrl}/_vti_bin/exportwp.aspx?pageurl={pageUrl}&guidstring={id}");`
The pageURl argument is passed as is.
Adding an Url encoding solved the issue:
`var request = (HttpWebRequest)WebRequest.Create($"{webUrl}/_vti_bin/exportwp.aspx?pageurl={HttpUtility.UrlKeyValueEncode(pageUrl)}&guids …
=> Added pageUrl argument encoding

Core/OfficeDevPnP.Core.Tests/Framework/Connectors/ConnectorAzureTests.cs, Core/OfficeDevPnP.Core.Tests/Framework/Connectors/ConnectorFileSystemTests.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/Connectors/AzureStorageConnector.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/Connectors/FileSystemConnector.cs
| Related issues?  | fixes #357
This PR adds support for both backward (```\```) and forward slashes (```/```) as path delimiters for Provisioning Engine's ```FileSystemConnector``` and ```AzureStorageConnector``` thus making it possible to use same provisioning templates across all different connectors.
The support for both delimiters was already implemented for the ```SharePointConnector``` and ```OpenXMLConnector```, so now all of the connectors should be able to use both '\' and '/' as the path separator.
The supprort for the ```SharePointConnector``` was added in PR #807 in 10/2016 and this current PR is implemented using similar approach.
=> Fix for #357: Support both forward and backward slashes in AzureStorage- and FileSystemConnectors

Core/OfficeDevPnP.Core/Entities/UnifiedGroupUser.cs, Core/OfficeDevPnP.Core/Framework/Graph/UnifiedGroupsUtility.cs, Core/OfficeDevPnP.Core/OfficeDevPnP.Core.csproj
| Bug fix?        | 
| New sample?      | 
| Related issues?  |
New functionality to retrieve Owners and Members of a particular Unified group.
Currently there is no functionality in PnP-Sites-Core Graph utility to retrieve Owners and Members of a particular Unified group. This can be useful in creating new commands in PnP-Powershell to fetch members and owners. The changes consists of following
- Methods GetUnifiedGroupMembers, GetUnifiedGroupOwners and a helper method GenerateGraphUserCollection(to reduce repeatitive code) added to UnifiedGroupsUtiity class. 
- New entity UnifiedGroupUser added with the properties User principal name and display name. This entity represents a user in a Unified group.
=> Get Owners and Members of a Unified Group.

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs
| Related issues?  | partially #1353 and #1457 
This PR partially fixes local field regression.
Here is the status of what's working or not (in scenarios where PnP engine is use to "clone" site, by exporting the template and applying it):
[X] List with content types not enabled are cloned properly (site fields and local fields)
[ ] List with content types enabled : 
[X] site fields referenced in the site content types are cloned properly
[ ] all list local fields are cloned, but are not bound to content types
[ ] all site fields are cloned, but are not bound to content types if the reference is in the list content type
I choose to still submit the PR as it solve the …
=> Partial fix of issue #1353 related to local fields

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectImageRenditions.cs
…me name, width & height)
Define a template with an Image Rendition, and provision it twice for the same site : the rendition will be present 2 times. This is because of the "Contains" test that is not relevant for this kind of object. I'm using a LINQ query to test if there is an existing image rendition (same name, width & height) in order to avoid provisionning multiple times the same image rendition.
=> Avoid duplicate image renditions if provisioned multiple times

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectCustomActions.cs
This PR includes code to use the TokenParser on CustomAction.RegistrationId, as it makes sense to resolve tokens there (as List ID, specially useful for registering spfx extensions, as RegistrationType=ContenType is not yet supported, so we need to specify a ListID if we want to use the extension with a specific List).
=> Using TokenParser on CustomAction.RegistrationId

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstanceDataRows.cs
| Bug fix?        | X
https://github.com/SharePoint/PnP-Provisioning-Schema/issues/259
https://github.com/SharePoint/PnP-Provisioning-Schema/issues/236
This pull request contains a fix for the data rows xml element. When defining the key column and update behaviour a new list item is always created.
The problem is that we're looking at the wrong key when iterating through each data row and verifying if dataRow.Key is null (which will always be null). In order to get the right value we need to look at the values inside the dataRow.Values and get the value where key == listInstance.DataRows.KeyColumn.
Example:
If we're updating items based on the column 'Title', we will have to iterate through each data row, get its values …
=> Fixing data rows key column and overwrite behaviour

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs
| Related issues?  | fixes #1090 
Added support for custom js link configuration. Currently, when we export a template, if the list view has custom jslink, then its not getting exported. It only shows the clienttemplates.js file in the JSLink node. This code fixes that issue.
=> Added support for custom js link configuration

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs
Fixed to set ListViewXml to the inner xml of our view schema so that any additional attributes on FieldRefs that aren't directly settable through CSOM are properly set.
Currently, if you have a view fieldref like the following, the attributes aren't preserved on the view when provisioned:
`
<FieldRef Name="Role" listItemMenu="TRUE" linkToItem="TRUE" />
`
The easy fix for this is to set the ListViewXml property of the view to the inner XML of the view schema right after creating it. This will properly set the above attributes, allowing the user to specify that a field other than Title should be used as a link to open the list item and/or to display the …
=> Fix to preserve attributes on view fieldrefs

Core/OfficeDevPnP.Core/Extensions/ClientContextExtensions.cs, Core/OfficeDevPnP.Core/OfficeDevPnP.Core.csproj, Core/OfficeDevPnP.Core/packages.config
Fix to decode a JWT token with System.IdentityModel.Tokens.Jwt v.4.0.0 instead of v.5.1.5
=> Fix to decode a JWT token with System.IdentityModel.Tokens.Jwt v.4.0.0 instead of v.5.1.5

Core/OfficeDevPnP.Core/Extensions/ListExtensions.cs
Added extension method on Web to retrieve a list by its Id. This is useful for example in handling webhook notifications in which the webhook notification payload contains a list's Id
=> Updated ListExtensions: GetListById extension method added

Core/OfficeDevPnP.Core/Extensions/FileFolderExtensions.cs
Fixed to avoid trying to access file.ListItemAllFields when the file isn't associated with a list item, causing a later, spurious 'The object specified does not belong to a list' error the next time the context is executed.
| Related issues?  | partially fixes #1340 
This code was accessing file.ListItemAllFields to check if it's a normal file or non-list-based file, but was doing so even if the call to file.EnsureProperty(f => f.ListItemAllFields) threw an exception (indicating the file's not associated with a list). Doing so throws the retrieval back in the context, and the next time that ExecuteQueryRetry is called (which could end up being in an entirely …
=> Fix errors when publishing non-list-based files.

Core/README.md
Two Additional documentation links were missing escape characters for spaces. Corrected links to SAML support and Timer job framework.
=> Corrected links for additional documentation

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectSiteSecurity.cs
| Related issues?  |  partially #1516
These changes fix the performance issues described in #1516. 
The problem is related to the method call "TokenParser.ParseString()" in the FirstOrDefault-Method.
The more groups you have the slower the FirstOrDefault-Method is.
By parsing first and using the parsed value in the FirstOrDefault-Method it's getting much faster.
=> Fix performance issues

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs
While provisioning a new user custom action, the ClientSideComponentId and ClientSideProperties are not set.
| New sample?      | yes
| Related issues?  | fixes #1542 
While extracting User Custom actions, populated the ClientSideComponentId and ClientSideProperties.
While provisioning a new List User custom action, setting these properties.
=> Populating List User custom action properties (ClientSideComponentId and ClientSideProperties)

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectTermGroups.cs
Handle the term Owner and Description fields in provisioning template extract
=> Include Term Descripition and owner in the TermGroup provisioning template extract

Core/OfficeDevPnP.Core/Extensions/FileFolderExtensions.cs
| Related issues?  | Solves this issue - https://github.com/SharePoint/PnP-Sites-Core/issues/1161
- Updates illegal characters set for SharePoint Online according to current limitations . For on-premises I used this article https://support.microsoft.com/lo-la/help/905231/information-about-the-characters-that-you-cannot-use-in-site-names--fo
- Applies new char set for folder creating, checking and file upload methods
=> Illegal chars set for folders and files

Core/OfficeDevPnP.Core/Extensions/TaxonomyExtensions.cs
| Related issues?  |
This PR fix taxonomy helper when the store has not english language defined. Instead, the code should use the default store's language.
=> Fix TaxonomyExtensions to work with other languages than English

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstanceDataRows.cs
| Related issues?  | fixes #1586 
Calling listItem.update() per field value causes an exception when creating an Event item via a template. Moving this out and calling it once per item resolves this issue, although this could have side effects.
=> Fix Event item provisioning

Core/OfficeDevPnP.Core/Utilities/WebParts/Processors/XsltWebPartPostProcessor.cs
| Related issues?  | fixes #1670
Fetching a view where the displayNameAttribute value is empty should not be be allowed. This returns the default view as illustrated in the image below:
Fixed this by checking if the value of the displayNameAttribute is not empty
```csharp
!string.IsNullOrEmpty(displayNameAttribute?.Value)
```
=> Fix issue #1670: wrong view provisioned on webpart

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectField.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ProvisioningTemplateApplyingInformation.cs
Fields can now be provisioned to sub sites. This is similar to how content types are provisioned to sub sites.
I have not implemented or tested support for extracting fields from sub sites, but this is not needed for provisioning. A simple example could be provisioning to add-in webs. [PR 1478](https://github.com/SharePoint/PnP-PowerShell/pull/1478) has also been created in the PowerShell repository to add support for this when extracting provisioning template.
=> Add option for provisioning fields in sub webs.

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs
| Related issues?  | fixes #1390
Added ability to update URL of list if modified while provisioning. The way this works is by modifying the folder name of the list in SharePoint.
=> List URL is updated on provisioning.

Core/OfficeDevPnP.Core/Entities/UnifiedGroupEntity.cs, Core/OfficeDevPnP.Core/Framework/Graph/UnifiedGroupsUtility.cs
Added support to retrieve "classification" of a unified group. Updated the UnifiedGroupsEntity to add a new property and updated **GetUnifiedGroup** and **ListUnifiedGroups** methods with optional parameter to include site classification.
This will also help easily access group classification value in PnP Powershell and extract site classification reports with PnP Powershell scripts.
Classification property extraction needs a separate call at the moment since we use old graph client. When the Graph client is updated, the property is accessible on the unified group object,
=> Added support to retrieve Unified group classification

Core/OfficeDevPnP.Core/Extensions/FileFolderExtensions.cs
With the introduction of ResourcePath API, file and folder names containing `%` and `#` characters are supported in SharePoint Online.
This PR makes use of that API for various methods in the FileFolderExtensions to fetch files and folders which may contain these special characters. It will work with normal characters as well.
=> Feature - added support for ResourcePath API in FileFolderExtensions

Core/OfficeDevPnP.Core/Pages/ClientSidePage.cs
Just a small fix...
One more missing SynchronizationContextRemover coming into play when calling Page.AvailableClientSideComponents(). Before it was leading to a deadlock again when calling this method from an application with UI Thread (e.g. MVC)
=> Fix async handling calling ClientSidePage.AvailableClientSideComponents()

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectCustomActions.cs
If a CustomAction is updated with a new ClientSideComponentId and ClientSideComponentProperties, the properties are not set when the provisioning template is applied.
=> CustomAction ClientSideComponentId and ClientSideComponentProperties not updated

CHANGELOG.md, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/SiteToTemplateConversion.cs
Fix so that list instances created from list definitions (stp) files get's created correct. When a FeatureId is present we need to check the template and set `ListTemplate` instead of `TemplateType`.
Sample template
```xml
<?xml version="1.0"?>
<pnp:Provisioning 
xmlns:pnp="http://schemas.dev.office.com/PnP/2018/05/ProvisioningSchema">
<pnp:Preferences Generator="OfficeDevPnP.Core, Version=2.27.1806.0, Culture=neutral, PublicKeyToken=null" />
<pnp:Templates ID="CONTAINER-TEMPLATE-B417026045BA442685C3AB4351F0BF21">
<pnp:ProvisioningTemplate ID="TEMPLATE-B417026045BA442685C3AB4351F0BF21" Version="1" BaseSiteTemplate="STS#0" Scope="RootSite">
<pnp:Lists>
<pnp:ListInstance Title="PnP" TemplateType="100" Url="Lists/PnP" …
```
=> Fix to support creating list from a list definition (stp)

Core/OfficeDevPnP.Core/Framework/Provisioning/Model/CanvasControl.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/Utilities/ClientSidePageContentsHelper.cs
- Set Title when extracting ClientSidePage
When a ClientSidePage is extracted using ClientSidePageContentsHelper.ExtractClientSidePage the Title is not set on the extracted ClientSidePage model.
- Fix NullReference exception when applying extracted Client Side Page
If CanvasControl.ControlProperties is null, provisioning of an extracted Client Side Page will fail.
=> ExtractClientSidePage fixes

Core/OfficeDevPnP.Core.Tests/Framework/ObjectHandlers/ObjectSiteSecurityTests.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectSiteSecurity.cs, Core/OfficeDevPnP.Core/OfficeDevPnP.Core.csproj, Core/OfficeDevPnP.Core/Utilities/PnPHttpUtility.cs
Fix incorrect update of site group description during provisioning. 
There are two places that holds the description for a group:
1. The group object Description property
2. The Note field for the group entry in the User Information List (UIL)
SharePoint UI uses the content in the Note Field from UIL to render the group description text in the UI.
It's therefore critical that the UIL is always updated with any group description changes.
Previously only the site group description would be set if the description was plain text. The entry in UIL was not set.
If the group was created with a rich text description both the group description and the UIL entry …
=> Fix group description update during site security provisioning

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectNavigation.cs
The UseShared property of web.Navigation wasn't being properly set to false when applying structural or managed navigation to a subsite, resulting in the error 'The top link bar can only be edited for a Web site with unique navigation' if the subsite's global nav was currently set to Inherit. Fixed to set to false before applying structural or managed navigation.
=> Fixed applying structural navigation to subsite

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectNavigation.cs
| Related issues?  | fixes #985 
The PnP provisioning template fails whenever we add a SharePoint url which is non-existent.
The trick here is to provision it as external url which will bypass the server-side validation.
This is also how,  i believe , SharePoint internally works because whenever we add SP relative url which is non-existent it is allowed via the UI.
This fixes a long pending issue which is present even in the latest PnP code.
To repro it, you can use the below minimal template:
```
<?xml version="1.0"?>
<pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2018/05/ProvisioningSchema">
<pnp:Preferences Generator="OfficeDevPnP.Core, …
```
=> Fix - template failure for non-existing links in quick launch or top nav

Core/OfficeDevPnP.Core/Pages/ClientSidePageHeaderType.cs
The Enum OfficeDevPnP.Core.Framework.Provisioning.Model.ClientSidePageHeaderType is not consistent with OfficeDevPnP.Core.Pages.ClientSidePageHeaderType
This means that when extracting a ClientSidePage and applying it again the HeaderType is changed.
Eg.
Default is changed to None
None is changed to Default
I've modified Pages.ClientSidePageHeaderType
from
```
public enum ClientSidePageHeaderType
{
Default = 0,
None = 1,
Custom = 2
}
```
to
```
public enum ClientSidePageHeaderType
{
None = 0,
Default = 1,
Custom = 2
}
```
=> Fixed ClientSidePageHeaderType enum inconsistency

Core/OfficeDevPnP.Core/Extensions/TaxonomyExtensions.cs
| Related issues?  | fixes #1669 
Incorrect exception is thrown while trying to update a multi-valued taxonomy field if that field itself is single valued. The code moves from the `if(taxField.AllowMultipleValues)` to the `else` block, this error is thrown
The exception is incorrect because we are not initializing the `StaticName` property.
To reproduce this issue, try to update a single valued taxonomy field and use the `SetTaxonomyFieldValues` method.
=> Fix - incorrect exception thrown while setting multi-valued tax field

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectFiles.cs
If we use a directory element in combination with MetadataMappingFile we currently have to create metadata mappings for _all_ files in the directory. This removes most of the benefit of using the Directory element. This fix allows us to specify metadata for some files, but any file in the directory will be uploaded to the target library regardless
cc: @wobba
=> Allow us to describe metadata for some, but not all files in a directory

Core/OfficeDevPnP.Core/Pages/ClientSidePageHeader.cs
When parsing the Client Side Page header Html, some properties might not exist within the html (eg. siteId, webId), which will result in a NullReferenceException.
I've added null check for the properties.
=> Fix NullReferenceException when parsing client side page header html

CHANGELOG.md, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/FieldAndListProvisioningStepHelper.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectContentType.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectField.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/TokenDefinitions/TokenDefinition.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/TokenParser.cs
| Related issues?  | fixes https://github.com/SharePoint/PnP-PowerShell/issues/1678
Instead of looping over all tokens, which can get up to 5000+ in large templates, and matching on each part of a template fragment, we instead pick the tokens from the template fragment, and find replacement values from a token dictionary.
This greatly improved CPU usage and over all provision speed on large templates in particular.
Code also breaks up two linq statements to to reduce parsing of xml and unneeded parsing of template fragements for tokens.
=> Optimize provisioning speed of fields and content types

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs
| Related issues?  | fixes #1884
This pull request fixes #1884 by parsing the tokens in the full xmlschema of the view when creating a new view. Tokens used within the View SchemaXML will now be parsed.
=> Parse tokens in the complete SchemaXML

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/TokenDefinitions/AssociatedGroupToken.cs
| Related issues?  | fixes #1905 
This PR fixes the `Object reference not set to instance of an object on server` error method.
This error occurs when there is no default associated visitor, member or owner group of a site.
To reproduce it, create a subsite with unique permissions. After that delete the visitor group and apply the template. It fails. So added a null check to determine whether the group exists or not.
Also, kinda improved the performance by sending minimal payload for each request. Currently, it fetches data for all groups in each iteration which can be avoided.
cc @wobba - can you please review this ? Please let me know if you need more details ! Cheers :)
=> Fix: object reference error for sharepoint groups in GroupToken

Core/OfficeDevPnP.Core.Tests/Framework/ObjectHandlers/TokenParserTests.cs, Core/OfficeDevPnP.Core/Extensions/SecurityExtensions.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/Extensions/SecurableObjectExtensions.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectSiteSecurity.cs
| Related issues?  | fixes #1881 
As described in Issue #1881 the comparison of LoginNames should be performed case-insensitive. 
The PR contains all changes to the master branch to change the comparison logic.
=> Fix: LoginNames should be compared case insensitive

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectTermGroups.cs
| Related issues?  | fixes #1897
Analysis of the issue #1897 showed that the root cause of the ServerException being thrown is the fact that the provisioning engine tries to create a custom sort order on the HashTags TermSet which is in fact **not allowed**. 
The IF statement inside ObjectTermGroups.cs at line 245 https://github.com/SharePoint/PnP-Sites-Core/blob/c6afdf14f55004b1b1255b9c57cde1920495c5ea/Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectTermGroups.cs#L245 
compares using -1. Custom sort order in SharePoint always starts with 1 for the element which should be located at the start of the list.
=> Fix: Unable to import Taxonomy Hashtag values

Core/OfficeDevPnP.Core/Extensions/TopologicalSort.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectSiteSecurity.cs, Core/OfficeDevPnP.Core/OfficeDevPnP.Core.csproj
| Related issues?  | fixes #1901 
Analysis of the root cause for issue #1901  showed that the code currently in place for sorting SiteGroup definitions (loaded from a provisioning template) based on it's dependencies at 
https://github.com/SharePoint/PnP-Sites-Core/blob/baa63ca778ab7952fb5f6345e3cea3d1e8e4901a/Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectSiteSecurity.cs#L66
inadvertently deletes SiteGroup definitions. Form the defined 11 groups inside the provisioning template (attached to issue #1901) only **two** are created: `Website Administrator` , `Website Manager`.
The pull request contains a fix which replaces the current sorting routine with …
=> Fixed issue 1901 by using a Topological Sort while provisioning SiteGroups

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs
| Related issues?  | fixes #1858, #1907
Fixed invalid template in a rare situation when Webhook's ServerNotificationUrl is empty solving #1907.
=> Fix: Invalid template in a rare situation when Webhook's ServerNotificationUrl is empty

Core/OfficeDevPnP.Core/Extensions/InformationManagementExtensions.cs
| Related issues?  | fixes #1906
As mentioned in #1906, because of wrong negation operator, the method `SetOpenBySitePolicy` doesn't work in the InformationManagementExtension.
=> Fix: SetOpenBySitePolicy always returns false

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectClientSidePages.cs, Core/OfficeDevPnP.Core/Pages/ClientSidePage.cs, Core/OfficeDevPnP.Core/Pages/ClientSidePageHeader.cs
Added support for Resource Path API in the modern site pages. 
It fixes the issue wherein we have `#` or `%` characters in page names or image names for modern site pages.
Should I go ahead and modify it across the solution for SPO ? I saw that we are using the `GetFileByServerRelativeUrl` across multiple extensions and provisioning handlers. I will ofcourse test it before making PR, but seems like something we should use across the PnP Core package.
=> Feature: Added support for Resource Path API in modern pages

Core/OfficeDevPnP.Core/AuthenticationManager.cs, Core/OfficeDevPnP.Core/Enums/SharePointPlatform.cs, Core/OfficeDevPnP.Core/Framework/Graph/SiteClassificationUtility.cs, Core/OfficeDevPnP.Core/Framework/TimerJobs/TimerJob.cs, Core/OfficeDevPnP.Core/Utilities/CredentialManager.cs, Core/OfficeDevPnP.Core/Utilities/MailUtility.cs, Core/OfficeDevPnP.Core/Utilities/PnPCoreUtilities.cs
| Related issues?  | fixes #1956 
Removes the maximum access token lease lifetime, which was set to 60 minutes, even though access tokens can be valid (depending on the case) up to 12 hours.
Doesn't remove the logic, that sets the token to null 5 minutes before validity ends. I suspect that's there for a reason?
Also contains my earlier pull request #1952 (since I messed up branching earlier), which just has fixes for typos and adds summaries for a few classes.
=> Removes 60 minute maximum lifetime for Access Tokens in AuthenticationManager

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs
| Related issues?  | fixes #1949
The issue is caused the MaxVersionLimit and MinorVersionLimit are set to 0.
When set to 0, it is assumed that there is no limit, in that case we will set to the maximum 50000 limit that we currently view in the browser, else it will respect that value set by the user.
=> Fix: MaxVersionLimit set to 0 issue

Core/OfficeDevPnP.Core/Framework/Graph/UnifiedGroupsUtility.cs
| Related issues?  | fixes #1987 
1) With this PR, we will be able to add Owners and Members during the group provisioning process itself.
Previously, it happened after the group was provisioned which sometimes caused issues like #1987 .
2) Also, now that Teams APIs are in GA, this PR provides the capability to create a MS Teams team associated with the O365 group. It is available via `createTeam` parameter which will be false by default.
=> Feature - Enhanced UnifiedGroups provisioning

Core/OfficeDevPnP.Core.Tests/Framework/ObjectHandlers/ObjectFieldTests.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/FieldAndListProvisioningStepHelper.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectField.cs
This small PR changes token parsing to use ParseXmlString when parsing SchemaXml.
ParseString can result in invalid xml that cannot be parsed by XElement.Parse.
=> Fixed schema xml parsing

Core/OfficeDevPnP.Core.Tests/Framework/ObjectHandlers/ObjectListInstanceTests.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/Utilities/FieldUtilities.cs
If a template contains a OOTB lookup field where the target list is an internal SharePoint list, applying the template will fail with "File not found" because the target list cannot be found.
Eg.
```xml
<Field ID="{6bfaba20-36bf-44b5-a1b2-eb6346d49716}" ColName="tp_AppAuthor" RowOrdinal="0" ReadOnly="TRUE" Hidden="FALSE" Type="Lookup" List="AppPrincipals" Name="AppAuthor" DisplayName="App Created By" ShowField="Title" JoinColName="Id" SourceID="http://schemas.microsoft.com/sharepoint/v3" StaticName="AppAuthor" FromBaseType="TRUE" />
```
This change will just return schemaXml in case the target list cannot be found.
Included above field in test …
=> FixLookupField. If target list is not found, just return fieldXml

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectField.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs
| Related issues?  | fixes #1236 
When extracting calculated fields from non-English site collections the field.Formula property will return a translated formula.
Only English formulas can be used when creating fields using xml. This change uses the formula element from the schema xml instead.
Another issue is that the tokenized schemaXml is overwritten when the PersistMultiLanguageResources attribute is set. This is fixed by changing the order of tokenization when extracting the field.
=> Fixed issue with calculated fileds for non-English site collections

Core/OfficeDevPnP.Core/Extensions/FieldAndContentTypeExtensions.cs
| Related issues?  | mentioned in https://github.com/SharePoint/PnP-PowerShell/issues/1504
Using this extension method, you can update the content type properties like description, group, form urls, etc
The associated PnP PowerShell command will be `Set-PnPContentType` which needs to be added.
=> Feature - ability to update content type properties

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectContentType.cs
| Related issues?  | fixes #778 
Change setting of content type properties ReadOnly, Hidden and Sealed to only apply when there is an actual change.
This change will fix #778 as long as the content type does not change the Sealed property. The Sealed property appears to only be allowed to change if the user is a site collection administrator. For new content types the Sealed property will be false by default.
=> Prevent access denied exception when provisioning content types

Core/OfficeDevPnP.Core.Tests/Extensions/NavigationExtensionsTests.cs, Core/OfficeDevPnP.Core/Extensions/NavigationExtensions.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectNavigation.cs
The quick links navigation may contain up to three levels. However, the provisioning logic previously supported only two levels. This commit adds support for a third level and tests for adding second and third level nodes.
| Related issues?  | fixes #1926 
This PR adds an optional parameter, `string l1ParentNodeTitle=null` to `NavigationExtensions.AddNavigationNode` that should be used to indicate the top-level parent in case the new node should be added on the third level. The logic that finds the parent node and adds the new node as child extracted so it can be reused for both top navigation and quick links.
The recursive …
=> adds support for a 3rd navigation level in provisioning

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectSiteSecurity.cs
I encountered a strange behaviour with SharePoint 2013 that updates to BasePermissions did not work. The solution is to create a new BasePermission object, assign it to the RoleDefinition and update.
Additionally I made a small optimization: the IsDirty check now considers existing permissions as well as the permissions in the template.
=> Stability improvements for updates to RoleDefinition update

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectApplicationLifecycleManagement.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectTenant.cs
…storage entities processing
1) Currently for SPO, in case of simple provisioning template like the one mentioned below, we are calling the Tenant as well as ALM handlers. It is not needed. This PR will fix it by doing a more robust checking of the schema elements
```
<?xml version="1.0"?>
<pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2018/05/ProvisioningSchema">
<pnp:Preferences Generator="OfficeDevPnP.Core, Version=2.26.1805.1, Culture=neutral, PublicKeyToken=5e633289e95c321a" />
<pnp:Templates ID="CONTAINER-TEMPLATE-0F3B0BF2CA31408CB750A266BC6A2CAB">
<pnp:ProvisioningTemplate ID="TEMPLATE-0F3B0BF2CA31408CB750A266BC6A2CAB" …
```
=> Fix - Skip calling of Tenant and ALM handlers when not needed , null check in 

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/TokenParser.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/Utilities/TenantHelper.cs
PnP Provisioning template having storage entities fails in case the tenant app catalog site collection doesn't exist.
This PR adds an additional null check while provisioning storage entities as well as while token parsing
=> Improvements to processing storage entities

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs
| Related issues?  | fixes #2022
Fixes a problem with ignoring all list custom actions but the first one when applying a provisioning template to an existing list [#2022]
=> Fixes a problem with ignoring all list custom actions but the first one when applying a provisioning template to an existing list

Core/OfficeDevPnP.Core/Diagnostics/Log.cs
Fixed logic to decide if logging should happen based on configured log level. Log levels with equal or higher severity than the configured log level will now always be logged.
Previously the behaviour was that when logging an error it would only log the event if log level was set to error or debug. Errors should always be logged. Similar issues existed when logging information (would log if log level was set to higher severity than information).
=> Log level logging fixes

Core/OfficeDevPnP.Core.Tests/Framework/Functional/Validators/WebSettingsValidator.cs, Core/OfficeDevPnP.Core/Extensions/WebExtensions.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectWebSettings.cs
| Related issues?  | fixes #1793 
Moved or removed from provisioning engine, and WebExtensions classes the lines where _RequestAccessEmail_ was inside pre-processor directives '#if ONPREMISES' , as it is now supported by CSOM for either SP2013 and SP2016
Massimo
=> Enables Web.RequestAccessEmail for OnPrem (both 15.0 and 16.0)

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectFiles.cs
This PR contains a small adjustement to the `ObjectFilesHandler`. Its purpose is to allow token in file names.
For example, it allows setting filenames like:
```
<pnp:Files>
<pnp:File Src="SiteAssets" 
TargetFileName="logo-{parameter:CustomerNameEncoded}.png" 
Folder="Assets/default-logo.png" 
/>
</pnp:Files>
```
=> Add token parsing in `targetFileName` property of file object

Core/OfficeDevPnP.Core/AuthenticationManager.cs, Core/OfficeDevPnP.Core/IdentityModel/TokenProviders/ADFS/KerberosMixed.cs, Core/OfficeDevPnP.Core/IdentityModel/WSTrustBindings/KerberosWSTrustBinding.cs, Core/OfficeDevPnP.Core/IdentityModel/WSTrustBindings/WindowsWSTrustBinding.cs, Core/OfficeDevPnP.Core/OfficeDevPnP.Core.csproj
This pull request contains an enhancement with which the authentication to a SharePoint server using an ADFS instance is possible by using kerberos authentication. Currently authenticating via ADFS is only possible with login/password and using a X.509 certificate.
In an on premises environment it's common that service accounts authenticate to other backend systems via Kerberos including the Kerberos Delegation mechanism, in which the service account can act as an specific user account. 
This PR provides three new public methods to the AuthenticationManager with which developers can at first determine the required relying party identifier for an …
=> Add support for Kerberos authentication against ADFS

Core/OfficeDevPnP.Core.Tests/Framework/ObjectHandlers/ObjectSiteSecurityTests.cs, Core/OfficeDevPnP.Core/Extensions/ClientObjectExtensions.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectSiteSecurity.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/TokenDefinitions/AssociatedGroupToken.cs, Core/OfficeDevPnP.Core/OfficeDevPnP.Core.csproj, Core/OfficeDevPnP.Core/Utilities/PnPUtility.cs
…member/visitor groups
Added support for provisioning and extracting associated owner, member, and visitor group.
I have changed the creation of groups in ObjectSiteSecurity to not require a group owner. This is not enforced by SharePoint, and will result in the current user to be the group owner. This needs to be changed in the schema too to be fully supported.
Changed group creation to support clearing description if it's an empty string in the schema.
I believe ClientObjectExtensions.ServerObjectIsNull is incorrectly implemented. I added a null check as the method could throw null reference exception. It also returns true when …
=> Provision and extract associated groups

Core/OfficeDevPnP.Core/Sites/SiteCollection.cs, Core/OfficeDevPnP.Core/Sites/SiteCollectionCreationInformation.cs
| Related issues?  | fixes https://github.com/SharePoint/PnP-PowerShell/issues/1688 , #2016 
1) Added support for HubSiteId in Modern sites
2) Added support to add additional owners for Modern team site and while Groupifying classic sites
3) Fixed site classification issue for Modern team sites and Groupified sites
4) Changed OData JSON format specification to v4 while provisioning modern sites
5) Made use of JSON light to reduce payload
=> Feature - set additional properties while provisioning modern sites + bug fix

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectSiteSecurity.cs
Small bugfix where EnsureProperty was executed on an unassigned Principal object.
=> Skip executing EnsureProperty on Principal object when the Principal is null

Core/OfficeDevPnP.Core/Framework/Graph/UnifiedGroupsUtility.cs
| Related issues?  | fixes https://github.com/SharePoint/PnP-PowerShell/issues/1327  & https://github.com/SharePoint/PnP-PowerShell/issues/1272
1) Added support for filtering group's with special characters in the display name and mailnickname
2) Added support for special characters in user's principal name while updating owners and members.
3) Modified groups filter from `startsWith` to `eq` to fix that PnP PS issue (1272) while provisioning groups
4) Also, added a `count > 0` check while adding owners and members during groups provisioning process
=> Feature: Added support for special characters while filtering groups and users

Core/OfficeDevPnP.Core.Tests/ALM/ALMTests.cs, Core/OfficeDevPnP.Core/ALM/AppManager.cs, Core/OfficeDevPnP.Core/ALM/AppMetadata.cs, Core/OfficeDevPnP.Core/Extensions/ClientContextExtensions.cs, Core/OfficeDevPnP.Core/Extensions/TenantExtensions.cs, Core/OfficeDevPnP.Core/Extensions/WebExtensions.cs, Core/OfficeDevPnP.Core/Utilities/RESTUtilities.cs
| Related issues?  | partially SharePoint/PnP-PowerShell#1812, successor of #2071 
As we needed the ALM functions in SharePoint 2019, I built upon the partially prepared code to include it. Changes are:
- Fixed error in RESTUtilities.SetAuthenticationCookies for on premises environments, as the credentials passed are not of type SharePointOnlineCredentials but NetworkCredentials. 
- Added additional authentication data in `AppManager` and `ClientContextExtensions` for on premises scenarios with NetworkCredentials. This was sufficient for my scenarios, however, I am not sure, if it is completley sufficient for all possible scenarios.
- The GetAvailable* tests in the ALMTests …
=> ALM functions for SharePoint 2019 on premises

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/Utilities/TenantHelper.cs
| Related issues?  | fixes #2088 
Removes the additional check `appMetadata.Deployed == false` check while publishing the app. 
Because of this `if` condition, while we are able to upload and overwrite the app package, we are unable to actually publish the latest updates if it was already deployed.
=> Fix #2088 - Provisioning template doesnt publish the app

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectField.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs
| Related issues?  |  no
If the attribute InternalName does'nt exists in the field SchemaXML, use the attribute Name for logging provisioning progress.
=> Ensure Field InternalName is correctly retrieved when logging provisision progress

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectFiles.cs
for modern sites while uploading files to siteAssets library.
This PR adds `web.Lists.EnsureSiteAssetsLibrary();` method to the files handler while uploading files.
If this is not present, then we get an access denied error while provisioning the files.
Consider a scenario as below, we use the below snippet to create a communication site and apply the template:
```
CommunicationSiteCollectionCreationInformation communicationSiteCollectionCreationInformation = new CommunicationSiteCollectionCreationInformation
{
Title = "Test Title comm site 1001",
Description = "Test desc",
Lcid = 1033,
ShareByEmailEnabled = true,
Url = …
```
=> Feature/Fix: Added ensureSiteAssetsLibrary method to prevent access denied 

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectSiteSecurity.cs
| Related issues?  | fixes #2127 
This PR fixes the issue of additional groups getting created while provisioning the template.
While debugging this, also found that everytime we create a new group and associate them, we need to run executeQueryRetry as well. 
Besides that also did a delta check to see if the Associated group name has changed in the groups, if it has changed then we will set that as the default group.
Have tested it quite exhaustively and it works fine for all sites , @jansenbe  can you have a look at this and let me know your thoughts ?
=> Fix : Skip creation of associated groups if they already exist

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectSiteSecurity.cs
Earlier it wasn't possible to EnsureUser for an extern user.
However, now if an external user exist in directory for the tenant, it is possible to EnsureUser on a Site where the user doesn't exist within the Site Collection.
So instead of skipping external users this change will allow the provisioning engine to try to EnsureUser and log a Warning if it didn't succeed.
=> EnsureUser for external users

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/Utilities/TermGroupHelper.cs
Add support for tokens in the Termset Owner property. 
Example: <pnp:TermSet Name="XXX" Owner="{associatedownergroup}" />
This solves issue: https://github.com/SharePoint/PnP-Sites-Core/issues/2082
=> Parse the Termset Owner string

Core/OfficeDevPnP.Core/CoreResources.Designer.cs, Core/OfficeDevPnP.Core/CoreResources.resx, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectTeams.cs
- Added a method for overwriting certain properties in the team template (JSON) if they've been separately specified in the xml markup.
- Made an error message more descriptive in case team provisioning fails.
=> Team template property overwrite

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectClientSidePages.cs
| Related issues?  | fixes #2184
A fix for the issue described in the ticket. At least in my case the missing page could be detected after adding this check.
=> fixing client side page existence check sometimes flags page as existing although it isn't

Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/Resolvers/NavigationFromModelToSchemaTypeResolver.cs
The provisioning schema specifies that GlobalNavigation is an optional element but if this element is not included in the provisioning template we get a null reference exception. This PR includes a fix for this.
=> Fix for global navigation null reference exception when provisioning

Core/OfficeDevPnP.Core.Tests/Framework/ObjectHandlers/ObjectTermGroupsTests.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/Utilities/TermGroupHelper.cs
| Related issues?  | fixes #2176 
Fixed test. Reused term sets should provision correctly (how did this ever work??). I hope this also covers cases where term sets are already existing or the structure is more complex.
=> #2176 fixing test: reused term sets are not set up properly

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectSiteFooterSettings.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectSiteHeaderSettings.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectTeams.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/SiteToTemplateConversion.cs
1) This PR fixes compile issues in the new Site Header, Footer and Teams handlers.
2) Used `(web.Context as ClientContext).Site.IsCommunicationSite()` extension method to check communication site in the Footer handler.
3) Added missing `web.Context.ExecuteQueryRetry();` in the Site Header handler.
4) Removed extra checks for header provisioning since modern pages on classic sites can have these capabilities.  
This is an extension of the [PR 2164](https://github.com/SharePoint/PnP-Sites-Core/pull/2164) which i had to close as i made boo-boo :(
=> Fix : Compile issues for OnPrem in the new handlers

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectSiteSecurity.cs
| Related issues?  | fixes #2205, https://github.com/SharePoint/PnP-PowerShell/issues/2057
This PR fixes the above mentioned issues which were caused due to a regression in the previous version 3.7. We are simply ensuring that the principal Id is initialised for role definitions
=> Fix : Ensuring principal Id for role definition

Core/OfficeDevPnP.Core/Utilities/RESTUtilities.cs
This PR fixes an issue that occured when `Credentials` were not set and the cookie was also empty (this is the case, when the `CurrentCredentials` flag is set in the `Connect-PnPOnline` PowerShell CmdLet).
If the `cookieString` is null, it does not make sense to continue executing the method as all subsequent commands expect the `cookieString` to contain a value.
=> Fixed NullReferenceException caused by missing cookie

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectField.cs
| Related issues?  | no
Tokenization of a Calculated field is incorrect when the formula contains the same field more than once e.g.
_=IF(Probability=\"Low\",1,IF(Probability=\"Medium\",2,3))_
The tokenization result for this will be:
_=IF(**[{fieldtitle:[{fieldtitle:Probability}]}]**=\"Low\",1,IF(**[{fieldtitle:[{fieldtitle:Probability}]}]**=\"Medium\",2,3))_
Each time a field is referenced in the formula, a corresponding FieldRef element is present in the schema xml for the calculated field. The result of this is that on the second iteration, the token for the field will get tokenized and create a token inside another token.
This PR ensures that we only process unique …
=> Fix tokenization for calculated field formula where one field is present multiple times in the formula

Core/OfficeDevPnP.Core/Extensions/ClientContextExtensions.cs, Core/OfficeDevPnP.Core/Sites/SiteCollection.cs
This PR adds the capability to connect existing Modern team site to Microsoft team.
It will also work for classic sites which have been newly groupified because they have the RelatedGroupId property populated. 
Usage:
`var teamId = clientContext.TeamifyAsync().GetAwaiter().GetResult();`
or 
`var teamId = SiteCollection.TeamifySiteAsync(clientContext).GetAwaiter().GetResult();`
=> Feature: Adds capability to connect existing team site to MS Teams team

Core/OfficeDevPnP.Core/Enums/TenantEnums.cs
Add ReadOnly option for SiteLockState enum as it is supported for SPO now.
Described at (-LockState):
https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-sposite?view=sharepoint-ps 
=> Update SiteLockState enum

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectNavigation.cs
| Related issues?  | fixes #2283
When ReplaceFileUniqueToken can not resolve the Token {fileuniqueid:xxx} to a File it will try if it can resolve it to a Folder. In that way we can use the fileuniqueid token also for OneNote as the root is a Folder.
=> Fix fileUniqueId parsing in ReplaceFileUniqueToken when point to Folder

Core/OfficeDevPnP.Core/Sites/SiteCollection.cs
As per the updated article for communication sites,  [create modern SharePoint sites](https://docs.microsoft.com/en-us/sharepoint/dev/apis/site-creation-rest), owner property is mandatory in App-only context. This PR adds support for it as per updated guidance.
=> Feature: Made owner mandatory for communication site in app-only context

Core/OfficeDevPnP.Core/Pages/ClientSidePage.cs, Core/OfficeDevPnP.Core/Pages/ClientSidePageHeader.cs
When creating a Client Side Page based on the Visual Layout template, the header image will reference "/_LAYOUTS/IMAGES/VISUALTEMPLATETITLEIMAGE.JPG".
When applying an exported template, this will result in an "Server relative urls must start with SPWeb.ServerRelativeUrl" exception within OfficeDevPnP.Core.Pages.ClientSidePageHeader.ResolvePageHeaderImage.
This PR allows references to the _layouts folder.
=> Support for default header image for client side page based on visual layout

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectSiteSecurity.cs
| Related issues?  | fixes #2302 
This is just a small fix where the Id property of the sitegroups had not been loaded, but the property is beeing accessed later in the code. This prevents new sitegroups from beeing provisioned.
=> fix sitegroup provisioning

Core/OfficeDevPnP.Core/Extensions/SecurityExtensions.cs
This PR fixes an exception "The 'Equals' member cannot be used in the expression" thrown in GetPrincipalUniqueRoleAssignments.
=> Fix for "The 'Equals' member cannot be used in the expression" in GetPrincipalUniqueRoleAssignments

.gitignore, Core/OfficeDevPnP.Core/Utilities/Caml.cs
This PR contains a little improvement for the CAML class. When doing a CAML query that contains a In-comparision, one would need to forge most of the query by himself with the current class:
```csharp
var fieldRef = CAML.FieldRef("ID")+"<Values><Value Type="Number">1</Value><Value Type="Number">2</Value></Values>";
var caml = CAML.In(fieldRef);
```
There is no method for creating a Value node without a FieldRef node. Furthermore the Values node also needs to be created manually.
I've added an overload for the In method, accepting a FieldRef string and an array for Value strings. In Addition, I've added a method "Value" to generate the string for a …
=> CAML improvements

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectHandlerBase.cs
| Related issues?  | fixes #2247
Fix Views tokenizer not working correctly in the root site collection with a ServerRelativeUrl of value "/" .
This is the output xml before this PR:
```xml
<View Name="{4CDD7F9D-7A64-4CA7-9C73-5F0FC848E92B}" DefaultView="TRUE" MobileView="TRUE" MobileDefaultView="TRUE" Type="HTML" DisplayName="All Documents" Url="{site}Shared Documents{site}Forms{site}AllItems.aspx"  Level="1" BaseViewID="1" ContentTypeID="0x" ImageUrl="{site}_layouts{site}15{site}images{site}dlicon.png?rev=47">
<Query>
<OrderBy>
<FieldRef Name="FileLeafRef" {site}>
<{site}OrderBy>
<{site}Query>
<ViewFields>
<FieldRef Name="DocIcon" {site}>
<FieldRef Name="LinkFilename" …
```
=> Fix tokenization issue with views in root site collection

Core/OfficeDevPnP.Core.Tests/OfficeDevPnP.Core.Tests.csproj, Core/OfficeDevPnP.Core.Tests/TestCommon.cs, Core/OfficeDevPnP.Core.Tests/Utilities/UnifiedGroupsUtilityTests.cs, Core/OfficeDevPnP.Core/Framework/Graph/UnifiedGroupsUtility.cs
Added methods for managing (get, list, restore, perm. remove) deleted Office 365 groups via Graph (beta) + unit tests. The code will be used by new PnP PowerShell commandlets.
=> Methods for managing deleted Office 365 groups

Core/OfficeDevPnP.Core.Tests/Sites/SiteCollectionTests.cs, Core/OfficeDevPnP.Core/Extensions/ClientContextExtensions.cs, Core/OfficeDevPnP.Core/Sites/SiteCollection.cs, Core/OfficeDevPnP.Core/Sites/SiteCollectionCreationInformation.cs
| Related issues?  | mentioned in #1401 
This PR adds a new extension to the clientcontext that allows creation of a modern team sites with no group. The extension uses the SPSiteManager REST endpoint which is much faster than the SpoOperation used by the existing extension on the tenant object.
=> Add extension to create team site with no group using SPSiteManager

Core/OfficeDevPnP.Core/Pages/ClientSidePage.cs, Core/OfficeDevPnP.Core/Pages/ClientSideSectionEmphasis.cs
| Related issues?  | fixes https://github.com/SharePoint/PnP-PowerShell/issues/2141
ZoneEmphasis in some cases returns undefined when requesting a ClientSidePage. This code change will ensure the PnP Core library can deal with this whereas now it would crash. I ran into this issue while fixing issue https://github.com/SharePoint/PnP-PowerShell/issues/2141 where requesting a clientside page on a subsite would return the client page but with the zoneemphasis information set to "undefined" which caused the code to crash trying to JSONConvert that into an int.
=> Allow ZoneEmphasis in ClientSidePage to be undefined

Core/OfficeDevPnP.Core/CoreResources.resx, Core/OfficeDevPnP.Core/Pages/ClientSidePageHeader.cs
| Related issues?  | fixes #2355 
This PR adds support for modern page header images which reside outside the current site collection. The image can be in a different site collection or any other CDN path.
Have modified the error message accordingly so that the end user is aware of the implication of setting the image path outside of the current site collection scope.
This PR was added since it was already possible to do this via UI, only when using the provisioning engine did we face this issue. I tested this with images in different site collection as well as hosted outside SharePoint on CDNs as well as wordpress blogs and it works fine in both the cases.
=> Feature: added support for page header images which reside outside current site collection

Core/OfficeDevPnP.Core/Extensions/ClientContextExtensions.cs, Core/OfficeDevPnP.Core/Sites/SiteCollection.cs
This PR adds additional methods related to teamify-ing O365 group sites.
1) Adds method of check if the teamify prompt is visible or not in the bottom left corner of the site.
2) Adds method to hide the teamify prompt from the bottom left corner of the site.
=> Feature: added support for additional teamify methods

Core/OfficeDevPnP.Core/Framework/Provisioning/Extensibility/ExtensibilityManager.cs
In the ExtensibilityManager class a formatted string is passed to the Log.Error function.
The Log.Error function is doing string.Format(), so we should leave it the Error function to format the string to avoind getting "Input string was not in a correct format." (in case the string contains {} characters)
=> Don't pass formatted string to logger

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectCustomActions.cs
| Related issues?  | no
Enabled functionalities for User Custom Actions in provisioning engine that is available for SharePoint 2019 (ClientSideCopmonentId, ClientSideCopmonentProperties, and resource tokens)
=> Enabled custom action functionality for SharePoint 2019 that was incorrectly disabled.

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/Utilities/ClientSidePageContentsHelper.cs
| Related issues?  | fixes #2370 
while concatinate the string for jsonControlData we use now JsonConvert.ToString for Title and Description to make sure special char in string are handled correct and not break the JSON constructed during export in ClientSidePageContentsHelper.
=> use JsonConvert.ToString to handle special char in Title and Description

Core/OfficeDevPnP.Core/Framework/Provisioning/Model/Teams/TeamFunSettings.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectTeams.cs
1) This PR adds additional null check while provisioning teams with additional settings like FunSettings, GuestSettings etc. 
2) Additionally, it removes compiler directives which are not needed as we already handle it "above".
3) If the Giphy content rating is set to Strict, that value is not respected, so fixed that issue with static class.
4) Added support for users with special characters in email address.
This PR fixes null issue when you try to provision a team from PnP template which is as below:
```
<pnp:Teams>    
<pnp:Team DisplayName="Sample Team 01" Description="This is just a sample Team 01" Visibility="Public" …
```
=> Fix: Additional null checks and content rating fix while creating team

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/Utilities/ClientSidePageContentsHelper.cs
@jansenbe Initialize RegEx for CollectImageFilesFromGenericGuids and CollectSiteAssetImageFiles outside the foreach loop and make them compiled does speed-up time spend in ObjectClientSidePageContents Extract (on my test site from 26min down to 11min).
=> Fix CPU Load and Performance for ExtractClientSidePage

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstanceDataRows.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/Utilities/ListItemUtilities.cs
@erwinvanhunen  Fix to Add Attachments to new List Items. Minimal invasive fix to Commit cd457e1 to avoid ExecuteQuery for new ListItem until all Attachments have been added as otherwise the Error "Item does not exist. It may have been deleted by another user." will happen.
=> Skip ExecuteQuery for new ListItem until all attachments are added

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/SiteToTemplateConversion.cs
@PaoloPia  CallWebHooks fails when WebHooks in template are empty since it passes null to AddRange. Fixed by having if-statement outside AddRange
=> SiteToTemplate - fix WebHook AddRange null exception

Core/OfficeDevPnP.Core/AuthenticationManager.cs, Core/OfficeDevPnP.Core/Utilities/TokenHelper.cs
| Related issues?  |  n/a
This PR contains an enhancement whith which it's possible to create an App Delegation token in an Hightrust configuration to act as specific user (behalf-of) within a SharePoint connection. Up to now this scenario was only possible with an `WindowsIdentity` object instance available, which is not the case if the addin is deployed in an environment which isn't connected to an Active Directory environment (e.g. Azue WebApp) and is employing other authentication themes like JWT Bearer or SAML tokens. 
This PR now provides new methods on `Core/OfficeDevPnP.Core/AuthenticationManager.cs` which allows to pass the SID or the UPN for an user for creating …
=> Feature: S2S user delegation in Hightrust app scenario

Core/OfficeDevPnP.Core/CoreResources.Designer.cs, Core/OfficeDevPnP.Core/CoreResources.resx, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/Extensions/LocalizationExtensions.cs
| Bug fix?        |   yes
| Related issues?  | fixes #2365 
The fix checks if destination site IsMultilingual and skips localization if not. 
If the Site IsMultilingual=true, it checks if the language from ressourcefile is in SupportedUILanguageIds of the web and applys only if they exist.
=> Fix list view localization (when destination single Language and PnP-Template Multilanguage)

Core/OfficeDevPnP.Core/CoreResources.Designer.cs, Core/OfficeDevPnP.Core/CoreResources.resx, Core/OfficeDevPnP.Core/WebAPI/WebAPIHelper.cs
Log and cast a clearer exception instead of an unhandled null reference exception in WebAPIHelper.GetClientContext when the cache item has not been registered using RegisterWebAPIService.
=> Fix for null reference exception in WebAPIHelper.GetClientContext

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectHierarchyTenant.cs
This PR adds additional check to the WillProvision method so that tenant settings are only applied if they are specified in the template.
Take the case of the below template:
```xml
<pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2018/07/ProvisioningSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://schemas.dev.office.com/PnP/2018/07/ProvisioningSchema https://raw.githubusercontent.com/OfficeDev/PnP-Provisioning-Schema/master/OfficeDevPnP.ProvisioningSchema/ProvisioningSchema-2018-07.xsd">
<pnp:Preferences Author="Gautam" Version="1.0" />
<pnp:Sequence ID="Test">
<pnp:SiteCollections> …
```
=> Fix for Tenant Hierarchy settings when template doesnt use them.

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstanceDataRows.cs
Move the check if ExecuteQuery is needed outside the Block for Update the Attachments in order to have it executed even when no Attachments exist.
=> Provisioing: Make sure we ExecuteQuery for newItem when no Attachments exist

Core/OfficeDevPnP.Core/CoreResources.Designer.cs, Core/OfficeDevPnP.Core/CoreResources.resx, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectContentType.cs
The DefaultDocument of a DocumentSet will be extracted - for Example: 
<pnp:DefaultDocuments>
<pnp:DefaultDocument Name="DocSetTestDok.docx" ContentTypeID="0x0101007B3995784C2BF642B3B4D7F4DE37C96E" FileSourcePath="_cts/MyDocSetTest/DocSetTestDok.docx" />
</pnp:DefaultDocuments>
=> Feature: Extract DefaultDocument for DocumentSet ContentType

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstanceDataRows.cs
@erwinvanhunen New List Item will have security not set since listitem.SetSecurity does want to read item security but item is not comited to sp at that time. The Block is now moved to the end of the function.
=> Fix set Item Security on new ListItems

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectSiteSecurity.cs
| Related issues?  | partially #2281
Fixes the issue 'The specified user X could not be found' when updating an existing SharePoint group.
=> Fix 'The specified user could not be found' when updating existing groups

Core/OfficeDevPnP.Core/Utilities/TokenHelper.cs
This fixes a very confusing NullReferenceException in in TokenHelper when the WebRequestException has no response - eg. when it's a timeout.
Eg. this one when using the `Connect-PnPOnline`:
```
PS>TerminatingError(Connect-PnPOnline): "Object reference not set to an instance of an object."
Connect-PnPOnline : Object reference not set to an instance of an object.
+ CategoryInfo          : NotSpecified: (:) [Connect-PnPOnline], NullReferenceException
+ FullyQualifiedErrorId : System.NullReferenceException,SharePointPnP.PowerShell.Commands.Base.ConnectOnline
```
And a stack trace like this:
```
System.NullReferenceException: Object reference not set to an instance of an object.
at OfficeDevPnP.Core.Utilities.TokenHelper.GetAppOnlyAccessToken(String targetPrincipalName, String targetHost, …
```
=> add null guard to catch block in GetAccess*Token

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectSiteSettings.cs
site.EnsureProperty(s => s.SearchBoxInNavBar) before try to compare in if-statement.
=> ObjectSiteSettings Provisioning: Fix SearchBoxInNavBar not intitialized 

Core/OfficeDevPnP.Core/Extensions/FieldAndContentTypeExtensions.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/Model/FieldRef.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectContentType.cs
| Related issues?  | fixes #2251 #2049
UpdateChildren was added to FieldRefs in Content Types.  According to [this](https://github.com/SharePoint/PnP-Sites-Core/pull/2049#issuecomment-494748756) comment the original PR wasn't merged.
This includes the changes in the original PR, plus an additional `AddFieldById` overload.
This also wasn't the whole story as any other changes to the content type would mean `Update` is called, plus if FieldRefs are in a different order again `Update` is called with updateChildren true.
I've defaulted the first `Update`, which is CT properties only to `false`
I've added a slightly questionable workaround where I check that is there are changes …
=> Content type update children

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectField.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs
When providing a FieldDefaults under a ListInstance for a taxonomy field and setting the ID to -1, this code change will make sure to update the -1 to the actual ID as it exists in the hidden TaxonomyHiddenList list or if it doesn't exist in there yet, create a new entry for it and update the -1 to the ID of this new entry.
To test this, create a PnP Provisioning Template by i.e. exporting an existing site. Inside a `<pnp:ListInstance> ... </pnp:ListInstance>` element, add:
`		  <pnp:FieldDefaults>
<pnp:FieldDefault FieldName="TaxSiteField">-1;#Value 3|3d30ef63-d5a4-42fa-909c-5cd578223132</pnp:FieldDefault>
</pnp:FieldDefaults>`
Update TaxSiteField …
=> Allow -1 to be used for taxonomy fields in pnp:FieldDefault

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectApplicationLifecycleManagement.cs
This PR adds additional check to the WillProvision method so that ALM handler is called only if necessary values are present in the template.
=> Fix for ALM handler when template doesn't use it

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectContentType.cs
This PR fixes an issue provisioning ReadOnly content types.
It isn't possible to update the content type after it is set ReadOnly.
The problem is solved by postponing setting ReadOnly to True.
Example of failing template.
```xml <?xml version="1.0"?>
<pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2019/09/ProvisioningSchema">
<pnp:Preferences Generator="OfficeDevPnP.Core, Version=3.15.1911.0, Culture=neutral, PublicKeyToken=5e633289e95c321a" />
<pnp:Templates ID="CONTAINER-TEMPLATE-C990DA14733E404EBCC57C5FDD879653">
<pnp:ProvisioningTemplate ID="TEMPLATE-C990DA14733E404EBCC57C5FDD879653" Version="1" BaseSiteTemplate="STS#3" …
```
=> Fix provisioning ReadOnly content type

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstanceDataRows.cs
When Library is exported with Content and the NewDocumentTemplate contains url's to files, those files will be exported as well.
=> Export Files in Forms folder when referenced in NewDocumentTemplate Property

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectClientSidePageContents.cs
Fix handles the situation were the user deleted the Template Folder in SitePages and Property vti_TemplatesFolderGuid contains therefore the Folder UniqueId of an not existing folder. 
If we can not resolve Folder by it's uniqueid we fallback to fix the default Foldername.
=> fix User Deleted Templates Folder in SitePages on Export

Core/OfficeDevPnP.Core/Entities/CustomActionEntity.cs, Core/OfficeDevPnP.Core/Extensions/NavigationExtensions.cs
Added ability to set host properties on a CustomAction for SharePoint Online. See https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/basics/preallocated-space-placeholders for more information on what can be done with the host properties.
=> Added HostProperties to CustomAction

Core/OfficeDevPnP.Core/Extensions/WebExtensions.cs
Added `EnableRequestAccess` method without providing e-mail addresses to instruct setting it back to the default owners of the site. After setting it to the default, trying to set it to a specific e-mail address again will set the e-mail address but will leave the selected option at the default owners in the web UI. To mitigate this, we always need to set `SetUseAccessRequestDefaultAndUpdate(false)` when setting `RequestAccessEmail`
=> Added option to set requesting access to a web to the default owners

Core/OfficeDevPnP.Core/Extensions/WebExtensions.cs
As far as I can judge, you can only set one e-mail address to receive the access request e-mails. Updating the code to mark the current methods accepting multiple e-mail addresses as obsolete and adding new methods making it clear that only e-mail address can be set. Test it for yourself by providing multiple e-mail addresses either through the current code or the web UI. It will result in an error no matter if you use a comma or semicolon to separate multiple addresses.
=> Only allow one e-mail address to receive access requests

Core/OfficeDevPnP.Core/CoreResources.Designer.cs, Core/OfficeDevPnP.Core/CoreResources.resx, Core/OfficeDevPnP.Core/Extensions/FileFolderExtensions.cs
| Related issues?  | helps to troubleshoot https://github.com/SharePoint/PnP-PowerShell/issues/2513
When applying a PnP Template that tries to upload files with invalid/unsupported characters in the file name, an error message is displayed. This PR includes the actual filename in the error message, making it easier to find where the issue is in the template (imagine having a template that uploads 100 files).
The updated resource file entry FileFolderExtensions_UploadFile_The_argument_must_be_a_single_file_name_and_cannot_contain_path_characters_ is used only in the single place I updated.
This is how the new error message looks:
How to reproduce template (the TargetFileName …
=> Improve error message when uploading a file with invalid characters in the file name

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectField.cs
Catches WebException with Timeout status to avoid potential timeout exception when updating and pushing changes for a site column used on many subsites and lists.
=> Catch WebException with Timeout status to fix timeout on update field and push changes

Core/OfficeDevPnP.Core/Extensions/BrandingExtensions.cs
The current Composed look for a Modern team site collection is by default empty. 
Extracting this Composed Look and provision it through the Composed Look ObjectHandler will throw the follow exceptions:
- Value cannot be null. Parameter name: masterPageServerRelativeUrl
- The 'colorPaletteUrl' argument cannot be null. Parameter name: colorPaletteUrl	
This PR ensures that the masterPageServerRelativeUrl and the colorPaletteUrl is never set to null.
=> Ensure null value is never set for MaterPageUrl and ColorPaletteUrl

Core/OfficeDevPnP.Core/CoreResources.Designer.cs, Core/OfficeDevPnP.Core/CoreResources.resx, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectContentType.cs
Ensures existing content types set to read only is not updated unless the value is changed to false.
=> Skip update of read only content type unless readonly is changed to false

Core/OfficeDevPnP.Core/Extensions/WebExtensions.cs
Web.IsNoScriptSite() extension method is not a definitive answer to if the site in fact is enabled for NoScript. This can also return true for sites that does not have NoScript enabled and the current user (or app only credentials) does not have required permissions to modify data.
Modified the documentation to highlight this.
=> Added message about false positive noscript detection

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectContentType.cs
Microsoft.SharePoint.Client.DocumentSet.DocumentSetTemplate.IsChildOfDocumentSetContentType requires an ExecuteQuery before it actually does something and returns a valid value. At present it would always return false, regardless if the content type did inherit from the document set content type. Confirmed by using Fiddler to look at the network traffic behind the execution.
=> Fixed IsChildOfDocumentSetContentType in ContentType Provisioning

.gitignore, Core/OfficeDevPnP.Core.Tests/Extensions/FileFolderExtensionsTests.cs
(enable versioing for document library)
UnitTest 'ResetFileToPreviousVersionTest' for SP2013 failed, cause the document library is created without versioning (major version) enabled. This PR enables versioning for document library.
This PR also exculdes output xml files (see .gitignore)
```
Core/OfficeDevPnP.Core.Tests/Resources/Templates/ProvisioningTemplate-*-OUT*.xml
```
=> UnitTest SP2013: Fix - ResetFileToPreviousVersionTest 

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/TokenParser.cs
| Related issues?  | View-/Listnames in Ressourcefiles containing for example char like () will not be replaced with text from Resx-File
While the LocalizationToken Class loads the Names from Resx-File with Regex.Escape but GetResourceTokenResourceValues does not look for the Name Reges.Escape it will not find the translation and therefore not set it if the Name contains any Char handled by Regex.Escape.
=> Fix Resx-Issue if names contain char handled by Regex.Escape

Core/OfficeDevPnP.Core/Sites/SiteCollection.cs
| Related issues?  | None
When a site collection is created with a provisioning template with Apply-PnPTenantTemplate , the default waiting time of 20 minutes (max) is used to ensure the site collection has finished provisioning from SharePoint Online side. As no log message is displayed during this time, it might look to the user like the process is stuck.
This PR adds additional debug logs (enabled with [Set-PnPTraceLog](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/set-pnptracelog?view=sharepoint-ps) -On -Level Debug) to monitor the waiting of the site collection creation.
This is how it looks in the console:
This is the text version:
>powershell.exe …
=> Improve logging when waiting for a site collection to be created

Core/OfficeDevPnP.Core/AuthenticationManager.cs
Using PnP PowerShell Connect-PnPOnline -Credentials (Get-Credential) with an username/password combination containing special characters would fail. URL Encoded these HTTP Form Post variables so they are correctly received by the Microsoft Online authentication endpoint.
=> Bugfix for authenticating with credentials containing special characters

Core/OfficeDevPnP.Core/Entities/UnifiedGroupEntity.cs, Core/OfficeDevPnP.Core/Framework/Graph/UnifiedGroupsUtility.cs
Added HasTeam boolean to UnifiedGroupEntity. Updated `GetUnifiedGroup` and `ListUnifiedGroups` to allow an optional boolean to include checking if an Office 365 Group has a Team provisioned for it and populate the HasTeam boolean. Backwards compatible.
=> Added HasTeam boolean to UnifiedGroupEntity

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectContentType.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectNavigation.cs
Make all the Framework Handler use ExecuteQueryRetry to make them handling throttling the same way.
=> Make all the Framework Handler use ExecuteQueryRetry

Core/OfficeDevPnP.Core/Extensions/ClientContextExtensions.cs
| Related issues?  | f
As Azure Function normally not have a app.config they can not set the UserAgent in General easely.
This change loads userAgent from Environment Var SharePointPnPUserAgent.
=> For AzureFunctions allow SharePointPnPUserAgent to be set in Environment

Core/OfficeDevPnP.Core/Utilities/PnPHttpProvider.cs
Implement same logic then for ExecuteQueryRetry and make PnPHandler check for SharePointPnPUserAgent and set UserAgent string accordingly
=> Make PnPHttpProvider respect SharePointPnPUserAgent setting

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectHierarchySequenceSites.cs
This PR adds an additional check to determine whether a particular custom theme exists in the tenant. If it exists, we will apply that theme, otherwise will show a warning and skip it. Currently, if the theme doesn't exist, the provisioning stops at this stage only
=> Fix: additional check to determine whether theme exists in the tenant

Core/OfficeDevPnP.Core/Pages/ClientSideWebPart.cs
| Related issues?  | f
The Parser in the ClientSideWebPart had the extracted Description-Field mapped to the Title-Field - corrected that.
=> Fix client side web part parser description was mapped to title

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectFiles.cs
Error: Files with properties in Libraries with ForceCheckout on failed to be provisioned.
Fix: The function SetFileProperties has to be called before checkin/publish in ObjectFiles
=> Have to set file properties before checkin/publish.

Core/OfficeDevPnP.Core/CoreResources.Designer.cs, Core/OfficeDevPnP.Core/CoreResources.resx, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectContentType.cs
Added functionality to allow a PnP Template to update the following features on a document set:
- WelcomePageFields
- SharedFields
- AllowedContentTypes
- DefaultDocuments
Before this change, they would only be applied on initial run when the document sets would be created by the PnP Provisioning engine.
=> Added functionality to allow PnP Templates to update docsets

Core/OfficeDevPnP.Core.Tests/Extensions/ClientObjectExtensionsTests.cs, Core/OfficeDevPnP.Core.Tests/Extensions/SecurityExtensionsTests.cs, Core/OfficeDevPnP.Core.Tests/Framework/Functional/Implementation/LocalizationImplementation.cs, Core/OfficeDevPnP.Core.Tests/Framework/ObjectHandlers/ObjectFilesTests.cs, Core/OfficeDevPnP.Core.Tests/Utilities/WebParts/XsltWebPartPostProcessorTests.cs, Core/OfficeDevPnP.Core/Extensions/BrandingExtensions.cs, Core/OfficeDevPnP.Core/Extensions/FeatureExtensions.cs, Core/OfficeDevPnP.Core/Extensions/FieldAndContentTypeExtensions.cs, Core/OfficeDevPnP.Core/Extensions/FileFolderExtensions.cs, Core/OfficeDevPnP.Core/Extensions/ListExtensions.cs, Core/OfficeDevPnP.Core/Extensions/PageExtensions.cs, Core/OfficeDevPnP.Core/Extensions/TaxonomyExtensions.cs, Core/OfficeDevPnP.Core/Extensions/WebExtensions.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/Connectors/SharePointConnector.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectClientSidePages.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectFiles.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstanceDataRows.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectNavigation.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectSiteSecurity.cs, Core/OfficeDevPnP.Core/Pages/ClientSidePage.cs, Core/OfficeDevPnP.Core/Sites/SiteCollection.cs
Reverts pnp/PnP-Sites-Core#2602 
running extraction of template showed this code to break:
var iprFeature = features.GetById(featureID);
iprFeature.EnsureProperty(f => f.DefinitionId);
Given we're releasing today, I'm reverting #2602
=> Revert "Fix: ensuring correct usage of EnsureProperties method"

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/Utilities/ClientSidePageContentsHelper.cs, Core/OfficeDevPnP.Core/Pages/ClientSidePage.cs
Since about one week ms seems not to set promoted state to 0 but leave it null. The fix interprets null as promotedstate 0.
=> Fix ExtractClientSidePage check isNews when PromotedState is null

Core/OfficeDevPnP.Core.Tests/Framework/Functional/Implementation/CustomActionImplementation.cs, Core/OfficeDevPnP.Core.Tests/Framework/ObjectHandlers/ObjectSiteSecurityTests.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectSiteSecurity.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/TokenDefinitions/GroupSiteTitleToken.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/TokenParser.cs, Core/OfficeDevPnP.Core/OfficeDevPnP.Core.csproj
| New sample?      | yes
| Related issues?  | mentioned in #2609
What's in this Pull Request?
as agreed this fix implements 2 new tokens groupsitetitle and groupsitename and makes use of this new Tokens while extract the Site Groups and Roles. This tokens represent the sitetitle with special char " / \ [ ] : | < > + = ; , ? * ' @ replaced with _.
=> Handle special char in SiteTile beeing replaced by _ for SP-Groupnames

Core/OfficeDevPnP.Core/Framework/Graph/UnifiedGroupsUtility.cs
Added `UnifiedGroupsUtility.RenewUnifiedGroup` which allows the expiration date of an Office 365 Group to be extended by the number of days defined in the Azure Active Directory Group Expiration policy
=> Added UnifiedGroupsUtility.RenewUnifiedGroup

Core/OfficeDevPnP.Core/AuthenticationManager.cs
Fixing NullReferenceException in case the authentication with credentials fails, such as in the scenario where a user enters incorrect credentials. Returning NULL instead to indicate we don't have an AccessToken.
=> Fixing NullReferenceException in case the authentication with credentials fails

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs
Changing the case of the view title will not update its value. Workaround for this is to change the title to a temporary value before setting the view title to the correct value.
This can be tested when there is a veiw with url "{site}/Library/Forms/A view title.aspx" and Title "A View Title"
When the template is applied multiple times a new view will be created each time with the name specified for the aspx file in the url attribute.
=> Fixed changing view title casing

Core/OfficeDevPnP.Core/Framework/Graph/UsersUtility.cs
Bugfix in paging when requesting Azure Active Directory users and minor help text fix. endIndex argument was used to measure the amount of results that would be returned instead of the index of the last item that should be returned.
=> Bugfix in paging for retrieving AAD Users

Core/OfficeDevPnP.Core/Framework/Graph/GraphHttpClient.cs, Core/OfficeDevPnP.Core/Framework/Graph/Model/User.cs, Core/OfficeDevPnP.Core/Framework/Graph/Model/UserDelta.cs, Core/OfficeDevPnP.Core/Framework/Graph/UsersUtility.cs, Core/OfficeDevPnP.Core/OfficeDevPnP.Core.csproj
Added option to retrieve Azure Active Directory user by its user principal name optionally allowing specific properties to be returned which is useful in i.e. the scenario where you want to retrieve extension attributes.
Also added the ability to retrieve user deltas to specifically get all changes to user objects in AAD since a provided deltatoken has been generated.
=> Added option to retrieve AAD user by its UPN optionally with specific properties

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectClientSidePageContents.cs
| Related issues?  | fixes #2472
The baseUrl for the Root Site would be //SitePages and therefore fail. Since we load the Library anyway we can take the Url from List RootFolder and add the trailing / for RegEx.
=> ClientSidePageContent/ExtractObject - the Url for SitePages Library was wrong for Root (//SitePages)

Core/OfficeDevPnP.Core/Sites/SiteCollection.cs, Core/OfficeDevPnP.Core/Sites/SiteCollectionCreationInformation.cs
This PR adds support to add sensitivity labels while provisioning modern team (backed by M365 group) site and communication site.
Note: in the modern team sites, it takes around 1-2 hours before the label appears.
=> Feature: Added support for Sensitivity Label while creating modern sites

Core/OfficeDevPnP.Core/Extensions/ClientContextExtensions.cs
| Related issues?  | fixes #2645 
This PR includes code to reattach eventhandlers onto copies ClientContext objects to ensure eventhandlers stay active even when using *-PnPProvisioningTemplate cmdlets.
=> Fix *-PnPProvisioningTemplate Cmdlets not working with Windows Auth and a multiple Auth Providers WebApp

Core/OfficeDevPnP.Core/Framework/Graph/UnifiedGroupsUtility.cs
| Bug fix?        | no/yes
Removing requirement for a description to be provided when creating a new unified group as this is not required by the Graph API itself either: https://docs.microsoft.com/en-us/graph/api/group-post-groups?view=graph-rest-1.0&tabs=http#request-body. Tested it without providing it and it creates an unified group without any problems.
=> Removing requirement for a description to be provided for unified group creation

Core/OfficeDevPnP.Core/Sites/SiteCollection.cs
Avoided providing HubSiteId on new sitecollection creation if no HubSiteId has been provided. It causes unnecessary traffic over the wire and yields the same result as not providing at all.
=> Avoided providing HubSiteId on new sitecollection creation if no HubSite has been provided

Core/OfficeDevPnP.Core/Enums/Office365Geography.cs, Core/OfficeDevPnP.Core/OfficeDevPnP.Core.csproj, Core/OfficeDevPnP.Core/Sites/SiteCollection.cs, Core/OfficeDevPnP.Core/Sites/SiteCollectionCreationInformation.cs
| Related issues?  | asked for in i.e. https://github.com/pnp/PnP-PowerShell/issues/2682
Added PreferredDataLocation parameter to creating a new site which allows for specifying of a geographical region for multi-geo enabled tenants.
Also added fix for forcing sensitivitylabel to use the SharePoint API to create the site, otherwise the sensitivity label will not be applied.
=> Added option to provide a PreferredDataLocation for supporting multi-geo tenants

Core/OfficeDevPnP.Core/Framework/Graph/Model/Group.cs, Core/OfficeDevPnP.Core/Framework/Graph/UnifiedGroupsUtility.cs, Core/OfficeDevPnP.Core/OfficeDevPnP.Core.csproj
Added `SetUnifiedGroupVisibility` to `UnifiedGroupsUntility.cs` to allow toggling the visibility of a unified group
=> Added SetUnifiedGroupVisibility to allow toggling the visibility of a unified group

Core/OfficeDevPnP.Core/AuthenticationManager.cs, Core/OfficeDevPnP.Core/Extensions/ClientContextExtensions.cs
| Related issues?  | discussed in https://github.com/pnp/PnP-PowerShell/issues/2742
In PnP PowerShell, when using `Connect-PnPOnline -Url https://tenant.sharepoint.com -WebLogin` and then running a PnPAdminCmdlet such as `Get-PnPTenant`, it would throw a 401 access denied as it doesn't have the FedAuth cookie for the tenant-admin.sharepoint.com domain. With this update, when connecting, it will add the FedAuth cookie for both the tenant.sharepoint.com as well as for the tenant-admin.sharepoint.com domains so the PnPAdminCmdlets will auto elevate and work correctly.
=> Adding authentication cookies for SPO Admin domain

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectWebSettings.cs
Call parse string from TokenParser for SearchCenterUrl property.
=> Call ParseString for webSettings.SearchCenterUrl

Core/OfficeDevPnP.Core/Extensions/ListExtensions.cs
Fixed incorrect location based metadata event receiver reference for SharePoint 2016 and 2019.
Previous version used a reference for SharePoint 2013 for SharePoint 2016 and 2019.
Assembly redirects added by default in SharePoint 2016 and 2019 installations probably made this not a real issue.
=> Fix incorrect onprem eventreceiver reference

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/Utilities/ConnectorFileHelper.cs
| Related issues?  | Improves #2613 
Improve the exception message when a file is not found during the provisioning by throwing a detailed ArgumentException with the filename that was not found instead of throwing a NullDereferenceException.
Outcome without the fix:
Outcome with the fix:
=> Improve exception message when a file is not found during the provisioning

Core/ProvisioningEngineTokens.md
The token {sitecollectionidencoded} was duplicated, missing the {sitecollectionid} token.
Is just a fix a small "bug", for which the token {sitecollectionidencoded} was duplicated, affecting the {sitecollectionid} token.
=> Fixing duplicated sitecollectionidencoded token

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectSiteSecurity.cs
Error: Settings on Associated Groups are not stored in Pnp-XML as on the Associated Groups are no properties to store the values.  
Fix: Export Associated Groups as SiteGroups without member - since members are already in Associated Group. The fix is important as "Change how members can share" is changing the setting on Associated Group on who can read members.
=> Fix preserve SPGroup Config also for Associated Groups

Core/OfficeDevPnP.Core/Extensions/FieldAndContentTypeExtensions.cs
Adds the possibility to set and get the AllowDeletion for a field. This is not exposed by CSOM, but is available by manually manipulating the SchemaXML for the field.
This can be usefull to prevent users from accidentally deleting a field and loosing data contained in that field for all items in a list. Also it will make it possible to prevent deletion of a field from site columns.
A UserVoice request has been created to expose this in CSOM. In the meantime this workaround should cover it.
https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/suggestions/40701070-expose-field-property-setter-for-allowdeletion
=> Added possibility to set AllowDeletion for a field

Core/OfficeDevPnP.Core/Extensions/ClientContextExtensions.cs, Core/OfficeDevPnP.Core/Sites/SiteCollection.cs
This PR adds support to delete modern communication or modern team site(groupless as well as backed by O365 group) 
It is based on [create modern SharePoint site](https://docs.microsoft.com/en-us/sharepoint/dev/apis/site-creation-rest) guidance.
=> Feature: Added support to delete modern sites

Core/OfficeDevPnP.Core/Framework/Provisioning/Model/Teams/BaseTeam.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/Model/Teams/Team.cs
This minor PR makes the Teams specialization and visibility enums nullable to handle null while extraction.
Currently it gives error as 
`Error converting value {null} to type 'OfficeDevPnP.Core.Framework.Provisioning.Model.Teams.TeamSpecialization` and similar for visibility value as well.
=> Minor fix: Made enum nullable for certain types of Teams

Core/OfficeDevPnP.Core/Extensions/PageExtensions.cs
| Related issues?  | none that I know of
This took a while to find. SharePoint apparently cannot export web parts via `exportwp.aspx` when the user agent is missing. 
Minimal PowerShell repro:
```powershell
$request = [System.Net.WebRequest]::CreateHttp('https://sharepointhost:443/hr/_vti_bin/exportwp.aspx?pageurl=https:%2F%2Fsharepointhost:443%2Fhr%2FSystemsites%2FHomepage.aspx&guidstring=c58a4115-542a-4f22-88a0-ae4e16e79877');
$request.Credentials = Get-Credential
$request.Method = 'GET';
#$request.UserAgent = "Mozilla/5.0 (Windows NT; Windows NT 6.2; de-DE) WindowsPowerShell/5.1.19041.1";
$request.GetResponse();
```
The response is a 302 redirect to …
=> Fixing SharePoint 2013 not returning any web parts

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/Extensions/SecurableObjectExtensions.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectFiles.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstanceDataRows.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectPages.cs
| Related issues?  | fixes #2723
Unfortunately some lines of code had to be changed to achieve what I described in #2723. It looks bigger than it actually is because the diff view seems to be confused by the moved code blocks. I extracted methods for code that has already been copy and pasted and that I would've had to copy again.
Assume you have to provision a  template with lots of role assignments for lots of principals. So far they were all applied at once. If one principal couldn't be found anymore the whole operation failed and the provisioning stopped. This is bad. But this logic is still there as step 1 - if it succeeds all is well.
I added a second step that is …
=> Checking for and ignore missing principals when provisioning object security

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectSiteSecurity.cs
Missing principals for direct role assignments on the site level are not handled properly as provisioning fails with an exception.
But the code looks like this wasn't the intention. Here's why:
The exception from `EnsureUser` is being caught:
https://github.com/pnp/PnP-Sites-Core/blob/dev/Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectSiteSecurity.cs#L705-L708
The access to principal is guarded with `?`:
https://github.com/pnp/PnP-Sites-Core/blob/dev/Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectSiteSecurity.cs#L711
And there are `null` checks in place like here: …
=> Fixing handling of missing principal in site security handler

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectWebSettings.cs
AlternateCssUrl of web needs to be loaded to be compared with the template value later here:
https://github.com/pnp/PnP-Sites-Core/blob/dev/Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectWebSettings.cs#L514 
Currently provisioning fails with exception that the property hasn't been loaded (at least on SP 2013).
=> Fix missing (non-loaded) AlternateCssUrl property value

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectSiteSecurity.cs
Log users that couldn't be added to groups. This also makes it more consistent with other places where missing users currently often lead to provisioning being interrupted. As a PnP user I want to be informed about this. The pull request makes it look like so:
Also there is a potential error in the exception handler when accessing the group title. Fixing it while here.
=> Log missing users which couldn't be added to a group and fix potential exception

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectWebSettings.cs
Fixes issue in extraction of template files where the folder property is not tokenized if site collection url contains spacing
=> Ensure decode of folderpath from uri segments to fix issue when url contains spacing

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectField.cs
This PR fixes an issue with update of taxonomy field specific properties like TermSetId, AnchorId, Open etc. through the Field ObjectHandler.
SharePoint doesn't seem to make changes to the properties when they are updated through the field SchemaXML, so we must handle any changes to taxonomy field properties separately.
=> Handle update of taxonomy field specific properties seperately in UpdateField

Core/OfficeDevPnP.Core/Framework/Graph/UnifiedGroupsUtility.cs
| Related issues?  | fixes https://github.com/SharePoint/PnP-PowerShell/issues/2397
As mentioned in the issue as well as in the [docs](https://docs.microsoft.com/en-us/graph/api/team-put-teams?view=graph-rest-1.0&tabs=http) 
> If the group was created less than 15 minutes ago, it's possible for the Create team call to fail with a 404 error code due to replication delays. The recommended pattern is to retry the Create team call three times, with a 10 second delay between calls.
This PR adds a retry mechanism while creating a Team from Unified group.
=> Feature: Added retry mechanism to handle team creation replication delays

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectHierarchySequenceSites.cs, Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/Utilities/TenantHelper.cs, Core/OfficeDevPnP.Core/Sites/SiteCollection.cs
| Related issues?  | fixes #2169
In the current release the SiteDesign attribute on the SiteCollection elements only works for OOTB Site Designs, and the token format `{SiteDesignId:Title of your site design}` does not work, as SiteDesign tokens are not getting parsed.
This PR parses the the SiteDesign token, and adds the `WebTemplateExtensionId` property to the `_api/SPSiteManager/Create` REST API call as the `SiteDesignId` property does not actually apply the Site Design during the site collection creation process (as mentioned in issue [#4810 in the sp-dev-docs repo](https://github.com/SharePoint/sp-dev-docs/issues/4810)).
In making this fix I also noticed that Site …
=> Fix site design token parsing (and application) in tenant provisioning

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs
Fixes some issues relating to token parsing when provisioning folders:
- Tokens was not parsed in folder default value field names and values
- Tokens was not parsed in folder property field name
- Tokens was not parsed in folder property bag key
- Sub-folders were created before the parent folder default values had been provisioned and because of this never received the default field values
=> Fix for token parsing when provisioning folders

Core/OfficeDevPnP.Core.Tests/Extensions/TaxonomyExtensionsTests.cs, Core/OfficeDevPnP.Core/Extensions/TaxonomyExtensions.cs
| Related issues?  | fixes #1955
Fixes an issue where importing terms which include commas, while also providing a GUID for the terms, would create the wrong hierarchy in the termstore.
A import like this:
> Group;#XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX|Set;#XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX|"TermX,TermY";#ZZZZZZZZ-ZZZZ-ZZZZ-ZZZZ-ZZZZZZZZZZZZ
would create a structure like this
> Group > Set > "TermX > TermY"
> TermY" has the GUID ZZZZZZZZ-ZZZZ-ZZZZ-ZZZZ-ZZZZZZZZZZZZ
instead of
> Group > Set > TermX,TermY
> TermX,TermY has the GUID ZZZZZZZZ-ZZZZ-ZZZZ-ZZZZ-ZZZZZZZZZZZZ
=> Fix issue with handling of terms with comma and provided GUID

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectSiteFooterSettings.cs
| Related issues?  | fixes #2792
Fixes #2792 by adding children nodes of FooterLink element. Extended modern footer contains 2 levels of navigation nodes. Simple modern footer contains 1 level, thus bug occurred when 2 levels extended footer was introduced.
=> Fix for sublinks not provisioned in Footer

Core/OfficeDevPnP.Core/Extensions/TenantExtensions.cs
| Related issues?  | none that I'm aware of
When using an App Only AAD connection that has a PnPProvisioningContext delegate setup (in PnP PowerShell this came up for me with ApplyTenantTemplate), IsCurrentUserTenantAdmin would call https://graph.microsoft.com/v1.0/me/memberOf?$select=id,displayName in order to see if the current user is in the _Company Administrator_ role; this approach does not work for an App Only AAD connection. If the AAD App doesn't have Graph permission to read users (which is a valid scenario for all of the provisioning we have been doing to date) you get the following error when calling that endpoint
```
{
"error": {
"code": …
```
=> Adjust tenant admin check to support an App Only AAD connection

Core/OfficeDevPnP.Core/Extensions/PageExtensions.cs
| Related issues?  | fixes https://github.com/pnp/PnP-PowerShell/issues/2921
Currently calling AddWebPartToWikiPage() on a non-wiki page tries to run a Regex on the content of the list field "WikiField" which is null. This Pull Request adds a null check and returns null as result webpart (which is the same existing behavior if the page is not found)
=> Handle AddWebPartToWikiPage() being called on a non-wiki page

Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/Resolvers/V202002/SharingSettingsFromSchemaToModel.cs
This fix from @SteveClements in March was overridden in May, so I am reapplying it.
| Related issues?  | fixes #2595 
This is from the original PR #2596 that was merged but later overridden:
As per item #2595 a simple change to `OfficeDevPnP.Core.Framework.Provisioning.Providers.Xml.Resolvers.V202002.SharingSettingsFromSchemaToModel` to return `null` when `SharingSettings` are not used in the template XML.
Currently it will return a default value which is `Disabled`
=> Reapply PR #2596 which addresses Issue #2595

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs
The List View Formatter Field fails during provisioning since in more complex Formatters like the new List-App provides multiple char need to be encoded in order to set the value. The Fix does a full html-encoding of the Formatter string.
=> All COntent of the Field needs proper HtmlEncode not only &

Core/ProvisioningEngineTokens.md
| Related issues?  | #2101 
Updated documentation to refer the Title instead of the name. I could not get the name to work, no matter what I tried and after 1 hour gave up and switched to the Title - worked perfectly
Not really solving the issue, but hopefully preventing others from falling into the same mistake of trying to use the name.
=> Update provisioning token apppackageid description

Core/OfficeDevPnP.Core/Pages/ClientSidePage.cs
The TwoColumnRightVerticalSection and TwoColumnLeftVerticalSection where wrong because the compare for ColumnFactor was done with Col 1 instead of Col 0. As a result we would get 1/3 and 2/3 instead of 2/3 and 1/3 Layout with Vertical Section.
=> Fix Layout dedection for TwoColumnRightVerticalSection and TwoColumnLeftVerticalSection

Core/OfficeDevPnP.Core/Extensions/FileFolderExtensions.cs
Ensure Folder will fail with Foldernames containg + in the Name like "This + That" since UrlDecode in compare does remove the + char from the string and therefore will not detect the existing "This + That" folder correctly.
I could not really figure out from history why UrlDecode is needed after all - so i just added a direct name compare which was good enough for my cases.
=> Fix Folder Compare - not match if Foldername contains +
