pnp/PnP-Sites-Core

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectField.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs

Fixed issue with engine introducing duplicate child elements in field xml.

Fixed issue with engine introducing duplicate child elements

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectContentType.cs

Existing code was failing on adding fields to content type

Change to log fieldId, not field.Id as field.Id is not initialized at this point

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectRegionalSettings.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/XMLPnPSchemaV201508Formatter.cs

Implemented default field value parsing for list instances
Updated regional settings handling
Fixed parsing issue with 201508 formatter

201508 implementation

---

Core/OfficeDevPnP.Core.Tests/AppModelExtensions/SecurityExtensionsTests.cs
Core/OfficeDevPnP.Core.Tests/Framework/ObjectHandlers/ObjectFilesTests.cs
Core/OfficeDevPnP.Core/AppModelExtensions/BrandingExtensions.cs
Core/OfficeDevPnP.Core/AppModelExtensions/FeatureExtensions.cs
Core/OfficeDevPnP.Core/AppModelExtensions/FieldAndContentTypeExtensions.cs
Core/OfficeDevPnP.Core/AppModelExtensions/FileFolderExtensions.cs
Core/OfficeDevPnP.Core/AppModelExtensions/ListExtensions.cs
Core/OfficeDevPnP.Core/AppModelExtensions/SecurityExtensions.cs
Core/OfficeDevPnP.Core/AppModelExtensions/TaxonomyExtensions.cs
Core/OfficeDevPnP.Core/AppModelExtensions/WebExtensions.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Connectors/SharePointConnector.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectFiles.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstanceDataRows.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectPages.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/TokenParser.cs
Core/OfficeDevPnP.Core/OfficeDevPnP.Core.csproj
Core/OfficeDevPnP.Core/Utilities/Deprecated/Utility.deprecated.cs
Core/OfficeDevPnP.Core/Utilities/Utility.cs

* Refactored usage of IsPropertyAvailable to use EnsureProperty
* Deprecated EnsureWeb and EnsureSite methods

Refactored usage of IsPropertyAvailable to use EnsureProperty

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs

When creating a view for a list through the CSOM it's not possible to provide `Url`. Usually SharePoint gets `Title` from `ViewCreationInformation` object and transforms it to url. The result is `All%20Items.aspx`. Things become even worse if I want view title in French `Tous les éléments` and url in English `AllItems.aspx`. View url becomes ugly `Tous%20les%20lments.aspx`. 
To workaround this, it is possible to setup title to be equal to url first (in order to force SharePont generate desired view url), then, when the view is added, we can update it with desired title.

Added ability to specify url for the list view.

---

Core/OfficeDevPnP.Core/AppModelExtensions/ExternalSharingExtensions.cs
Core/OfficeDevPnP.Core/OfficeDevPnP.Core.csproj

External sharing extensions for site or document sharing.

Added external sharing extensions.

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs

Small bug fixes on special list handling in export/import scenarios.

List provisioning bug fixes around Survey and Contact list handling.

---

Core/OfficeDevPnP.Core/CoreResources.Designer.cs
Core/OfficeDevPnP.Core/CoreResources.resx
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectSitePolicy.cs

Logging of the Site Policy is done when applied or when not found

Added logging for Site Policies in the provisioning engine

---

Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/XMLTemplateProvider.cs

Add support for XInclude/Fallback element and recursive XInclude parsing

xinclude fallback support and recursive parsing

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs

Changes as provided in PR # 112. Manually implemented due to conflicts

Updated for on-prem list creation

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs

Bug fixed with this pull request. Tested.

Proposed solution to Bug #165

---

Core/OfficeDevPnP.Core/AppModelExtensions/BrandingExtensions.cs

Prevents comparison of the ThemeEntity.MasterPage property if the property is null

Null check for Theme.MasterPage

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectField.cs

AddFieldAsXml does not validate default value for Taxonomy fields that results in situation when term item is not added to taxonomy hidden list and default value is not applied to items. It is also not possible to set correct WssId for the default field value at creation time, since there is client API to get Wss Id of the term. 
I've added routine to validate default value for taxomony fields (and set correct Wss Id for the value) after field is created or updated. It actually works only if you specify -1 as Wss Id for the value.

Provisioning - validate taxonomy field default value

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs

tested with pages library and works fine.

Proposal to Fix Issue #193

---

Core/OfficeDevPnP.Core/Framework/Provisioning/Model/DataRow.cs

Fixed bug #200

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/Extensions/SecurableObjectExtensions.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstanceDataRows.cs

Fixed a bug with List Instance Data Rows where role inheritance are broken even when there's no role assignments set for the data row

Fixed a bug with List Instance Data Rows where role inheritance are broken even when there's no role assignments set for the data row

---

Core/OfficeDevPnP.Core/AppModelExtensions/ListRatingExtensions.cs
Core/OfficeDevPnP.Core/Enums/VotingExperience.cs

Added a new VoteExperience type, "None". If VotingExperience is set to
None, Ratings for the list are disabled.

Functionality to disable list ratings

---

Core/OfficeDevPnP.Core/AppModelExtensions/SecurityExtensions.cs

Extend role assignment extraction process to even deeper level so that resources with unique permission at those levels could be reached as well.

Extend role assignment extraction process to deeper level

---

Core/OfficeDevPnP.Core/AppModelExtensions/WebExtensions.cs
Core/OfficeDevPnP.Core/CoreResources.Designer.cs
Core/OfficeDevPnP.Core/CoreResources.resx

I added extension methods for easier usage of the `Web.RequestAccessEmail` property.

Added extensions for request access

---

Core/OfficeDevPnP.Core/AppModelExtensions/WebExtensions.cs

Adding compiler flag to exclude RequestAccessEmail from 15 builds... othewise the build fails

Adding compiler flag to exclude RequestAccessEmail from 15 builds

---

Core/OfficeDevPnP.Core/AppModelExtensions/FieldAndContentTypeExtensions.cs

Added a method to remove fields by Id.

Added RemoveFieldById()

---

Core/OfficeDevPnP.Core/AppModelExtensions/TaxonomyExtensions.cs

SetTaxonomyFieldDefaultValue field extension sets incorrect WssId for the value

fix for SetTaxonomyFieldDefaultValue incorrect WssId

---

Core/OfficeDevPnP.Core/AppModelExtensions/BrandingExtensions.cs

Fixed typo based on [issue 1296](https://github.com/OfficeDev/PnP/issues/1296).

Update to fix typo with property bag keys

---

Core/OfficeDevPnP.Core/AppModelExtensions/FieldAndContentTypeExtensions.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs

Added support for View ContentTypeId and DefaultForContentType attributes support

provisioning engine - view ContentTypeId and DefaultForContentType attributes support

---

Core/Documentation.md
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/Extensions/SecurableObjectExtensions.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs

See: https://github.com/OfficeDev/PnP-Sites-Core/pull/351

Applied changes suggested by larry-lau in PR #351

---

Core/OfficeDevPnP.Core/Utilities/Caml.cs

Implemented possibility to specify ViewFields and ViewScope.

CAML class improvements 

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectWorkflows.cs

See also: https://github.com/OfficeDev/PnP-Sites-Core/pull/431

Fixes Workflow duplication

---

Core/Documentation.md
Core/OfficeDevPnP.Core.Tests/AppModelExtensions/ListExtensionsTests.cs
Core/OfficeDevPnP.Core/AppModelExtensions/ListExtensions.cs
Core/OfficeDevPnP.Core/AppModelExtensions/PageExtensions.cs

Updated based on based on community contribution. Manual merge of following pull request from @rgueldenpfennig - https://github.com/OfficeDev/PnP-Sites-Core/pull/397. Original pull request closed due conflicts.

Updated page library resolving logic for publishing sites 

---

Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/XMLPnPSchemaV201512Formatter.cs

it's not causing a bug, but it's more coherent do it that way

Fixed issue 446

---

Core/OfficeDevPnP.Core/AppModelExtensions/FieldAndContentTypeExtensions.cs

Added method to delete a content type from the web by name. Will add byId later.

Added DeleteContentTypeByName

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

Issue and pull request template to be taken into use after June master merge.

Added Issue Template and PR template.

---

Core/OfficeDevPnP.Core/Utilities/TokenHelper.cs

Added method to TokenHelper to create valid S2S token from non-Windows claims identity. In case both SharePoint and provider hosted add-in are using non-Windows identity providers and High Trust authentication model is in use. Though it's pretty rare case I guess, well described by Kirk Evans here: https://blogs.msdn.microsoft.com/kaevans/2014/07/14/high-trust-sharepoint-apps-on-non-microsoft-platforms/

TokenHelper GetS2SClientContextWithClaimsIdentity

---

Core/OfficeDevPnP.Core.Tests/Framework/ObjectHandlers/ObjectLookupFieldsTests.cs
Core/OfficeDevPnP.Core.Tests/OfficeDevPnP.Core.Tests.csproj
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectLookupFields.cs

| Bug fix?        | yes 
| Related issues?  | Manual merge of PR #532 
Manual merge of PR #532 and small code change to the same PR.

Manual Merge of PR532

---

Core/OfficeDevPnP.Core/AppModelExtensions/FieldAndContentTypeExtensions.cs

| Related issues?  | fixes #555 and #153
Compared ContentTypeID based on current or parent ContentType.

Fix for issue #555 and PR #153

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectPublishing.cs

Fixed bug during extraction of page layouts.

Fix to publishing layout extration

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/TokenParser.cs

| Related issues?  | fixes #229
Replace listid with listid token, optionally scanning rootweb for lists in case of template extraction from rootweb.

Fix for lookup site columns referencing list in rootweb

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectWorkflows.cs

This pull request adds a retry when saving a new workflow definition as this is the area we are seeing the random "The underlying connection was closed: A connection that was expected to be kept alive was closed by the server." error appear.
We did look at extending ExecuteQueryRetry to catch the error but the WorkflowDefinition object needs to be re-created when retrying else it will fail to save correctly.
Also added an ExecuteQueryRetry after publishing the definition as it was missing and is required.

Added catch and retry for connection error when saving new Workflow Definitons

---

Core/OfficeDevPnP.Core.Tests/AppModelExtensions/BrandingExtensionsTests.cs
Core/OfficeDevPnP.Core/AppModelExtensions/BrandingExtensions.cs
Core/OfficeDevPnP.Core/CoreResources.Designer.cs
Core/OfficeDevPnP.Core/CoreResources.resx
Core/OfficeDevPnP.Core/OfficeDevPnP.Core.csproj
Core/OfficeDevPnP.Core/Resources/PnP-Responsive-CustomActionScript.js
Core/OfficeDevPnP.Core/Resources/PnP-Responsive-UI.js
Core/OfficeDevPnP.Core/Resources/PnP-Responsive-UI_CSS.css
Core/OfficeDevPnP.Core/Resources/Responsive.UI.Infrastructure.xml
Core/OfficeDevPnP.Core/Resources/Responsive.UI.Template.xml

Added web extension method to enable and disable responsive UI

Added Enable and DisableResponsiveUI extension methods

---

Core/OfficeDevPnP.Core/CoreResources.Designer.cs
Core/OfficeDevPnP.Core/CoreResources.resx
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/SiteToTemplateConversion.cs

Fix of a reference to a deprecated property in the Provisioning Engine.

Changed PersistComposedLookFiles into PersistBrandingFiles

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectSiteSecurity.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/TokenDefinitions/RoleDefinitionToken.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/TokenParser.cs
Core/OfficeDevPnP.Core/OfficeDevPnP.Core.csproj

Fixes role definition issue where source site language is different from target site language.

Tokenization for OOTB roledefinitions

---

Core/OfficeDevPnP.Core/AppModelExtensions/WorkflowExtensions.cs

Added extension methods to start a new workflow instance for an item or a web site.

Added extension methods to start a new workflow instance.

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/TokenDefinitions/AuthenticationRealmToken.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/TokenParser.cs
Core/OfficeDevPnP.Core/OfficeDevPnP.Core.csproj

Added Authentication Realm token to provisioning templates.

Added Authentication Realm token

---

Core/OfficeDevPnP.Core/AppModelExtensions/FileFolderExtensions.cs

Updates some comments in method signatures.

Modified comments around Folder to Document Set conversion methods.

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectExtensibilityHandlers.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ProvisioningTemplateApplyingInformation.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/SiteToTemplateConversion.cs

Added the capability to provide ExtensibilityHandlers while provisioning a template.

Added support for ExtensibilityHandlers while provisioning a template.

---

Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/ProvisioningSchema-2015-12.extensions.cs

Fixes a wrong behavior of the serializer when there is a field default value that is NULL.

Fixed wrong behavior with empty default values for fields.

---

Core/OfficeDevPnP.Core/Framework/Provisioning/Connectors/OpenXML/Model/PnPFileInfo.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Connectors/OpenXML/Model/PnPFileMap.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Connectors/OpenXML/Model/PnPInfo.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Connectors/OpenXML/PnPPackage.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Connectors/OpenXML/PnPPackageHelper.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Connectors/OpenXMLConnector.cs
Core/OfficeDevPnP.Core/OfficeDevPnP.Core.csproj

This PR fixes an issue with OpenXML file names inside the package.

OpenXML .PnP Connector: changed support for file names

---

Core/OfficeDevPnP.Core/AppModelExtensions/WorkflowExtensions.cs

Added the capability to return the GUID of a new workflow instance through the StartWorkflowInstance extension methods.

Added return value to StartWorkflowInstance methods.

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectTermGroups.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/XMLPnPSchemaV201605Formatter.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/XMLTemplateProvider.cs

| Related issues?  | issue while compiling on SP2013, SP2016
Just to fix an issue related to compilation of core with SP2013 and SP2016.

Schema201605

---

Core/OfficeDevPnP.Core/Framework/Provisioning/Connectors/OpenXMLConnector.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectContentHandlerBase.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectFiles.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectWorkflows.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/SiteToTemplateConversion.cs

This PR includes some important fixes for the SPD workflows object handler. Now initiation forms are supported, as well as tasks, and actions that use lists which are not the target of the current workflow definition.

Fixed some bugs related to SPD workflows handling.

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectPageContents.cs

Fixed wrong behavior of HomePage extraction for webparts URLs

---

Core/OfficeDevPnP.Core/Framework/Provisioning/Model/ListInstance.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Model/ProvisioningTemplate.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectCustomActions.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/XMLPnPSchemaV201605Formatter.cs

| Related issues?  | fixes #511
Added the capability to support user custom actions at list instance level.

Added support for UserCustomAction items at list instance level.

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectCustomActions.cs

| Related issues?  | fixes #653
Added support for Enabled attribute for CustomAction objects. If Enabled=true and the CustomAction is new, it will be added. If Enabled=false and the CustomAction does not exist, nothing will happen. To remove a CustomAction there is the Remove boolean attribute.

Added support for Enabled property for CustomActions

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs

| Related issues?  | fixes #673 
Fixes the issue described in #673 .

Fixed issue with library versioning minor/major version

---

Core/OfficeDevPnP.Core/Framework/Provisioning/Model/Term.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectTermGroups.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/TokenDefinitions/SiteCollectionIdToken.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/TokenParser.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/XMLPnPSchemaV201605Formatter.cs
Core/OfficeDevPnP.Core/OfficeDevPnP.Core.csproj

| Related issues?  | fixes #458 and includes #591
Fixed a wrong behavior of the engine when extracting templates with taxonomy based navigation.

Added tokenization for taxonomy termsets for navigation + reused/deprecated terms.

---

Core/README.md

| Bug fix?        | yes?
|
Fixed typo in file "SAML authentication.md" url
Link for "SAML authentication.md" was returning 404

Typo in file URL

---

Core/OfficeDevPnP.Core/AppModelExtensions/WebExtensions.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectRetrieveTemplateInfo.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/ProvisioningSchema-2016-05.xsd

Correct behavior for extracting BaseSiteTemplate ID.

Fixed BaseSiteTemplate handling at template level.

---

Core/OfficeDevPnP.Core/CoreResources.Designer.cs
Core/OfficeDevPnP.Core/CoreResources.resx
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/SiteToTemplateConversion.cs

Added a warning when the target site base template ID doesn't match the source site's base template ID.

Added warning for not matching target site template

---

Core/OfficeDevPnP.Core.Tests/Framework/Functional/ComposedLookTest.cs
Core/OfficeDevPnP.Core.Tests/Framework/Functional/Templates/composedlook_add.xml
Core/OfficeDevPnP.Core.Tests/Framework/Functional/Validators/ComposedLookValidator.cs
Core/OfficeDevPnP.Core.Tests/OfficeDevPnP.Core.Tests.csproj

Hi Bert,
Added composed look validator code.
Thanks,
Raj

ComposedLook validator

---

Core/OfficeDevPnP.Core.Tests/Framework/Functional/SearchsettingTest.cs
Core/OfficeDevPnP.Core.Tests/Framework/Functional/Templates/searchsettings_site_add .xml
Core/OfficeDevPnP.Core.Tests/Framework/Functional/Templates/searchsettings_web_add.xml
Core/OfficeDevPnP.Core.Tests/Framework/Functional/Validators/SearchsettingsValidator.cs
Core/OfficeDevPnP.Core.Tests/OfficeDevPnP.Core.Tests.csproj

Hi Bert,
Added search settings validator code.
Thanks,
Raj

Search Settings validator

---

Core/OfficeDevPnP.Core.Tests/Framework/Functional/LocalizationTest.cs
Core/OfficeDevPnP.Core.Tests/Framework/Functional/Templates/core.en-us.resx
Core/OfficeDevPnP.Core.Tests/Framework/Functional/Templates/core.it-it.resx
Core/OfficeDevPnP.Core.Tests/Framework/Functional/Templates/localization_add.xml
Core/OfficeDevPnP.Core.Tests/Framework/Functional/Validators/LocalizationValidator.cs
Core/OfficeDevPnP.Core.Tests/OfficeDevPnP.Core.Tests.csproj

Hi Bert,
Added localization validator code
Thanks,
Raj

Localization test

---

Core/OfficeDevPnP.Core/AuthenticationManager.cs
Core/OfficeDevPnP.Core/OfficeDevPnP.Core.csproj

Added ability to set icon for weblogin form

Added ability to set icon for weblogin form

---

Core/OfficeDevPnP.Core/AppModelExtensions/TenantExtensions.cs
Core/OfficeDevPnP.Core/Entities/SiteEntity.cs

Exposed the site lock state information through the LockState property on SiteEntity

Added the LockState property to SiteEntity

---

Core/OfficeDevPnP.Core.Tests/OfficeDevPnP.Core.Tests.csproj
Core/OfficeDevPnP.Core.Tests/Utilities/WebParts/WebPartPostProcessorFactoryTests.cs
Core/OfficeDevPnP.Core.Tests/Utilities/WebParts/XsltWebPartPostProcessorTests.cs
Core/OfficeDevPnP.Core/AppModelExtensions/PageExtensions.cs
Core/OfficeDevPnP.Core/OfficeDevPnP.Core.csproj
Core/OfficeDevPnP.Core/Utilities/WebParts/IWebPartPostProcessor.cs
Core/OfficeDevPnP.Core/Utilities/WebParts/Processors/PassThroughProcessor.cs
Core/OfficeDevPnP.Core/Utilities/WebParts/Processors/XsltWebPartPostProcessor.cs
Core/OfficeDevPnP.Core/Utilities/WebParts/Schema/WebPart.v3.cs
Core/OfficeDevPnP.Core/Utilities/WebParts/Schema/WebPart.v3.xsd
Core/OfficeDevPnP.Core/Utilities/WebParts/WebPartPostProcessorFactory.cs

| Related issues?  | Closes #584

Added support for dynamically updating XsltListViewWebPart 

---

Core/OfficeDevPnP.Core/AppModelExtensions/FieldAndContentTypeExtensions.cs

Added and extension method for ContentType to check if a field exists within a content type by name.

Added FieldExistsByNameInContentType

---

Core/OfficeDevPnP.Core/AppModelExtensions/WebExtensions.cs

Load the collection of webs (parentWeb.Webs) before performing the query.

Fixed WebExistsByTitle

---

Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/ProvisioningSchema-2016-05.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/ProvisioningSchema-2016-05.xsd

Fix for https://github.com/OfficeDev/PnP-Provisioning-Schema/issues/114

---

Core/OfficeDevPnP.Core/AppModelExtensions/BrandingExtensions.cs

| Related issues?  | --
Fixes a bug related to responsive UI with an infrastructural site collection.

Fixed bug in the EnableResponsiveUI extension method.

---

Core/OfficeDevPnP.Core/AppModelExtensions/FieldAndContentTypeExtensions.cs

Added search in site hierarchy when removing content type from list

---

Core/OfficeDevPnP.Core/AppModelExtensions/ListExtensions.cs

Fix for issue as mentioned in #163

Fixed issue with SetDefaultColumnValues

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs

Do not set enable attachments in case of PictureLibrary

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/TokenDefinitions/MasterPageCatalogToken.cs

Merged code from PR #640

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstanceDataRows.cs

Added support for multi value user and lookup fields so that data can be provisioned from the template.

Added multi value user and lookup fields

---

Core/OfficeDevPnP.Core.Tests/Framework/ExtensibilityCallOut/ExtensibilityTests.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectExtensibilityHandlers.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/TokenDefinitions/MasterPageCatalogToken.cs

Fixed some bugs

---

Core/OfficeDevPnP.Core/AppModelExtensions/FileFolderExtensions.cs

Proposed fix for EnsureFolderPath extension method.

---

Core/OfficeDevPnP.Core/AppModelExtensions/PageExtensions.cs

Allows to export none-exportable webpart XML and does not use the webservice anymore in SPO scenarios, resulting in a support for app only contexts.

Implemented native CSOM webpart export for SPO

---

Core/OfficeDevPnP.Core/AppModelExtensions/PageExtensions.cs

Code cleanup

---

Core/OfficeDevPnP.Core/AppModelExtensions/BrandingExtensions.cs
Core/OfficeDevPnP.Core/AppModelExtensions/ClientContextExtensions.cs
Core/OfficeDevPnP.Core/AppModelExtensions/ClientObjectExtensions.cs
Core/OfficeDevPnP.Core/AppModelExtensions/ExternalSharingExtensions.cs
Core/OfficeDevPnP.Core/AppModelExtensions/FeatureExtensions.cs
Core/OfficeDevPnP.Core/AppModelExtensions/FieldAndContentTypeExtensions.cs
Core/OfficeDevPnP.Core/AppModelExtensions/FileFolderExtensions.cs
Core/OfficeDevPnP.Core/AppModelExtensions/InformationManagementExtensions.cs
Core/OfficeDevPnP.Core/AppModelExtensions/ListExtensions.cs
Core/OfficeDevPnP.Core/AppModelExtensions/ListRatingExtensions.cs
Core/OfficeDevPnP.Core/AppModelExtensions/NavigationExtensions.cs
Core/OfficeDevPnP.Core/AppModelExtensions/PnPClientContext.cs
Core/OfficeDevPnP.Core/AppModelExtensions/ProvisioningExtensions.cs
Core/OfficeDevPnP.Core/AppModelExtensions/RecordsManagementExtensions.cs
Core/OfficeDevPnP.Core/AppModelExtensions/SecurityExtensions.cs
Core/OfficeDevPnP.Core/AppModelExtensions/TaxonomyExtensions.cs
Core/OfficeDevPnP.Core/AppModelExtensions/TenantExtensions.cs
Core/OfficeDevPnP.Core/AppModelExtensions/WebExtensions.cs

Code cleanup and simplification

---

Core/OfficeDevPnP.Core/AppModelExtensions/BrandingExtensions.cs

Now supports the full site collection, or just a subsite.

Changed behavior of EnableResponsiveUI and DisableResponsiveUI

---

Core/OfficeDevPnP.Core.Tests/Framework/Functional/FilesTests.cs
Core/OfficeDevPnP.Core.Tests/Framework/Functional/PagesTests.cs
Core/OfficeDevPnP.Core.Tests/Framework/Functional/SecurityTests.cs
Core/OfficeDevPnP.Core.Tests/Framework/Functional/SitePolicyTests.cs
Core/OfficeDevPnP.Core.Tests/Framework/Functional/Templates/files_add.xml
Core/OfficeDevPnP.Core.Tests/Framework/Functional/Templates/pages_add.xml
Core/OfficeDevPnP.Core.Tests/Framework/Functional/Templates/security_add.xml
Core/OfficeDevPnP.Core.Tests/Framework/Functional/Templates/sitepolicy_add.xml
Core/OfficeDevPnP.Core.Tests/Framework/Functional/Templates/workflows_add.xml
Core/OfficeDevPnP.Core.Tests/Framework/Functional/Validators/FilesValidator.cs
Core/OfficeDevPnP.Core.Tests/Framework/Functional/Validators/PagesValidator.cs
Core/OfficeDevPnP.Core.Tests/Framework/Functional/Validators/SecurityValidator.cs
Core/OfficeDevPnP.Core.Tests/Framework/Functional/Validators/SitePolicyValidator.cs
Core/OfficeDevPnP.Core.Tests/Framework/Functional/Validators/WorkflowValidator.cs
Core/OfficeDevPnP.Core.Tests/Framework/Functional/WorkflowsTests.cs
Core/OfficeDevPnP.Core.Tests/OfficeDevPnP.Core.Tests.csproj

Hi Bert,
We have added security and site policy validator to the PnP site core solution.
Thanks and Regards,
Srinu Tamada

Security and Site Policy validations

---

Core/OfficeDevPnP.Core/Framework/Graph/UnifiedGroupsUtility.cs

| Related issues?  | --
Just small fixes to the Unified Group utility methods

Small fixes to the Unified Group utility methods.

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectHandlerBase.cs

| Related issues?  | fixes #828
Fixes incorrect tokenization in calculated fields when created as site columns and multiple fieldrefs pointing to the same field are present in the field CAML.

Fixes issue as mentioned in issue #828

---

Core/OfficeDevPnP.Core/Framework/Graph/UnifiedGroupsUtility.cs

Made a 5 sec delay while creating a Unified Group

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs

| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| Related issues? | n/a |
When a list containing a localization token is created (Eg. {res:List_MyList_Title}), that token is added as value to the ListId token instead of the Title (and translated titles).
A ListId token is now added with the correct Title. The same is changed for ListUrl token.

ListId token fix

---

Core/OfficeDevPnP.Core/Utilities/JsonUtility.cs

| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| Related issues? | Performance improvements to json serialization/de-serialization |
Performance improvements to json serialization/de-serialization

Performance improvements to json serialization/de-serialization

---

Core/OfficeDevPnP.Core.Tests/Framework/Functional/LocalizationTest.cs
Core/OfficeDevPnP.Core.Tests/Framework/Functional/Templates/LocalizationPage2.aspx
Core/OfficeDevPnP.Core.Tests/Framework/Functional/Templates/core.en-us.resx
Core/OfficeDevPnP.Core.Tests/Framework/Functional/Templates/core.nl-nl.resx
Core/OfficeDevPnP.Core.Tests/Framework/Functional/Templates/localization_add.xml
Core/OfficeDevPnP.Core.Tests/Framework/Functional/Validators/LocalizationValidator.cs
Core/OfficeDevPnP.Core.Tests/OfficeDevPnP.Core.Tests.csproj
Core/OfficeDevPnP.Core/AppModelExtensions/PageExtensions.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/Extensions/WebPartLocalizationExtensions.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectFiles.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectPages.cs
Core/OfficeDevPnP.Core/OfficeDevPnP.Core.csproj

Added support to localize web part titles using resx files utilizing the approach mentioned by Alexey Sadomov at [http://sadomovalex.blogspot.no/2015/09/localize-web-part-titles-via-client.html](http://sadomovalex.blogspot.no/2015/09/localize-web-part-titles-via-client.html)

Added localization support for web part titles

---

Core/OfficeDevPnP.Core/Resources/SP-Responsive-UI.js

Fixed some missing semicolons in code.

---

Core/OfficeDevPnP.Core/AppModelExtensions/PageExtensions.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectPageContents.cs

| Related issues?  | fixes #753

Fixed bug #753

---

Core/OfficeDevPnP.Core.Tests/AppModelExtensions/BrandingExtensionsTests.cs
Core/OfficeDevPnP.Core.Tests/AppModelExtensions/FeatureExtensionsTests.cs
Core/OfficeDevPnP.Core.Tests/AppModelExtensions/ListRatingExtensionTest.cs
Core/OfficeDevPnP.Core.Tests/AppModelExtensions/StructuralNavigationExtensionsTests.cs
Core/OfficeDevPnP.Core.Tests/AppModelExtensions/WebExtensionsTests.cs
Core/OfficeDevPnP.Core/Constants.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/BaseTemplates/BaseTemplateManager.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectPublishing.cs

| Related issues?  | no issues, just refactoring
See if you like this Constants refactoring of feature ID's, not really an improvement but a cosmetic fix for consistency.
Everything that was public is marked as Obsolete rather than deleted for backwards compatibility.

Refactored feature id constants and changed to PascalCase

---

Core/OfficeDevPnP.Core/AppModelExtensions/BrandingExtensions.cs

| Related issues?  | fixes #92

Fixed bug described in issue #92.

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectContentType.cs

| Related issues?  | fixes #235

Fixed issue #235

---

Core/OfficeDevPnP.Core.Tests/Framework/Functional/Templates/core.en-us.resx
Core/OfficeDevPnP.Core.Tests/Framework/Functional/Templates/core.nl-nl.resx
Core/OfficeDevPnP.Core.Tests/Framework/Functional/Templates/localization_add.xml
Core/OfficeDevPnP.Core.Tests/Framework/Functional/Validators/LocalizationValidator.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/Extensions/LocalizationExtensions.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs
Core/OfficeDevPnP.Core/OfficeDevPnP.Core.csproj

Added support to localize list view titles, with same approach as used for web part titles.
Renamed WebPartLocalizationExtensions to LocalizationExtensions.

Added localization support to list views

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstanceDataRows.cs

I found that with the current implementation it is not possible to provision listitems with recurring dates to a calender list. The reason is that the provisioning framework performs a listitem.Update() after every single field update which in this case triggers causes an exception because the listitem fields depend on each other. I changed the code to update the listitem only once for every DataRow entry.
This is the exception:
`Microsoft.SharePoint.Client.ServerException occurred
HResult=0x80131500
Message=Invalid data has been used to update the list item. The field you are trying to update may be read only. …

Bugfix: Do not update ListItem after every field change

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs

Added support for View column aggregations

---

Core/OfficeDevPnP.Core/AppModelExtensions/WebExtensions.cs
Core/OfficeDevPnP.Core/CoreResources.Designer.cs
Core/OfficeDevPnP.Core/CoreResources.resx
Core/OfficeDevPnP.Core/OfficeDevPnP.Core.csproj
Core/OfficeDevPnP.Core/packages.config

This PR contains a new method called CreatePublishingImageRendition. This new method allows for the simple creation of unique Image Renditions in SharePoint. The new Image Rendition's Name must be unique; if it already exists, it will not be created.

Pnp ps publishingimagerenditions

---

Core/OfficeDevPnP.Core/AppModelExtensions/PublishingExtensions.cs

Added RemovePublishingImageRendition and GetPublishingImageRendition extensions

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs

Fix for wrong handling of ID property of views.

Small fix to List View ID token parser handling.

---

Core/OfficeDevPnP.Core.Tests/Framework/Functional/Templates/termgroup_delta_1605_1.xml
Core/OfficeDevPnP.Core.Tests/Framework/Functional/TermGroupTests.cs
Core/OfficeDevPnP.Core.Tests/OfficeDevPnP.Core.Tests.csproj

Hi Bert,
Added term groups contributors and managers test
Thanks,
Raj

Term Group 1605 changes

---

Core/OfficeDevPnP.Core.Tests/Framework/Functional/NavigationTests.cs
Core/OfficeDevPnP.Core.Tests/Framework/Functional/Templates/navigation_add.xml
Core/OfficeDevPnP.Core.Tests/Framework/Functional/Templates/navigation_add2.xml
Core/OfficeDevPnP.Core.Tests/Framework/Functional/Templates/navigation_add3.xml
Core/OfficeDevPnP.Core.Tests/Framework/Functional/Validators/NavigationValidator.cs
Core/OfficeDevPnP.Core.Tests/OfficeDevPnP.Core.Tests.csproj

Hi Bert,
Added navigation functional test files.
Thanks,
Raj

Navigation test

---

Core/OfficeDevPnP.Core.Tests/Framework/Providers/XMLProvidersTests.cs
Core/OfficeDevPnP.Core.Tests/Resources/Templates/ProvisioningTemplate-2016-05-Sample-02.xml
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectNavigation.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/XMLPnPSchemaV201605Formatter.cs

| Related issues?  | fixes #969

Updated navigation handling to accept empty structuralnavigation nodes.

---

Core/OfficeDevPnP.Core/AppModelExtensions/InformationManagementExtensions.cs

Added methods to programatically check if a site is closed or not, and to close/open the site if it has a site policy defined.

Added IsSiteClosed, CloseSite, OpenSite extension methods

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectField.cs

If not, code breaks in the WriteMessage parser
Bug fix for formatting the refactored Message line in ObjectField

Check for empty and white space and not just null

---

Core/OfficeDevPnP.Core/AppModelExtensions/FileFolderExtensions.cs
Core/OfficeDevPnP.Core/AppModelExtensions/ListExtensions.cs
Core/OfficeDevPnP.Core/AppModelExtensions/NavigationExtensions.cs
Core/OfficeDevPnP.Core/AppModelExtensions/WebExtensions.cs

Which can prevent an additional round trip

Added optional Expression parameters to allow retrieval of properties

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectContentType.cs

The code only ordered fields on new content types, not on updated ones.

Support update field order on existing content types

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectTermGroups.cs

Added support for normalized names in taxonomy items.

---

Assemblies/readme.md

[ X ] Documentation
Clean up ensuring proper information are in README markdown file for Assemblies folder

Cleaning and updating Assemblies readme

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectSupportedUILanguages.cs

Added reload of SupportedUILanguageIds after it's set in the ObjectHandler. This avoids that the  property is dirty when we later ensures the property in ObjectListInstance.

Added reload of SupportedUILanguageIds

---

Core/OfficeDevPnP.Core/CoreResources.Designer.cs
Core/OfficeDevPnP.Core/CoreResources.resx
Core/OfficeDevPnP.Core/Extensions/ListExtensions.cs

Allow setting default column value programatically for people fields using the id and ident from the hidden userinfo list on the current site.
Single value field: *1;#Foo Bar*
Multi value field: *1;#Foo Bar;#2;#Bar Foo*
The name can be either title, e-mail or login

Set default column person

---

Core/OfficeDevPnP.Core/Extensions/ListExtensions.cs

Added extension method to load the default field values for the folders of a library.

Added method to get column defaults from a library

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/TokenDefinitions/TokenDefinition.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/TokenParser.cs

Avoid additional call to GetTokens in TokenParser
Avoid additional call to GetTokens in TokenParser

TokenParser optimization

---

Core/OfficeDevPnP.Core/Framework/Graph/UnifiedGroupsUtility.cs

Add support to update an existing group with new owners, members or set the group to be public/private.
Changes added to support features in Set-PnPUnifiedGroup

Set properties on an existing unified group

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectSiteSecurity.cs

| New feature?    | no?
| New sample?      | no?
When exporting site security the template cannot be applied to a new site collection if users are disabed in Azure AD.
Eg. a user within a site group is disabled because he left the company. When applying the template the site groups are created and the users are added to the group. However when the framework is trying to add the disabled user, EnsureUser will throw an exception and stop further progress.
This change logs a Warning instead and continues the progress.
EnsureUser will also fail for External Users if they don't already exist on the site.
A check has been added skipping external user if doesn't exist in SiteUsers.

Handle EnsureUser exceptions

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectContentType.cs

This PR fixes an issue where Sealed content types are updated.
This change only allows sealed content types to updated if they're changed not to be sealed.

Ensure sealed content type is not updated

---

Core/OfficeDevPnP.Core/Extensions/ListExtensions.cs

| Improvement    | yes
Add support for more field types: Boolean, DateTime, Number, Currency
Refactored and cleaned up existing code for readability.

Support more field types on default columns

---

Core/OfficeDevPnP.Core/AppModelExtensions/ListExtensions.cs
Core/OfficeDevPnP.Core/CoreResources.Designer.cs
Core/OfficeDevPnP.Core/CoreResources.resx
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectNavigation.cs

| Related issues?  | fixes #1079
Fixed issue related to setting global navigation to inherit

Fixed issue related to setting global navigation to inherit #1079

---

Core/OfficeDevPnP.Core/CoreResources.Designer.cs
Core/OfficeDevPnP.Core/CoreResources.resx
Core/OfficeDevPnP.Core/Framework/Graph/PnPHttpProvider.cs
Core/OfficeDevPnP.Core/Framework/Graph/UnifiedGroupsUtility.cs

| Improvement?        | yes
* Changed Thread.Sleep to Task.Await to avoid busy sleep
* Added try/catch blocks to get Graph errors out in the error stream since we are doing async calls

Optimize busy wait and better error handling

---

Core/OfficeDevPnP.Core/AppModelExtensions/JavaScriptExtensions.cs
Core/OfficeDevPnP.Core/Resources/SP-Responsive-UI.js

| Related issues?  | [#109](https://github.com/SharePoint/PnP-Tools/issues/109)
Remove the minimal and maximal scale fixed by the meta tag viewport.

Scale viewport

---

Core/OfficeDevPnP.Core/Framework/Graph/UnifiedGroupsUtility.cs

| Improvement?        | yes
Added try/catch on all public functions to log service errors. Very useful when using PnP posh, as you can more clearly see what the actual error is.
`C:\Users\miksv> New-PnPUnifiedGroup -DisplayName "Foo" -Description "Foo" -MailNickname footest -Owners miksvenson@tenant.onmicrosoft.com
powershell.exe Error: 0 : 2017-03-09 12.55.40.7791      [OfficeDevPnP.Core]     [0]     [Error] Graph call returned the following error: One or more properties contains invalid values..   0ms`

Added try/catch with Logging on all calls

---

Core/OfficeDevPnP.Core.Tests/Framework/Providers/XMLProvidersTests.cs
Core/OfficeDevPnP.Core.Tests/TestCommon.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/PnPSerializationScope.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/Serializers/ContentTypesSerializer.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/XmlPnPSchemaBaseSerializer.cs
Core/OfficeDevPnP.Core/OfficeDevPnP.Core.csproj

ContentType serializer and fix for issue with PnPSerializationScope.

Contenttype serializer

---

Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/PnPObjectsMapper.cs

Convert source value to string if destination property is of string type

default conversion to string

---

Core/OfficeDevPnP.Core.Tests/Framework/Providers/XMLProvidersTests.cs
Core/OfficeDevPnP.Core.Tests/Resources/Templates/ProvisioningTemplate-2016-05-Sample-03.xml
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/PnPObjectsMapper.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/Resolvers/DocumentSetTemplateFromModelToSchemaTypeResolver.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/Resolvers/ExpressionCollectionValueResolver.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/Resolvers/ExpressionTypeResolver.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/Resolvers/ExpressionValueResolver.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/Resolvers/FromBasePermissionsToStringValueResolver.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/Resolvers/FromStringToBasePermissionsValueResolver.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/Resolvers/FromStringToEnumValueResolver.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/Resolvers/PropertyObjectTypeResolver.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/Resolvers/ResolversExtensions.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/Resolvers/RoleAssigmentsFromSchemaToModelTypeResolver.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/Resolvers/XmlAnyFromModeToSchemalValueResolver.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/Serializers/ContentTypesSerializer.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/Serializers/CustomActionsSerializer.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/Serializers/FilesSerializer.cs
Core/OfficeDevPnP.Core/OfficeDevPnP.Core.csproj

Added CustomActions serializer, fixes for ContentTypes serializer, enhanced serializers tests. Added some generic resolver as well: EnumFromStrings, Expressions resolvers (to resolve values/types with lambda expresions), XElement to Any.
Fixes in PnPObjectMapper.MapProperties - recursive parameter not passed to child function calls.

New serializers

---

Core/OfficeDevPnP.Core.Tests/Framework/Providers/XMLProvidersTests.cs
Core/OfficeDevPnP.Core.Tests/Resources/Templates/ProvisioningTemplate-2016-05-Sample-03.xml
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/Resolvers/CollectionFromModelToSchemaTypeResolver.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/Resolvers/ExpressionTypeResolver.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/Resolvers/ExpressionValueResolver.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/Resolvers/FromArrayToDictionaryValueResolver.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/Resolvers/FromDictionaryToArrayValueResolver.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/Resolvers/FromNullableToSpecifiedValueResolver.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/Resolvers/FromStringToGuidValueResolver.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/Resolvers/PropertyObjectTypeResolver.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/Resolvers/RoleAssigmentsFromModelToSchemaTypeResolver.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/Resolvers/RoleAssigmentsFromSchemaToModelTypeResolver.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/Serializers/ComposedLookSerializer.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/Serializers/CustomActionsSerializer.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/Serializers/DirectoriesSerializer.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/Serializers/FilesSerializer.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/Serializers/PagesSerializer.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/Serializers/TermGroupsSerializer.cs
Core/OfficeDevPnP.Core/OfficeDevPnP.Core.csproj

Directories and Pages serializers, unit tests also for Taxonomy serializer and some fixes

More new serializers

---

Core/OfficeDevPnP.Core.Tests/Framework/Providers/XMLProvidersTests.cs
Core/OfficeDevPnP.Core.Tests/Resources/Templates/ProvisioningTemplate-2016-05-Sample-03.xml
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/Resolvers/ExpressionValueResolver.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/Resolvers/PageLayoutsFromModelToSchemaTypeResolver.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/Resolvers/PageLayoutsFromSchemaToModelTypeResolver.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/Serializers/AddinsSerializer.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/Serializers/ComposedLookSerializer.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/Serializers/ContentTypesSerializer.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/Serializers/CustomActionsSerializer.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/Serializers/DirectoriesSerializer.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/Serializers/ExtensibilityHandlersSerializer.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/Serializers/FilesSerializer.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/Serializers/PagesSerializer.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/Serializers/PublishingSerializer.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/Serializers/TemplateBasePropertiesSerializer.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/Serializers/WebSettingsSerializer.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/Serializers/WorkflowsSerializer.cs
Core/OfficeDevPnP.Core/OfficeDevPnP.Core.csproj

Final portion of serializers and tests

Even more new serializer

---

Core/OfficeDevPnP.Core/Extensions/PageExtensions.cs

| Related issues?  | fixes #997 
This PR contains another approach of fixing related issue. For previous discussion please refer to PR #998 
It doesn't change signature for public interfaces but uses clone of the ClientContext instead.

Added new fix for xslt web parts adding on subweb issue.

---

Core/OfficeDevPnP.Core/Utilities/MailUtility.cs

| Improvement?        | yes
Added async methods for sending emails in MailUtility using async/await (currently only old fashioned asynchronous methods are available) and improved code.

Added async methods for sending emails in MailUtility

---

Core/OfficeDevPnP.Core.Tests/Framework/Providers/XMLProvidersTests.cs
Core/OfficeDevPnP.Core.Tests/Resources/Templates/ProvisioningTemplate-2016-05-Sample-03.xml
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/Resolvers/CalendarTypeFromSchemaToModelValueResolver.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/Resolvers/ExpressionCollectionValueResolver.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/Resolvers/ExpressionTypeResolver.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/Resolvers/TermSetFromModelToSchemaTypeResolver.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/Resolvers/WorkHourFromSchemaToModelValueResolver.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/Serializers/ListInstancesSerializer.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/Serializers/NavigationSerializer.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/Serializers/PropertyBagPropertiesSerializer.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/Serializers/RegionalSettingsSerializer.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/Serializers/SecuritySerializer.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/Serializers/TemplateBasePropertiesSerializer.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/Serializers/TermGroupsSerializer.cs
Core/OfficeDevPnP.Core/OfficeDevPnP.Core.csproj

More unit test for XML fomatters refactoring. Following tests are failing:
- Deserialize regional settings
- Deserialize security
- Serialize list instances
- Serialize property bag entries
- Serialize regional settings
- Serialize template base properties
@PaoloPia could you please review?

More unit tests

---

Core/OfficeDevPnP.Core.Tests/App.config.sample
Core/OfficeDevPnP.Core.Tests/Authentication/HighTrustAuthenticationTests.cs
Core/OfficeDevPnP.Core.Tests/OfficeDevPnP.Core.Tests.csproj
Core/OfficeDevPnP.Core.Tests/TestCommon.cs
Core/OfficeDevPnP.Core/AuthenticationManager.cs
Core/OfficeDevPnP.Core/Utilities/TokenHelper.cs

Added support for high trust on premises authentication through a private certificate

High Trust support for on premises

---

Core/OfficeDevPnP.Core/Extensions/BrandingExtensions.cs
Core/OfficeDevPnP.Core/Extensions/ClientContextExtensions.cs
Core/OfficeDevPnP.Core/Extensions/ClientObjectExtensions.cs
Core/OfficeDevPnP.Core/Extensions/ExternalSharingExtensions.cs
Core/OfficeDevPnP.Core/Extensions/FieldAndContentTypeExtensions.cs
Core/OfficeDevPnP.Core/Extensions/FileFolderExtensions.cs
Core/OfficeDevPnP.Core/Extensions/JavaScriptExtensions.cs
Core/OfficeDevPnP.Core/Extensions/ListExtensions.cs
Core/OfficeDevPnP.Core/Extensions/NavigationExtensions.cs
Core/OfficeDevPnP.Core/Extensions/PageExtensions.cs
Core/OfficeDevPnP.Core/Extensions/PublishingExtensions.cs
Core/OfficeDevPnP.Core/Extensions/SearchExtensions.cs
Core/OfficeDevPnP.Core/Extensions/SecurityExtensions.cs
Core/OfficeDevPnP.Core/Extensions/TaxonomyExtensions.cs
Core/OfficeDevPnP.Core/Extensions/TenantExtensions.cs
Core/OfficeDevPnP.Core/Extensions/WebExtensions.cs
Core/OfficeDevPnP.Core/Extensions/WorkflowExtensions.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/BaseTemplates/BaseTemplateManager.cs

Hi Bert,
Added comments to microsoft.sharepoint.client namespace files. Please review and merge.
Thanks,
Raj

microsoft.sharepoint.client comments

---

Core/OfficeDevPnP.Core/Entities/AreaNavigationEntity.cs
Core/OfficeDevPnP.Core/Entities/DefaultColumnTermPathValue.cs
Core/OfficeDevPnP.Core/Entities/DefaultColumnTermValue.cs
Core/OfficeDevPnP.Core/Entities/ExternalUserEntity.cs
Core/OfficeDevPnP.Core/Entities/FieldCreationInformation.cs
Core/OfficeDevPnP.Core/Entities/RoleAssignmentEntity.cs
Core/OfficeDevPnP.Core/Entities/SiteEntity.cs
Core/OfficeDevPnP.Core/Entities/StructuralNavigationEntity.cs
Core/OfficeDevPnP.Core/Entities/TaxonomyFieldCreationInformation.cs
Core/OfficeDevPnP.Core/Entities/ThemeEntity.cs
Core/OfficeDevPnP.Core/Entities/UnifiedGroupEntity.cs
Core/OfficeDevPnP.Core/Entities/UserEntity.cs
Core/OfficeDevPnP.Core/Entities/WebTemplateEntity.cs
Core/OfficeDevPnP.Core/Entities/WebhookNotification.cs
Core/OfficeDevPnP.Core/Entities/WebhookSubscription.cs
Core/OfficeDevPnP.Core/Entities/YammerGroup.cs
Core/OfficeDevPnP.Core/Entities/YammerUser.cs

Hi Bert,
Added comments to OfficeDevPnP.Core.Entities namespace files
Thanks,
Raj

OfficeDevPnP.Core.Entities comments

---

Core/OfficeDevPnP.Core/Extensions/ExceptionExtensions.cs
Core/OfficeDevPnP.Core/Extensions/SafeConvertExtensions.cs
Core/OfficeDevPnP.Core/Extensions/ValidationExtensions.cs
Core/OfficeDevPnP.Core/Utilities/Caml.cs
Core/OfficeDevPnP.Core/Utilities/CookieReader.cs
Core/OfficeDevPnP.Core/Utilities/CredentialManager.cs
Core/OfficeDevPnP.Core/Utilities/FileTokenCache.cs
Core/OfficeDevPnP.Core/Utilities/TokenHelper.cs
Core/OfficeDevPnP.Core/Utilities/UrlUtility.cs
Core/OfficeDevPnP.Core/Utilities/Utility.cs
Core/OfficeDevPnP.Core/Utilities/WebParts/IWebPartPostProcessor.cs
Core/OfficeDevPnP.Core/Utilities/WebParts/Processors/PassThroughProcessor.cs
Core/OfficeDevPnP.Core/Utilities/WebParts/Processors/XsltWebPartPostProcessor.cs
Core/OfficeDevPnP.Core/Utilities/WebParts/Schema/WebPart.v3.cs
Core/OfficeDevPnP.Core/Utilities/WebParts/WebPartPostProcessorFactory.cs
Core/OfficeDevPnP.Core/Utilities/XMLSerializer.cs
Core/OfficeDevPnP.Core/Utilities/YammerUtility.cs

Hi Bert,
Added comments to OfficeDevPnP.Core.Utilities and System namespace files.
Thanks,
Raj

Utilities and system comments

---

Core/OfficeDevPnP.Core/Diagnostics/ILogger.cs
Core/OfficeDevPnP.Core/Diagnostics/Log.cs
Core/OfficeDevPnP.Core/Diagnostics/LogConfigurationSection.cs
Core/OfficeDevPnP.Core/Diagnostics/LogEntry.cs
Core/OfficeDevPnP.Core/Diagnostics/LogLevel.cs
Core/OfficeDevPnP.Core/Diagnostics/PnPMonitoredScope.cs
Core/OfficeDevPnP.Core/Diagnostics/Tree/Enums.cs
Core/OfficeDevPnP.Core/Diagnostics/Tree/ITreeNode.cs
Core/OfficeDevPnP.Core/Diagnostics/Tree/ITreeNodeAware.cs
Core/OfficeDevPnP.Core/Diagnostics/Tree/ITreeNodeList.cs
Core/OfficeDevPnP.Core/Diagnostics/Tree/Tree.cs
Core/OfficeDevPnP.Core/Diagnostics/Tree/TreeNode.cs
Core/OfficeDevPnP.Core/Diagnostics/Tree/TreeNodeList.cs
Core/OfficeDevPnP.Core/Enums/BuiltInIdentity.cs
Core/OfficeDevPnP.Core/Enums/NavigationType.cs
Core/OfficeDevPnP.Core/Enums/SharePointPlatform.cs
Core/OfficeDevPnP.Core/Enums/StructuralNavigationSortBy.cs
Core/OfficeDevPnP.Core/Enums/StructuralNavigationSorting.cs
Core/OfficeDevPnP.Core/Enums/TimeZone.cs
Core/OfficeDevPnP.Core/Extensions/EnumerationExtensions.cs
Core/OfficeDevPnP.Core/IdentityModel/TokenProviders/ADFS/CertificateMixed.cs
Core/OfficeDevPnP.Core/IdentityModel/TokenProviders/ADFS/UsernameMixed.cs
Core/OfficeDevPnP.Core/IdentityModel/WSTrustBindings/CertificateWSTrustBinding.cs
Core/OfficeDevPnP.Core/IdentityModel/WSTrustBindings/UserNameWSTrustBinding.cs
Core/OfficeDevPnP.Core/IdentityModel/WSTrustBindings/WSTrustBindingBase.cs
Core/OfficeDevPnP.Core/Pages/ClientSidePageCanvas.cs
Core/OfficeDevPnP.Core/Pages/ClientSidePagesControlData.cs
Core/OfficeDevPnP.Core/WebAPI/WebAPIContextFilterAttribute.cs

Hi Bert,
Added comments to other namespace files. Please review and merge.
Thanks,
Raj

Other namespace file comments

---

Core/OfficeDevPnP.Core/Extensions/ListExtensions.cs

| Related issues?  |1282
Change defaultResourceFile in the method GetLocalizedString cmscore to osrvcore for support spanish language.

fix List_Pages_UrlName for spanish

---

Core/OfficeDevPnP.Core/Extensions/PageExtensions.cs

| Related issues?  | #1305
Small change to WebPart exporting to allow using current credentials.

Pass default credentials when no credential is supplied

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs

| Bug fix?        | Yes
Even if the latest 201705 schema includes the `NoCrawl` attribute, the code didn't applied it.
These PR adds missing code.

Missing NoCrawl property in list creation

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectFiles.cs

| Related issues?  | fixes #796
This PR includes a Proposal to fix issue #796 
What I'm doing is to catch the ServerException in the UploadFile method, and check the Error Code to just ignore the File if the error is "The file is already checked out". Otherwise, if follows the original logic.

Proposal to Fix issue #796

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs

If we are provisioning a Calendar, we ensure that it supports Recurrence
| Related issues?  | fixes #1104
If we are provisioning a Calendar, we ensure that it supports Recurrence

 Fixing the calendar recurrence option

---

Core/OfficeDevPnP.Core/Extensions/ListExtensions.cs

| Bug fix?        |  yes?
| New sample?      | no -
| Related issues?  | fixes #1156 
Fixes the problem with not including list title within the query, which causes problem for regular users (OOB Visitors' group members) to execute this code without getting Access Denied issue.

List title is now included in the GetListByTitle query

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectPages.cs

Trying to overwrite a page that is set as welcomepage for a web fails if the WelcomePage attribute is not defined in the same template. Reason for that is that ObjectPages.ProvisionObjects() relies on the WelcomePage property of the page model to detect if a page needs special handling.
For some update scenarios we do not want to touch the WelcomePage property.
I updated the method to not rely on the Page model but instead to check if the page to be updated is the welcome page by using the CSOM.
I realize I already made a similar pull request a while ago but failed to describe the error understandably.

Allow page that is set as welcome page to be overwritten

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectPageContents.cs

| Bug fix?        | yes?
| Related issues?  | fixes #1095
Ignoring welcome pages when they are views in a list as these pages are create as part of the lists.

Fixed #1095 by ignoring welcome pages that are list views

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectClientSidePages.cs
Core/OfficeDevPnP.Core/OfficeDevPnP.Core.csproj
Core/OfficeDevPnP.Core/Utilities/CanvasControl/CanvasControlPostProcessorFactory.cs
Core/OfficeDevPnP.Core/Utilities/CanvasControl/ICanvasControlPostProcessor.cs
Core/OfficeDevPnP.Core/Utilities/CanvasControl/Processors/ListControlPostProcessor.cs
Core/OfficeDevPnP.Core/Utilities/CanvasControl/Processors/PassThroughProcessor.cs

| Related issues?  | Includes #1333 
* Support token replacement in JsonControlData of client side web parts
* Support adding List web part based on list url only - for dynamic scenarios
Based the processing pattern on how xsltlistview wp are being processed.
@jansenbe let me know if you have any questions.

Support list by path and title

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs

| Related issues?  | fixes #1353
Little tweak to fix #1353.

Fix https://github.com/SharePoint/PnP-Sites-Core/issues/1353

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectSiteSecurity.cs

Groups in templates are processed as they are stored. That can lead to problem when Owner of the group is another yet unprocessed group in template. In this case apply template process crashes with error.
| Related issues?  | fixes #1377
Site groups are sorted out to respect ownership. Groups that are owners of other groups are processed prior groups that they own.

Sorting site groups during applying template process to respect group Ownership dependency

---

Core/OfficeDevPnP.Core/WebAPI/WebAPIHelper.cs

Basically copies the exsting RegisterWebAPIService() method but allows to use it with a HttpContextBase instance instead of a Page object not available in ASP.NET MVC (with Razor views) project

Adds extension to register WebAPI in ASP.NET MVC solutions instead of using Page object

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs

Fixed bug in provisioning template creation. When list view with null ListViewXml property is met, template creation process crashes with NullReference exception.

Fixed bug in provisioning template creation. 

---

Core/OfficeDevPnP.Core/AuthenticationManager.cs

| Related issues?  | fixes PnP PowerShell issue #1122
Adds support for authenticating with on-premises SharePoint farms published as non-claims aware applications via ADFS and Web Application Proxy (WAP).
Technically, the PR updates the **AuthenticationManager** class to also recognize the cookie **EdgeAccessCookie** issued by the WAP server. Before it only recognized the **FedAuth** and **rtFa** cookies.

Fixed PnP PowerShell issue #1122

---

Core/OfficeDevPnP.Core/ALM/AppManager.cs
Core/OfficeDevPnP.Core/Extensions/ClientContextExtensions.cs
Core/OfficeDevPnP.Core/OfficeDevPnP.Core.csproj
Core/OfficeDevPnP.Core/Sites/SiteCollection.cs
Core/OfficeDevPnP.Core/Utilities/RESTUtilities.cs
Core/OfficeDevPnP.Core/Utilities/Webhooks/WebhookUtility.cs

| Related issues?  | fixes #1411 
Fixes authentication issie when using ClientContext that has been obtained through weblogin.

Fixes Authentication when using through weblogin obtained clientcontext

---

Core/OfficeDevPnP.Core/Extensions/SiteExtensions.cs
Core/OfficeDevPnP.Core/Extensions/TenantExtensions.cs
Core/OfficeDevPnP.Core/Framework/Graph/GraphHttpClient.cs
Core/OfficeDevPnP.Core/Framework/Graph/Model/DirectorySetting.cs
Core/OfficeDevPnP.Core/Framework/Graph/Model/DirectorySettingTemplates.cs
Core/OfficeDevPnP.Core/Framework/Graph/Model/DirectorySettingValue.cs
Core/OfficeDevPnP.Core/OfficeDevPnP.Core.csproj

Added full support for Site Classification (activate, update, deactivate, get/set at site collection level)

Added support for Site Classification

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectNavigation.cs

Fixed setting Structural and StructuralLocal navigation.
* observed behavior: Navigtion settings in template were not set correctly on a publishing subsite.
`<pnp:Navigation>
<pnp:GlobalNavigation NavigationType="Structural" >
<pnp:StructuralNavigation RemoveExistingNodes="true" >
<pnp:NavigationNode Title="Documenten" Url="{site}/Documents/Forms/AllItems.aspx" />
</pnp:StructuralNavigation>
</pnp:GlobalNavigation>
<pnp:CurrentNavigation NavigationType="StructuralLocal">
<pnp:StructuralNavigation RemoveExistingNodes="true" >
<pnp:NavigationNode Title="Documenten" Url="{site}/Documents/Forms/AllItems.aspx" />
</pnp:StructuralNavigation> …

Allow structural navigation

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectCustomActions.cs

* Allow for tokens in `ClientSideComponentProperties`  (Line 82).
* Minor readability refactoring as I was editing the file.

Added parsing of tokens for ClientSideComponentProperties.

---

Core/OfficeDevPnP.Core/Extensions/ListExtensions.cs

This will support a PR I'll submit to PnP-PowerShell. I'd like the ability to create or update lists to hidden from the SharePoint UI.

Support ability to create new hidden lists

---

Core/OfficeDevPnP.Core/Extensions/ListExtensions.cs

| Enhancement/Bug fix?        | yes
| Related issues?  | fixes #1494 
When having many folders using the same field, the code loaded up the field for every single folder when parsing the existing settings. By adding a field name to field cache this made the code load one field one time only.
Also improved code to load the /Forms folder, not loading all folders, but access it directly. Reduces load time a lot when you have many folder in a library.
* Improved loading time of client_LocationBasedDefaults.html
* Added caching of Field
* Reduce loading terms from term store

Optimized default value for folder code

---

Core/OfficeDevPnP.Core/OfficeDevPnP.Core.csproj
Core/OfficeDevPnP.Core/Utilities/Cache/ICacheProvider.cs
Core/OfficeDevPnP.Core/Utilities/Cache/InMemoryCacheProvider.cs
Core/OfficeDevPnP.Core/Utilities/Cache/SimpleAspNetCacheProvider.cs
Core/OfficeDevPnP.Core/WebAPI/WebAPIContextCache.cs

Changes in WebAPIContextCache class to be able to specifiy a custom cache provider.
This will, for example, allow to implement a better distributed cache system for server farms or Azure WebApp instances

Web API Context CacheProvider

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstanceDataRows.cs

Fix missing call to token parser when querying for key column value.

Fix missing call to token parser when querying for key column value.

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/TokenParser.cs

| Related issues?  | fixes #1522 
A small fix to a bug referenced in #1522 and related to the TokenParser searching for apps in the AppCatalog.

Fix for issue #1522

---

Core/OfficeDevPnP.Core/Extensions/WebExtensions.cs

On premises compilation was broken due to O365 code. This PR adds conditional compilation

Broken on premise compilation

---

Core/OfficeDevPnP.Core/ALM/AppManager.cs

| Related issues?  | same as #1469 
Added PR again as i needed to update my fork
Currently you can either get all available apps or get an app by its ID. 
So, have "added support" to get an app by its title.
In the future, if and when we get API support to get an app by title, we can simply replace some code in the BaseGetAvailableAsync method without impacting the implementation outside.
PS - Would be great if we also have API support (some time in the future)  to get an app by its title, something along the lines of 
`/_api/web/tenantappcatalog/AvailableApps/GetByTitle`

Added support to get an app by its title

---

Core/OfficeDevPnP.Core/Extensions/TaxonomyExtensions.cs

Added useful extension method for working with Term Labels to ensure the specified label exists on a given Term

Term.EnsureLabel extension method

---

CHANGELOG.md
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstanceDataRows.cs

Updated to not update readonly fields and allow for setting null values

---

Core/OfficeDevPnP.Core/CoreResources.Designer.cs
Core/OfficeDevPnP.Core/CoreResources.resx
Core/OfficeDevPnP.Core/Entities/SiteEntity.cs
Core/OfficeDevPnP.Core/Entities/ThemeEntity.cs
Core/OfficeDevPnP.Core/Entities/WebhookNotification.cs
Core/OfficeDevPnP.Core/Entities/WebhookSubscription.cs
Core/OfficeDevPnP.Core/Extensions/BrandingExtensions.cs
Core/OfficeDevPnP.Core/Extensions/ClientContextExtensions.cs
Core/OfficeDevPnP.Core/Extensions/Deprecated/TenantExtensions.deprecated.cs
Core/OfficeDevPnP.Core/Extensions/FileFolderExtensions.cs
Core/OfficeDevPnP.Core/Extensions/NavigationExtensions.cs
Core/OfficeDevPnP.Core/Extensions/PageExtensions.cs
Core/OfficeDevPnP.Core/Extensions/PnPClientContext.cs
Core/OfficeDevPnP.Core/Extensions/SearchExtensions.cs
Core/OfficeDevPnP.Core/Extensions/TenantExtensions.cs
Core/OfficeDevPnP.Core/Extensions/WebExtensions.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Connectors/OpenXML/PnPPackage.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Model/View.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectWebSettings.cs
Core/OfficeDevPnP.Core/Framework/TimerJobs/TimerJob.cs
Core/OfficeDevPnP.Core/Framework/TimerJobs/TimerJobRunEventArgs.cs
Core/OfficeDevPnP.Core/Pages/ClientSidePageCanvas.cs
Core/OfficeDevPnP.Core/Sites/SiteCollectionCreationInformation.cs
Core/OfficeDevPnP.Core/Utilities/CanvasControl/Processors/ListControlPostProcessor.cs
Core/OfficeDevPnP.Core/Utilities/RESTUtilities.cs
Core/OfficeDevPnP.Core/Utilities/TokenHelper.cs
Core/OfficeDevPnP.Core/Utilities/UrlUtility.cs
Core/OfficeDevPnP.Core/Utilities/Utility.cs
Core/OfficeDevPnP.Core/Utilities/YammerUtility.cs
Core/README.md

Mostly in comments - hopefully I didn't make any mistakes. :)

Some spelling fixes

---

Core/OfficeDevPnP.Core.Tests/PnPCore.Tests.csproj
Core/OfficeDevPnP.Core/PnPCore.csproj

updated project files

---

Core/OfficeDevPnP.Core/Pages/ClientSidePageControls.cs

Added support for custom full bleed webparts with property supportsFullBleed

Fix full bleed web parts

---

Core/OfficeDevPnP.Core/ALM/AppManager.cs

| Related issues?  | fixes #1720 
Added missing negation to check if file exists or not

Fixed - added missing negation to check if file exists or not in ALM

---

Core/OfficeDevPnP.Core/Extensions/ClientObjectExtensions.cs

Provided high level async extension methods for Client Object Extensions.

implement async higher level methods for ClientObjectExtensions

---

Core/OfficeDevPnP.Core/Extensions/FeatureExtensions.cs

This Pull request add new extensions methods providing async support for Features. CC @jansenbe

added higher async level methods for features extensiosn

---

Core/OfficeDevPnP.Core/Extensions/ListExtensions.cs

| New sample?      | yes
| Related issues?  | mentioned in #725 
Additional methods for list property bags
Added method to Get,Add and Remove Indexed property bag
Added method to get and add property bag containing date time value
Added method to Remove a property bag

Feature - added additional support for list property bag methods

---

Core/OfficeDevPnP.Core/CoreResources.Designer.cs
Core/OfficeDevPnP.Core/CoreResources.resx
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectContentType.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectField.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectTenant.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectWebApiPermissions.cs

Fix for issue #1747 and various other engine updates

Engine fixes

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs

This PR fix a compilation issue with OnPrem versions. `ListCreationInformation.ListTemplate` isn't available.

Fix on premise compilation.

---

CHANGELOG.md
Core/OfficeDevPnP.Core/Pages/ClientSidePage.cs

| Related issues?  | fixes https://github.com/SharePoint/PnP-PowerShell/issues/1484
Check if he page is a default home page, and leave the CanvasContent field empty.

Fix for default page

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectField.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/Utilities/FieldUtilities.cs
Core/OfficeDevPnP.Core/OfficeDevPnP.Core.csproj

| Related issues?  | fixes #1786
This PR contains a fix that support passing list web relative url to the `List` parameter of lookup fields.

Changed lookup field privisioning to also handle list url in `List` attribute

---

Core/OfficeDevPnP.Core/ALM/AppManager.cs

| Related issues?  | fixes https://github.com/SharePoint/PnP-PowerShell/issues/1519 and potentially https://github.com/SharePoint/PnP-PowerShell/issues/1183
Bugfix for PnP PowerShell issue 1519 (tested) and possibly PnP PowerShell issue 1183 (not tested but symptoms seem similar). Scope was not passed on thus when providing sitecollection app catalog scope, it would default back to tenant app catalog scope when doing Update-PnPApp. Fixed in joint collaboration with @RobinDijkstra.

Bugfix for updating sitecollection App Catalog app

---

Core/OfficeDevPnP.Core/Extensions/ExternalSharingExtensions.cs

Correcting a few typos :)
| Bug fix?        | ~yes (typos)
Fixed 2 typos in the summary

correct typos

---

Core/OfficeDevPnP.Core/Extensions/InformationManagementExtensions.cs

Adding higher level async methods for information management.

adding information management extensions async

---

CHANGELOG.md
Core/OfficeDevPnP.Core/AuthenticationManager.cs
Core/OfficeDevPnP.Core/Extensions/ClientContextExtensions.cs
Core/OfficeDevPnP.Core/OfficeDevPnP.Core.csproj
Core/OfficeDevPnP.Core/packages.config

| Related issues?  | --
Introduced dependency on ADAL 3.x and updated code accordingly

Introduced support for ADAL 3.x and JWT 5.x

---

Core/OfficeDevPnP.Core/Framework/Graph/GraphUtility.cs
Core/OfficeDevPnP.Core/OfficeDevPnP.Core.csproj

| Bug fix?        | 
| New sample?      | 
Added **GraphUtility** class to perform Graph operations using GraphServiceClient.
Added a method to this class to invite guest user using Azure B2B Invitation API. I will also use this method further to create a command in PnP PowerShell.
Re-submitting this request as the Graph version has been updated in the latest release [#1570](https://github.com/SharePoint/PnP-Sites-Core/pull/1570)

Graph utility class added with a function to invite Guest user (Azure B2B)

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectClientSidePages.cs

| Related issues?  | fixes #1917 
Add token parsing for client side page's Page Name

Add token parsing for ClientSidePage's page name

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs

| Related issues?  | fixes #1910
Fixed File Not Found error when applying template exported from modern team site solving #1910

Fix: File Not Found error when applying template exported from modern team site

---

Core/OfficeDevPnP.Core/Extensions/WebExtensions.cs

| Related issues?  | fixes #1925
Fixed ServerUnauthorizedAccessException when creating web.

Fixed ServerUnauthorizedAccessException when creating web (#1925)

---

Core/nuget.md

| New sample?      | yes
Removed link to Vesa his blogpost as it was outdated and contains many no longer working links. Added references to NuGet packages as they were incredibly hard to find.

Added reference to NuGet Packages

---

Core/OfficeDevPnP.Core/Enums/SharePointPlatform.cs
Core/OfficeDevPnP.Core/Framework/Graph/SiteClassificationUtility.cs
Core/OfficeDevPnP.Core/Framework/TimerJobs/TimerJob.cs
Core/OfficeDevPnP.Core/Utilities/CredentialManager.cs
Core/OfficeDevPnP.Core/Utilities/MailUtility.cs
Core/OfficeDevPnP.Core/Utilities/PnPCoreUtilities.cs

I've been going through the code a lot to figure out a reason for an issue we had - when I was doing that, I added a few summaries to classes and fixed typos where I saw them.

Improvements on comments & fixes typos

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs

Changed proposed default of 50000 to 500 which is the default in SPO.
Updated code not set a default of 500 when not being used towards SPO.

Manual merge of PR #1950

---

CHANGELOG.md
Core/OfficeDevPnP.Core.Tests/Framework/ObjectHandlers/TokenParserTests.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/TokenParser.cs

| Related issues?  | fixes #1972 #1953 #1968
Manually merged #1972 and #1968, with additional cleanup related to ~tokens without {}.

Tokenimprov

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs

| Related issues?  | #1972 
Performance improvement only parsing SiteFields once before processing FieldRefs

ObjectListInstance.ProcessFieldRefs performance improvement

---

Core/OfficeDevPnP.Core/Extensions/FieldAndContentTypeExtensions.cs

Fixes for exception about Id not being initialized when calling ShowContentTypesInNewButton or HideContentTypesInNewButton.

Fix hide content types in new button

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectSearchSettings.cs

Add parsing of tokens when provisioning search settings.

Add token parsing when provisioning search settings

---

Core/OfficeDevPnP.Core.Tests/Framework/ObjectHandlers/ObjectListInstanceTests.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs

| New sample?      | n
Allows parameters to be used and parsed correctly within FieldDefaults elements

Allow parameters in field defaults

---

Core/OfficeDevPnP.Core/Extensions/FieldAndContentTypeExtensions.cs
Core/OfficeDevPnP.Core/Extensions/ListExtensions.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs

| Related issues?  | fixes #1963 https://github.com/SharePoint/PnP-PowerShell/issues/1706
Support provisioning of default column values, and fix path encoding when setting default values.

Default column value

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectNavigation.cs

| Related issues?  | fixes #1860 
Fixed setting structural navigation in provisioning by setting navigation nodes after updating WebNavigationSettings.

Fix provisioning navigation settings

---

Core/OfficeDevPnP.Core.Tests/App.config.sample

Fixed typos

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs

| Related issues?  | #1982
Same problem as #1982

Fixed parsing of SchemaXml

---

Assemblies/readme.md

| Related issues?  | originally proposed in #2071
The readme.md in the Assemblies folder was missing an entry for the 16.0.10000 folder and had also some Markdown issues (at least Markdown-lint was complaining very much...). This PR aims to fix both issues.

Reformatted readme.md for Assemblies

---

Core/OfficeDevPnP.Core/Extensions/PageExtensions.cs
Core/OfficeDevPnP.Core/Pages/AvailableClientSideComponents.cs
Core/OfficeDevPnP.Core/Pages/CanvasColumn.cs
Core/OfficeDevPnP.Core/Pages/CanvasControl.cs
Core/OfficeDevPnP.Core/Pages/CanvasSection.cs
Core/OfficeDevPnP.Core/Pages/CanvasSectionTemplate.cs
Core/OfficeDevPnP.Core/Pages/ClientSideCanvasControlData.cs
Core/OfficeDevPnP.Core/Pages/ClientSideCanvasControlPosition.cs
Core/OfficeDevPnP.Core/Pages/ClientSideCanvasData.cs
Core/OfficeDevPnP.Core/Pages/ClientSideCanvasPosition.cs
Core/OfficeDevPnP.Core/Pages/ClientSideComponent.cs
Core/OfficeDevPnP.Core/Pages/ClientSidePage.cs
Core/OfficeDevPnP.Core/Pages/ClientSidePageHeader.cs
Core/OfficeDevPnP.Core/Pages/ClientSidePageHeaderLayoutType.cs
Core/OfficeDevPnP.Core/Pages/ClientSidePageHeaderTitleAlignment.cs
Core/OfficeDevPnP.Core/Pages/ClientSidePageHeaderType.cs
Core/OfficeDevPnP.Core/Pages/ClientSidePageLayoutType.cs
Core/OfficeDevPnP.Core/Pages/ClientSideText.cs
Core/OfficeDevPnP.Core/Pages/ClientSideTextControlData.cs
Core/OfficeDevPnP.Core/Pages/ClientSideWebPart.cs
Core/OfficeDevPnP.Core/Pages/ClientSideWebPartControlData.cs
Core/OfficeDevPnP.Core/Pages/ClientSideWebPartControlDataOnly.cs
Core/OfficeDevPnP.Core/Pages/ClientSideWebPartData.cs
Core/OfficeDevPnP.Core/Pages/DefaultClientSideWebParts.cs
Core/OfficeDevPnP.Core/Pages/PromotedState.cs
Core/OfficeDevPnP.Core/Utilities/RESTUtilities.cs

| Related issues?  | related to #2074 
This pull request enables the "Pages API" (`OfficeDevPnP.Core.Pages`) for SharePoint 2019. Similar to PR #2074, I added code to add support for and to fix issues with `NetworkCredentials`.
I checked the web parts listed in the enum `DefaultClientSideWebParts` and deactivated those for on-premises environments that caused an error during creation.

OfficeDevPnP.Core.Pages for SP2019

---

CHANGELOG.md
Core/OfficeDevPnP.Core/ALM/AppManager.cs

App Catalog ALM updates

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/Utilities/TenantHelper.cs

This PR fixes the issue with us not being able to set the Private CDN origin and policy capabilities due to the code using the Public CDN values.

Fix: Added capability to set the private CDN orgins and policies

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectClientSidePages.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/Utilities/ClientSidePageContentsHelper.cs
Core/OfficeDevPnP.Core/Pages/ClientSideWebPart.cs
Core/OfficeDevPnP.Core/Pages/ClientSideWebPartData.cs

| Related issues?  | fixes #2079
Ability to export and import Client Side Web Parts that are configured to use Dynamic Data.

Export and import client side web parts with dynamic data connections

---

CHANGELOG.md
Core/OfficeDevPnP.Core/Extensions/SiteExtensions.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Model/ClientSidePage.cs

| Related issues?  | --
Introduces a new extension method called IsCommunicationSite for Site objects.

Added IsCommunicationSite extension method for Site

---

Core/OfficeDevPnP.Core.Tests/Framework/ObjectHandlers/ObjectTeamsTests.cs
Core/OfficeDevPnP.Core.Tests/OfficeDevPnP.Core.Tests.csproj
Core/OfficeDevPnP.Core/CoreResources.Designer.cs
Core/OfficeDevPnP.Core/CoreResources.resx
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectTeams.cs
Core/OfficeDevPnP.Core/Utilities/HttpHelper.cs

Teams provisioning based on a Teams template

Laura teams templates

---

Core/OfficeDevPnP.Core/CoreResources.Designer.cs
Core/OfficeDevPnP.Core/CoreResources.resx
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/TokenDefinitions/SiteCollectionTermGroupId.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/TokenDefinitions/SiteCollectionTermGroupNameToken.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/TokenParser.cs

| Related issues?  | fixes #2197
Revert as per @okms with added logging

Populating site collection termgroup tokens in app context

---

.github/ISSUE_TEMPLATE.md

| Bug fix?        | yes?
| Related issues?  | fixes #2215 
Update link to pnpjs in issue template.

Updated link to pnpjs.

---

Core/OfficeDevPnP.Core/Extensions/TenantExtensions.cs

while groupifying site collection
Added support for HubSiteId and Owners property in the TenantExtension's GroupifySite method.

Feature : Added support for HubSiteId and Site owners property in TenantExtension

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/Utilities/TenantHelper.cs

This PR adds support for NoDefaultOrgin parameter while provisioning O365 Tenant's CDN capability.

Feature: Added support for NoDefaultOrigin while setting CDN capability

---

Core/OfficeDevPnP.Core.Tests/Framework/Providers/XMLSerializer201903Tests.cs
Core/OfficeDevPnP.Core.Tests/OfficeDevPnP.Core.Tests.csproj
Core/OfficeDevPnP.Core.Tests/Resources/Templates/ProvisioningSchema-2019-03-FullSample-01.xml
Core/OfficeDevPnP.Core/Framework/Provisioning/Model/ApplicationLifecycleManagement.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Model/SiteGroup.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/Resolvers/V201903/TemplateSecurityUsersFromModelToSchemaTypeResolver.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/Resolvers/V201903/TenantSiteDesignsWebTemplateFromModelToSchemaValueResolver.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/Serializers/V201801/TenantSerializer.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/Serializers/V201903/ProvisioningTemplateWebhooksSerializer.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/Serializers/V201903/SecuritySerializer.cs
Core/OfficeDevPnP.Core/OfficeDevPnP.Core.csproj

| Bug fix?        | yes?
Unit tests for upcoming 201903 and old schema (de)serialization. 
Closes #2193 
Closes #2212 
References #2194

Unit tests for xml (de)serialization.

---

Core/OfficeDevPnP.Core.Tests/Framework/Providers/XMLSerializer201903Tests.cs
Core/OfficeDevPnP.Core.Tests/Resources/Templates/ProvisioningSchema-2019-03-FullSample-01.xml
Core/OfficeDevPnP.Core/Framework/Provisioning/Model/ClientSidePage.cs

| Related issues?  | fixes #2224 , references #2194 
Added more unit tests for 201913 schema. New nodes introduced in 201913 are covered, 90% of objects and properties from ProvisioningTemplate node are also covered.

Schema 201903 unit tests 

---

Core/OfficeDevPnP.Core/AuthenticationManager.cs
Core/OfficeDevPnP.Core/CoreResources.Designer.cs
Core/OfficeDevPnP.Core/Extensions/InformationManagementExtensions.cs
Core/OfficeDevPnP.Core/Extensions/TenantExtensions.cs
Core/OfficeDevPnP.Core/Extensions/TopologicalSort.cs
Core/OfficeDevPnP.Core/Framework/Graph/SiteClassificationUtility.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Connectors/OpenXMLConnector.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Model/DataRow.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectTeams.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectTermGroups.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/TokenDefinitions/DateNowToken.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/TokenDefinitions/SimpleTokenDefinition.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/Utilities/TermGroupHelper.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/TemplateProviderBase.cs

| Related issues?  | fixes compiler warnings
Fixed xml comments to reduce compiler warnings.

Fixed xml comments to reduce compiler warnings.

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ProvisioningTemplateCreationInformation.cs

 Added capability to export template with just selected lists

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/Utilities/ListItemUtilities.cs

| Related issues?  | #2244 
Fix issue with replacing the tokens for DataRows, for fields other than User/Taxonomy/Lookup types.

Fix DataRow parameters replacement.

---

Core/OfficeDevPnP.Core.Tests/Framework/ObjectHandlers/ObjectTeamsTests.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectTeams.cs

Added methods for removing unallowed characters from mailnickname (when created based on display name) and replacing accented characters with latin ones. Removed unused using directives. Added an unit test for testing the change.

Creating an acceptable mailNickname from displayName

---

Core/OfficeDevPnP.Core.Tests/Framework/ObjectHandlers/ObjectTeamsTests.cs
Core/OfficeDevPnP.Core.Tests/Framework/ObjectHandlers/ObjectTeamsTestsOrdered.orderedtest
Core/OfficeDevPnP.Core.Tests/OfficeDevPnP.Core.Tests.csproj
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectTeams.cs

Review for PR #2292

---

Core/OfficeDevPnP.Core.Tests/Framework/ObjectHandlers/ObjectTeamsTests.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectTeams.cs

Delta changes for Teams channels and tabs:
- Refactored the original SetTeamChannels method
- Added logic for updating team channels and tabs based on the provisioning template
Added unit tests for:
- Testing teams creation based on the provisioning template
- Testing updating Teams channels and tabs based on the provisioning template

Delta changes for Teams channels and tabs

---

Core/OfficeDevPnP.Core/Sites/SiteCollection.cs

Fix for CreateGroupEx with SiteStatus = 1

Fix for CreateGroupEx with SiteStatus = 1

---

Core/OfficeDevPnP.Core/Framework/Graph/UnifiedGroupsUtility.cs

Added documentation for the public "deleted unified group" methods. Minor refactoring.

 Added documentation for the public "deleted unified group" methods

---

Core/ProvisioningEngineTokens.md

| Bug fix?        |yes
| Related issues?  | None
Correcting the documentation, as Associated[owner|member|visitor] group tokens were incorrect.

Corrected AssociatedGroup Tokens

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectHierarchySequenceSites.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectWebSettings.cs

1) Modified the provisioning handler to use the SPSiteManager API to create modern site without 
O365 group.
2) Removed use of deprecated methods in the code.

Feature : Modified TeamNoGroup provisioning to use the new SPSiteManager API

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectTeams.cs
Core/OfficeDevPnP.Core/OfficeDevPnP.Core.csproj
Core/OfficeDevPnP.Core/packages.config

This PR includes minor bugfixes CreateTeam From ProvisioningSchema 
- Checking if team.Security section is configured, if it isn't set this part is skipped.
- Included the TokenParser as parameter to Tabs functionality, allowing to use parameters for Tabs
- In the UpdateTeamChannel made a check for name 'General' as it is not allowed to make PATCH to the General Channel

Minor bugfixes for Channels and Tabs

---

Core/OfficeDevPnP.Core/Utilities/JsonConverters/EmphasisJsonConverter.cs

| Related issues?  | fixes #2401
@PaoloPia EmphasisJsonConverter converter returns now int to make section color work again.

Fix conversion of zoneEmphasis in EmphasisJsonConverter

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/TokenParser.cs

| Related issues?  | fixes issue open in the PnP Schema repo: https://github.com/SharePoint/PnP-Provisioning-Schema/issues/301
This PR should fix the issue reported here: https://github.com/SharePoint/PnP-Provisioning-Schema/issues/301

Fixing issue in Localization Token

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectHierarchySequenceSites.cs

This PR adds support to teamify as well as hide the teamify prompt while provisioning O365 group connected sites.

Feature - added support to teamify and hide the teamify prompt 

---

Core/OfficeDevPnP.Core/Extensions/SecurityExtensions.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Model/Hierarchy/SiteCollection.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Model/Hierarchy/SubSite.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Model/SharePoint/InformationArchitecture/ContentType.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Model/SharePoint/ModernExperiences/ClientSidePageHeader.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Model/SharePoint/Settings/WebSettings.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectPages.cs

This PR fixes some issues reported by static analysis, in particular:
- Using only a sub-set of class members in GetHashCode() functions
- Using & instead of && in logical expression
- Validating the same parameter twice instead of 2 different ones
- Ignoring contructor parameter, using the class field instead
- Checking if "this" is null instead of the class member

Fix issues reported by static analysis

---

Core/OfficeDevPnP.Core/Extensions/TenantExtensions.cs

Enabled some functionality in the tenant extensions for on prem SharePoint versions:
GetSiteGuidByUrl
GetWebTemplates
SetSiteProperties
AddAdministrators
GetSiteCollections
CreateSiteCollection
DeleteSiteCollection

Enabled several functionalities in TenantExtensions for onpremises

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs

@erwinvanhunen  As schema supports now ContentType on Folders this addition takes care that this new attribute is respected and if the ContentType is based on DocumentSet we set properties make it behave and look as DocumentSet.

Fix Provisioning ContentType on Folder and set as DocumentSet

---

Core/OfficeDevPnP.Core.Tests/Framework/Providers/XMLSerializer201909Tests.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Model/SharePoint/ModernExperiences/Theme.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/Utilities/TenantHelper.cs

This PR adds support for the Overwrite attribute while processing tenant themes.
With this attribute present, we will check if a theme is present or not.
If it is not present, we will add the tenant theme.
If it is present and if its set to Overwrite, then we will update the tenant theme else skip its processing.

Feature: Added support to overwrite tenant themes

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/SiteToTemplateConversion.cs

| Related issues?  | fixes #2442
This PR adds additional null check while provisioning tenant hierarchy which dont contain webhooks

Fix : Additional null check while provisioning webhooks

---

Core/OfficeDevPnP.Core.Tests/Framework/ObjectHandlers/ObjectTeamsTests.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectTeams.cs

Implemented AllowToAddGuests setting for teams + unit tests
The implementation of AllowToAddGuests setting for teams related unified groups (controls external sharing).

AllowToAddGuests setting for teams

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectTeams.cs

Documentation for the AllowToAddGuests methods.

Documentation for the AllowToAddGuests methods

---

Core/OfficeDevPnP.Core/Extensions/SearchExtensions.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Model/SharePoint/Settings/SiteSettings.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Model/SharePoint/Settings/WebSettings.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectSiteSettings.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectWebSettings.cs

* Added support for searchbox in header settings - prepare for schema support
* Added code to enable/disable noscript if needed when setting search box url

Search box in header

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectHierarchyTenant.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectTenant.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/Utilities/TenantHelper.cs

This PR adds support to set User profile property values when provisioning via Tenant templates.
Currently, have only added support for Single valued properties as i couldn't find a  proper way to set Multi-valued properties.

Feature: Added support for setting user profile property values

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectTeams.cs

Removed duplicated call to retrieve tabs. This call is also executed in the GetTeamChannelTabs method.

Removed duplicated call to retrieve tabs;

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs

This fix makes sure that Folder Properties (came with last schema update) specified are provisioned to the Folder Fields.

Set Folder Fields according to Folder.Properties in Template

---

Core/OfficeDevPnP.Core/Extensions/TenantExtensions.cs

Adding paging to GetHubSiteChildUrls so it works with tenants having more than 5000 site collections as well. With the current code, it would throw an exception about exceeding the list view threshold.

Adding paging to GetHubSiteChildUrls

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectContentType.cs

| Related issues?  | fixes code formatting change introduced in #2501 
Changed indentation formatting back to spaces after had been changed to tabs in #2501. Spaces is the default indentation formatting in the project and also Visual Studio. 
Indentation formatting using spaces should be a requirement for contributing code as it introduces difficulties in merging when formatting changes back and forth based on developer preferences.

Change indentation back to spaces.

---

Core/OfficeDevPnP.Core.Tests/Extensions/ClientObjectExtensionsTests.cs
Core/OfficeDevPnP.Core.Tests/Extensions/SecurityExtensionsTests.cs
Core/OfficeDevPnP.Core.Tests/Framework/Functional/Implementation/LocalizationImplementation.cs
Core/OfficeDevPnP.Core.Tests/Framework/ObjectHandlers/ObjectFilesTests.cs
Core/OfficeDevPnP.Core.Tests/Utilities/WebParts/XsltWebPartPostProcessorTests.cs
Core/OfficeDevPnP.Core/Extensions/BrandingExtensions.cs
Core/OfficeDevPnP.Core/Extensions/FeatureExtensions.cs
Core/OfficeDevPnP.Core/Extensions/FieldAndContentTypeExtensions.cs
Core/OfficeDevPnP.Core/Extensions/FileFolderExtensions.cs
Core/OfficeDevPnP.Core/Extensions/ListExtensions.cs
Core/OfficeDevPnP.Core/Extensions/PageExtensions.cs
Core/OfficeDevPnP.Core/Extensions/TaxonomyExtensions.cs
Core/OfficeDevPnP.Core/Extensions/WebExtensions.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Connectors/SharePointConnector.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectClientSidePages.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectFiles.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstanceDataRows.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectNavigation.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectSiteSecurity.cs
Core/OfficeDevPnP.Core/Pages/ClientSidePage.cs
Core/OfficeDevPnP.Core/Sites/SiteCollection.cs

In this PR, replaced the `EnsureProperties` method with `EnsureProperty` method across the framework where necessary.

Fix: ensuring correct usage of EnsureProperties method

---

PnP-Sites-Core.yml

These changes allow us to automatically update the Office and M365 galleries (https://developer.microsoft.com/en-us/microsoft-365/gallery) with information for this tool. This also allows us to dynamically surface these tools in the Office / SharePoint Developer Portals, so that developers see the most up-to-date information.**

Add YAML metadata for PnP-Sites-Core

---

Core/OfficeDevPnP.Core/Framework/Graph/UnifiedGroupsUtility.cs

Add a method called `GetNestedUnifiedGroupMembers` which will get all the users in a group including the users that are present in nested groups.
Instead of editing and disturbing the existing `GetUnifiedGroupMembers` and `GenerateGraphUserCollection` I have added separate methods. However, if this functionality can be implemented in the same methods please feel free to or let me.
- GetNestedUnifiedGroupMembers (line 948)
- GenerateNestedGraphUserCollection (line 1108)
- GenerateGraphGroupCollection (line 1141)

Added GetNestedUnifiedGroupMembers method

---

Core/OfficeDevPnP.Core/Enums/GraphSubscriptionChangeType.cs
Core/OfficeDevPnP.Core/Enums/GraphSubscriptionTlsVersion.cs
Core/OfficeDevPnP.Core/Framework/Graph/Model/Subscription.cs
Core/OfficeDevPnP.Core/Framework/Graph/SubscriptionsUtility.cs
Core/OfficeDevPnP.Core/OfficeDevPnP.Core.csproj

Adding creading/retrieving/updating/deleting Microsoft Graph Subscriptions for webhooks

Adding CRUD operations for Microsoft Graph Subscriptions

---

Core/OfficeDevPnP.Core/Extensions/FileFolderExtensions.cs

| Related issues?  | fixes #2649 
This PR fixes the incorrect check while converting a folder to a document set.

Fix #2649 - Added correct document set content type check

---

Core/OfficeDevPnP.Core/Sites/SiteCollection.cs

Making `GetValidSiteUrlFromAliasAsync` public and adding `GetIsAliasAvailableAsync` inside `Sitecollection.cs` to allow validation if an alias is still available to be used to create a new sitecollection with.
Will be used by PnP PowerShell through PR https://github.com/pnp/PnP-PowerShell/pull/2698

Adding GetValidSiteUrlFromAliasAsync and GetIsAliasAvailableAsync

---

Core/OfficeDevPnP.Core/Extensions/ClientContextExtensions.cs
Core/OfficeDevPnP.Core/Extensions/PageExtensions.cs

| Bug fix?        |  yes? -- for 1438, 2371 & 2677
https://github.com/pnp/PnP-PowerShell/issues/1438
https://github.com/pnp/PnP-PowerShell/issues/2371
https://github.com/pnp/PnP-PowerShell/issues/2677
Fix for 1438, 2371 & 2677

Fix 403 GetWebPartXML On Prem  1438, 2371 & 2677

---

Core/OfficeDevPnP.Core/Extensions/NavigationExtensions.cs

Bugfix in LoadFooterNavigation causing no navigation items to be returned, added GetFooterTitle, SetFooterTitle, GetFooterLogoUrl, SetFooterLogoUrl and RemoveFooterLogoUrl methods to allow configuration of the footer on a communication site

Bugfix in LoadFooterNavigation + added Footer Title & Logo methods

---

Core/OfficeDevPnP.Core/Framework/Graph/UnifiedGroupsUtility.cs

| Related issues?  | Requested for PnP PowerShell through https://github.com/pnp/PnP-PowerShell/issues/2743
Added public methods for adding/removing/clearing members and owners of Microsoft 365 Groups

Added methods for adding/removing/clearing members and owners of M365 Groups

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/Utilities/ListItemUtilities.cs

| Related issues?  | no
Fix - UpdateListItem: Ignor ID column. ID column cannot be updated (Exception: This field cannot be updated.) 
Sometimes the ID column is used as KeyColumn for DataRows.

Fix - UpdateListItem: Ignor ID column. ID column cannot be updated.

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectSiteSecurity.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/TokenParser.cs

| Related issues?  | Not sure
This PR adds minor token parsing changes.
1) After clearing the token for group changes, added that token again for use downstream.
2) Replaced the HTTP request with the unified groups method due to 100 limit of groups retrieved.

Fix: Token parsing changes

---

Core/OfficeDevPnP.Core/Extensions/SecurityExtensions.cs

This PR improves the ability to fetch site collection admin and remove them in a site collection with large no. of users.
Credit to @MrTantum  for figuring this out and fixing it in the PnP PowerShell library.

Fix: Site collection admin timeout issue

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstance.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/TokenParser.cs

| Bug fix?        | no/yes
| New feature?    | no/yes
With this PR it will become possible to use tokens inside a ListInstance which references a list field of the same list or the list itself. Also for adding list fields to the ListInstance, tokens can now reference the list itself or other list fields in that same list.
Samples of where this will be useful:
<pnp:ListInstance Title="Sample Calendar"
TemplateType="106"
Url="Lists/SampleCalendar"
EnableFolderCreation="false"
ValidationFormula="=(([{fieldtitle:EndDate}]-[{fieldtitle:EventDate}])*24)&gt;4"
ValidationMessage="The active time should be a minimum of 4 hours">
</pnp:ListInstance>
Here the Validationformula references two list fields …

Allow tokens referencing the current list

---

Core/OfficeDevPnP.Core/AuthenticationManager.cs

Added `loginRequestUri` to `GetWebLoginClientContext` in `AuthenticationManager.cs` to allow providing a specific URL to log on to. This solves an issue when you are connecting using this method to the SharePoint Online Admin Center. If the tenant you're connecting to is using the new modern experience, it will go through a redirect before it loads the page and completes the login. If the tenant you're connecting to uses the classic SharePoint Online Admin Center experience still, it will load the classic page listing all site collections which can take up to minutes to be loaded and thereby complete the login cycle. By adding this optional …

Allow providing a specific URL with GetWebLoginClientContext to log on to

---

Core/OfficeDevPnP.Core/Framework/Provisioning/Model/Teams/BaseTeam.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/Model/Teams/Team.cs
Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectTeams.cs
Core/OfficeDevPnP.Core/Utilities/Graph/GraphHelper.cs

||
| Related issues?  | fixes #2427 
This PR adds stability and performance improvements while working with teams provisioning and delta changes.
1) It checks the archive state of the team and depending on that archives/un-archives the team.
2) While working with a team which is already archived, it will first check the state. If it is archived, it will check the flag value and based on that will un-archive or skip processing that particular team.
3) Currently, while trying to add a new channel to an already existing team, it is not working. Have fixed that by returning the Id property of the team.
4) Moved multiple endpoints from beta to v1 where possible. Have tested it thoroughly and didn't …

Feature : multiple improvements while working with Teams

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectWebSettings.cs

| Related issues?  | partially fixes #2475 
This PR adds additional SharePoint admin check while extracting Hub site url as well as while associating a web to a hub site since we are using TenantContext.

Feature : additional check while extracting/setting hub site

---

Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/Utilities/TenantHelper.cs

Fixed bug highlighted in #2613 with apps in AppCatalog

Fixed bug highlighted in #2613 with apps in AppCatalog

---

Core/OfficeDevPnP.Core/Framework/Graph/UnifiedGroupsUtility.cs

| Related issues?  | fixes #2761
Fixed incorrect HasTeamsTeam check. Currently, it always returns false because we are using the incorrect endpoint.

Fix: Incorrect HasTeamsTeam check

---

Core/OfficeDevPnP.Core/Framework/Graph/UnifiedGroupsUtility.cs

| Related issues?  | fixes #2773 
Fixes #2773 by changing the exception type to generic exception to handle duplicate members and owners

Fix #2773 - changed Exception type for duplicate members and owners
